### ISSUE TITLE
Investigate BrowserStack integration

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#1013]

**Comment by mzgol** [comment]
This will need resource management similar to what [karma-browserstack-launcher](https://github.com/karma-runner/karma-browserstack-launcher) has (using [the npm browserstack module](https://www.npmjs.com/package/browserstack)). Otherwise running this with too many browsers will immediately fail with a message:
```
UnknownError: N sessions are currently being used. Please upgrade to add more parallel sessions.
```

**Comment by elgalu** [comment]
What's still missing is Protractor to update the tests results via the API

```js
{
    uri: 'https://www.browserstack.com/automate/sessions/' +
          sessionId + '.json',
    method: 'PUT',
    json: { "status": status }
}
```
