### ISSUE TITLE
Matching Strings to be case insensitive

### ISSUE THREAD

**Issue by mohit-excelindia** [angular/protractor#1082]
Hi @juliemr 

In my application I have status of an event.
I have created an object for those status while writing test scripts like this:

var satus = {
  open : 'Open',
  inProgress : 'In-Progress'
  closed : 'Closed'
};

I have that status displayed in many pages of the application and at different pages it is written in Upper Case letters while not in others.

Can we expect Strings as insensitive?

Thanks,
Mohit

**Comment by padmarao123** [comment]
ok

**Comment by caneraydinbey** [comment]
Failed: expect(...).toLowerCase is not a function

**Comment by caneraydinbey** [comment]
for
`element.all(by.css('span[ng-if="vm.selectedMerchant"]')).first().getText().toLowerCase()
`

> ERROR: TypeError: element.all(...).first(...).getText(...).toLowerCase is not a function


but

for

`element.all(by.css('span[ng-if="vm.selectedMerchant"]')).first().getText()`

there is output string.. What is wrong?

**Comment by vynomer** [comment]
If I'm reading your question correctly, caneraydinbey, the answer to your question relates to promises. 

The element.all function is an asynchronous function known as a promise, as are the first and getText functions, chaining off of the element promise. Because of this, you're not actually getting a string back.  In contrast, the lowerCase is a synchronous function, one which is on the String prototype. The expect function can take a promise and resolve it, using the result, which is why it seems like getText returns a string.

If you wanted to actually lower case the results of your getText, you'd need to chain another promise to the end of it, a then promise most likely, which will take the text from the resolution of the getText promise. Then, you can lowercase the text, and return it for the expect statement.

Here's an example, where I set it to a variable for ease of use:

var textElementText = element.all(by.css('span[ng-if="vm.selectedMerchant"]')).first().getText().then(function(text){ return text.lowerCase() })

expect(textElementText).toContain('lowercase')

Of course, this assumes that textElementText actually contains the string 'lowercase', otherwise the test fails.
