### ISSUE TITLE
Drag and Drop is confusing. Document better, or create a better syntax to work with it

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#1205]
Using an action sequence is hard, and causes a lot of confusion. Let's discuss how to make this easier.

**Comment by pidupuis** [comment]
Any advance on this topic ?
I am currently not able at all to simulate a drag and drop... I would really like to have a better flexibility and a better documentation

**Comment by mgiambalvo** [comment]
We're not going to make any API changes. However, I'll do the following

- [] Add the browser.actions() API to our docs
- [] mention this in the FAQ (and also mention that HTML5 DnD events do not work in Chrome due to a known [chromedriver issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=841))
- [] add a cookbook example for doing drag and drop
