### ISSUE TITLE
Protractor Tests without a Backend (or how to mock a backend)

### ISSUE THREAD

**Issue by mren** [angular/protractor#125]
Hi!

I want to write integration tests for an angular app with protractor.
As @juliemr mentioned in [a comment to a similar issue](https://github.com/angular/protractor/issues/31#issuecomment-21265369) written by @mrappleton, Protractor is intended for End to End Tests with an actual backend hooked up.
This is a reasonable use case and good to know.

However in my case I have a fairly well tested Backend.
Therefore I would prefer to have my protractor tests not depend on my backend.

The advantages of this could be

- Testing the angularjs app can be done in separation of the server
- I won't test things twice
- Less dependencies to worry about

I played around with something similar to @leifhanack [backend dsl](https://github.com/angular/protractor/issues/69).
It is possible to test the whole App and Mock the Api Routes in the Test.
However this feels like a lot of overhead (setup rest server in each test, worry about body parsers,...)

In my App I have a Api Module that talks to the server.
I would really like to spy and mock this Api Module from the tests.
This is difficult as the tests (protractor) are not executed in the same scope as the app (selenium driven browser).

I would fancy to do something like this in my tests:

```javascript
Api = $injector.get('Api');
sinon.mock(Api, 'getSomethingFromServer').andRespondWith({foo: 'bar'})
// do tests, go to page, fill out form, submit form, etc...
assert(Api.getSomethingFromServer.wasCalledOnce);
```

In this case I could test the client in seperation without doing a lot of boilerplate to get up running.
I know that this is not possible right now, because `$injector` is running in the browsers scope.

The only way to do something similar would be to use `ptor.addMockModule`.
This is limited, as it is only possible to replace whole modules (and not mock parts of it) and it is difficult to make assertions on the mocked functions (something like `mockedModule.function.wasCalledOnce`)

What would be a great way to mock the access to the backend to test an angular app in isolation?

What is the angularjs teams view on this issue?

**Comment by ddelnano** [comment]
@nadersoliman I am trying to use the tool you linked too however I get ```ReferenceError: HttpBackend is not defined```.  I am new to angular and I am struggling would you happen to have a working example of this?

**Comment by shoshanatech** [comment]
I can't get any httpBackend mock working with my seemingly simple login service.  I've tried both atecarlos and kbaltrinic's libraries - each does exactly the same - if I start the real server, the test works fine.  If I turn off the server and run only with mocks, they fail, leaving me believing that httpBackend is not being mocked.  Here's  my test:
=============
var HttpBackend = require('http-backend-proxy');
var proxy = new HttpBackend(browser);
var loginUser;  // fixture with some users

describe('login', function () {
    beforeEach(function () {
        browser.get('http://localhost:8100');  // get root
        browser.executeScript("localStorage.removeItem('activeUser');");  'make sure token is empty'
        browser.sleep(2000);
        loginUser = require('../login.json');
    });

    beforeEach(function () {
        browser.ignoreSynchronization = false;
        // regex for http://(myserver)/authenticate/login?username="aname"
        proxy.whenGET(/\/login\//).respond(loginUser[0]);
    });

    afterEach(function() {
        browser.manage().logs().get('browser').then(function(browserLog){
            if(browserLog.length) console.log('log:'+ JSON.stringify(browserLog));
        })
    });

    it('should go to mainmenu after successful login', function () {
        element(by.model('username')).sendKeys('tlouisa');
        browser.sleep(2000);
        element(by.id('btnLogin')).click();
        browser.sleep(2000);
        expect(browser.getCurrentUrl()).toEqual('http://localhost:8100/#/mainmenu');
    });

**Comment by atecarlos** [comment]
Hi @shoshanatech. Feel free to submit an issue on protractor-http-mock so we can work out whatever issue it is you are having.

**Comment by kbaltrinic** [comment]
@shoshanatech I'll echo @atecarlos sentiments, whichever library you prefer to use, post an issue to the appropriate one and we'll do what we can to help.  You may also want to take a look a the closed issues, I can't speak for protractor-http-mock, but most of the common issues for the http-backend-proxy have come up and there is at least one closed issue dealing with it.  

Without knowing more details, at a guess, I would say that you are not loading the [ngMockE2E module](https://docs.angularjs.org/api/ngMockE2E) in the browser.

**Comment by rfodge** [comment]
Just wondering if anyone has a good solution for updating mocked called within a protractor test.  I need to be able to mock a call (which I can do using ngMockE2E) but the next time the call is made, I want it to come back with different results.

httpbackend.when('GET', ....URL....).respond(200, results);
where results is a json object that is returned

The first time the call is made is it coming back with the correct json.  But within the same test, I want to update those results so that the next time the call is made, it returns the updated json.

Thoughts?

**Comment by kbaltrinic** [comment]
@rfodge, The solution to having the same call return different responses is to place logic in the response call back function to return different responses under different circumstances.  

If you are using the http-backend-proxy, you can use the context object to accomplish this.  Simply have the callback function return a value defined on the context object, then change the value and manually re-sync the context between tests.  [Here are the relevant docs.](https://github.com/kbaltrinic/http-backend-proxy/wiki/Installation-&-Usage#calling-functions-and-sharing-data-between-tests-and-browser)

**Comment by rfodge** [comment]
Thank you!  I was able to get that working based on the responses on the issue thread in github. :)

**Comment by nabil-boag** [comment]
A project called [Angular Multimocks](https://github.com/wongatech/angular-multimocks) solves a lot of the problems people are having here. It is a wrapper around $httpBackend that allows you to create mock files as simple JSON files and them compose mocks into various scenarios.

**Comment by germanio** [comment]
Hope this is still active. I have a question about mocking the backend:

How do you organize the mocks when the app grows?

I mean, if we start mocking $httpBackend calls for each test, we quickly end up having a big list of `.whenGET(/foo\/bar/).respond(mockResponse);` to maintain in a single file, and also duplicated for each test, right?
We managed to add the data for the response (the one that goes in `mockResponse`) from a different file, which makes much easier to maintain and read, but after a while, those files are again big enough to make maintenance a problem. 
So I tried to divide that list in at least two calls to `browser.addMockModule()` that adds different `module.run()`, but the last one added seems to overwrite the first one. I don't understand why that happens since each call adds a different module, and each `module.run()` is supposed to add mock calls to the same $httpBackend (mock) instance, right? 
Any thought on how to DRY my mocks will be appreciated.
PS: I will take a look at what @nabil-boag has shared, it looks promising.

**Comment by nabil-boag** [comment]
Hey @germanio, [Angular Multimocks](https://github.com/wongatech/angular-multimocks) does help solve the problem you talk about by allowing you to define mocks once and then load them up in different scenarios. 

Full disclosure, I am the maintainer of Multimocks 😸. If you need any help getting set up let me know.

**Comment by jonbcampos** [comment]
All that are watching this. I haven't worked with Multimocks, though I am sure it is a great solution. In my last project I set up a mini framework around [protractor http mocks](https://github.com/atecarlos/protractor-http-mock) with great success. There was a bit of setup (hence the mini framework) but it did work well for me.

Ultimately protractor tests are e2e tests and therefore should be hitting real services. I'm sure we all agree on that already though.

**Comment by nabil-boag** [comment]
Hey @jonbcampos,

If your goal in testing is to do a full integration test of your stack then mocking the backend is probably counter-productive.

I think a lot of people want to use protractor to acceptance/service test their front end applications in isolation of a back end. 
My argument though is that real backends are inconstant and inflexible. If you use a real backend, ask yourself the following questions:

* What happens when my test fails?
* Was it my application or did the internet connection fail?
* Was the API team deploying code when I was running my test?
* What happens if the API is offline or has a version deployed that conflicts with my application?

If your application makes very few API calls or the UX doesn't change based on different API responses then Angular's built-in ngMock mocking tools are great.

However, as applications grow in size and complexity, integration tests become increasingly flakey (non-deterministic). Mocks allow you to control the test process carefully, but it can become difficult to manage API response mocks, change scenarios and test complex UX interactions (which is what people like @germanio are experiencing).

**Comment by blabno** [comment]
Guys, to you really run all the edge cases with real backend?
Mocks are a must!

2016-04-13 11:27 GMT+02:00 Nabil Boag <notifications@github.com>:

**Comment by jonbcampos** [comment]
While I always appreciate a long over explanation, I already agreed and
that is why I've said I use protractor HTTP mocks with great success.

**Comment by nabil-boag** [comment]
Sorry for the long comment @jonbcampos.

**Comment by jonbcampos** [comment]
no worries. I was more hoping to stem the tide of others that were starting
to jump on board thinking we weren't in agreement.

On Wed, Apr 13, 2016 at 9:22 AM, Nabil Boag <notifications@github.com>
wrote:

> Sorry for the long comment @jonbcampos <https://github.com/jonbcampos>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/protractor/issues/125#issuecomment-209471696>
>



-- 
Jonathan Campos

**Comment by juliemr** [comment]
I'm glad there's been good discussion here, and I think people have brought up good points about the advantages and disadvantages of mocking out backends. I think these are good questions to ask, but I'm not sure that this issue is the best place to do them. We're cleaning up issues, so I'm going to go ahead and close this one.

**Comment by jdnichollsc** [comment]
Thanks for the examples! Guys, check my example without more npm modules, you can clone and test! yay! 💃 https://github.com/jdnichollsc/Game-of-Drones/tree/master/FrontEnd/tests/e2e-tests

**Comment by EvtK** [comment]
I have ngMockE2e in place to return mocks as separate json file, based on a synchronous XMLHttpRequest. I have created a decorator for the ngMocke2e httpbackend to be able to manipulate the response time of the various backend calls that don't go with a PassThrough.

```
$provide.decorator('$httpBackend', function ($delegate) {
var proxy = function (method, url, data, callback, headers) {
  var waitTimes = [
    { regex: /^.*BackendCallUri1.*$/, response: 3000 },
    { regex: /^.*BackendCallUri2.*$/, response: 1500 }
  ]; 
var responseTime = 0;
var found = false;
  angular.forEach(waitTimes, function (waitTime) {
    if (!found && waitTime.regex.test(url)) {
      responseTime = waitTime.response;
      found = true;
    }
  });
  var interceptor = function () {
    var _this = this,
      _arguments = arguments;

    setTimeout(function () {
      callback.apply(_this, _arguments);
    }, responseTime);
  };

  return $delegate.call(this, method, url, data, interceptor, headers);
};
for (var key in $delegate) {
  proxy[key] = $delegate[key];
}
return proxy;        
```


As you can see the default responsetime is 0, but you can configure each call separatly. Anyways.. the thing is that protractor doesn't seems to catch these waittimes. If I set them all to 0, test runs ok. But as soon as I configure a wait time, protractor doesn't wait for the response to be returned. Failing my tests. Is what I have achieved with the wait times not supported by waitForAngular() ?

BTW: I'm still on angular. 1.5.8. Upgrading to 1.6.2 [for this fix](https://github.com/angular/angular.js/commit/bd63b2235cd410251cb83eebd9a47d3102830b6b) didn't solve the issue.

Any suggestions?

**Comment by Pragati103** [comment]
Hi it is possible to use mockservice in e2e testing

**Comment by Pragati103** [comment]
Any suggestions?
