### ISSUE TITLE
Explicit include test files doesn't work when shardTestFiles = true

### ISSUE THREAD

**Issue by hvdb** [angular/protractor#1357]
When you run with shardTestFile: false (default) and have a spec with ddescribe it only runs this describe.
When you set shardTestFiles: true it will run all tests, not only the ddescribe.

I would expect that the behaviour is the same.

When using a mix of shardTestFiles: true/false this will give you not the same results.
We had tests failing when we used shardTestFiles, so we set that to false for IE to see if that is the problem.

"All"  tests passes, but it was only one test :) instead of the full suite.

**Comment by csymeonides** [comment]
Hi, sorry to post on a closed issue but I don't really understand why fdescribe (or ddescribe) is not supported. It's a really useful way of testing a specific feature, which you want to do quickly while developing/testing, and it sounds like you would need to run protractor with a different config file (which has sharding disabled) in order to do that. Also, what if the test covers several different pages, and is therefore called from several different test files? You might want to run a sharded job (so that it finishes faster) in order to test them all, but again only that particular test.

**Comment by zenmaster15** [comment]
> Do we actually need this feature? It doesn't seem like something protractor should support for two reason:
> 
> 1. using sharding with ddescribe or iit will always be a mistake than anything intentional.
> 2. it seems like trouble down the road if we infuse jasmine into protractor (i.e. to understand what iit and ddescribes are, which are only in jasmine) instead of using the frameworks to run tests like what we have now.

currently facing an issue in my project which is set up to run specific test suites using fit s and we used sharding to speed up things. Would have been useful
