### ISSUE TITLE
How To Pass Configuration To PhantomJS?

### ISSUE THREAD

**Issue by Jacob-Friesen** [angular/protractor#150]
Hello,

Is there a way to specify command line arguments passed (or do something else that has the equivalent effect) to PhantomJS in Protractor? Specifically, I need to pass in --web-security=false so I can do E2E tests with CORS.

**Comment by btmurrell** [comment]
There has been a lot of FUD and misinformation posted here and around other threads... I've spent hours getting to the bottom of this, and I can share these facts based on my experiences (phantomjs version 1.9.8):

1. You must specify the phantom args as a string, *not* and object structure:

    **BAD:**
    ```
    capabilities: {
      'phantomjs': {
        'cli': {
          'args': ['web-security=false']
        }
      }
    }
    ```
    **GOOD:**
    ```
    capabilities: {
      browserName: 'phantomjs',
      'phantomjs.binary.path': require('phantomjs').path,
      'phantomjs.cli.args': ['--web-security=false', '--ignore-ssl-errors=true', '--webdriver-loglevel=DEBUG'],
    },
    ```

2. The value of `phantomjs.cli.args` must be an array, *not* a string

    **BAD:**
    ```
      'phantomjs.cli.args': '--web-security=false --ignore-ssl-errors=true --webdriver-loglevel=DEBUG'
    ```

    **GOOD:**
    ```
      'phantomjs.cli.args': ['--web-security=false', '--ignore-ssl-errors=true', '--webdriver-loglevel=DEBUG'],
    ```

3. You must supply *only* valid arguments to `phantomjs.cli.args`.  If you supply any arguments (or values?) that phantomjs does not recognize, your protractor dies with an error (`UnknownError: null`)... The stack trace comes from a promise, so it is impossible to see the root cause. (any other app would just ignore arguments it does not recognize, but not here... that said I don't know where to point the finger here because there are so many layers [webdriver -> ghostjs -> phantomjs]).

    **BAD:**
    ```
    'phantomjs.cli.args': ['--web-security=false', '--ignore-ssl-errors=true', '--logLevel=DEBUG']
    ```

    **GOOD:**
    ```
    'phantomjs.cli.args': ['--web-security=false', '--ignore-ssl-errors=true', '--webdriver-loglevel=DEBUG']
    ```
    [E.g., note bad `--logLevel` vs. good `--webdriver-loglevel`... this obviously applies to any invalid argument.]

    These arguments are [valid phantomjs](http://phantomjs.org/api/command-line.html) arguments and/or valid webdriver arguments (which include `--webdriver-loglevel` and `--webdriver-logfile` as far as I can tell from reading the src).   


All this said, I still have not been able to get webdriver to successful write to the log file... Without specifying `--webdriver-logfile`, the default file is `phantomjsdriver.log` in the current directory.  If you get any error while running the protractor test, the phantomjs process stays running.  By viewing `ps` output, you can see the arguments successfully passed to phantomjs... however, I never see anything in the specified phantomjsdriver.log file.  In fact, even though I see the file specified in the `ps` output, I do not see the file on my file system.   I welcome any suggestions on how to get logging in there.

Hope this helps.

**Comment by EugeneSnihovsky** [comment]
Hi everyone. I have faced [this](https://github.com/ariya/phantomjs/issues/14095) issue using protractor + cucumber.js.
**SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"**

As [solution](https://github.com/ariya/phantomjs/issues/14095#issuecomment-280867264) I need to pass **-platform windows:dpiawareness=0** to PhantomJS.
I tried to use capabilities config section
```javascript
capabilities: {
         'browserName': 'phantomjs',
         'phantomjs.binary.path': require('phantomjs-prebuilt').path,
         'phantomjs.ghostdriver.cli.args': ['--loglevel=DEBUG'],
         'phantomjs.cli.args': ['-platform windows:dpiawareness=0']
     }
```
And has an error
```bash
[11:53:01] I/local - Starting selenium standalone server...
[11:53:01] I/launcher - Running 1 instances of WebDriver
[11:53:02] I/local - Selenium standalone server started at http://192.168.0.107:55637/wd/hub
[11:54:02] E/launcher - null
[11:54:02] E/launcher - WebDriverError: null
```

Can someone tell me please, how to pass params to PhantomJS right way?
