### ISSUE TITLE
sendKeys is very slow in IE 11

### ISSUE THREAD

**Issue by santhoshchunchu** [angular/protractor#1506]
Hi All,

FYI recently my IE got upgraded to IE 11 and when I recently run the scripts it is executing very very slow.... Do anyone have faced the same problem. Do let me know.

The login page is taking nearly 2 sec for each character to enter in the text field.

Thanks,
Santhosh Chunchu

**Comment by dpaquette** [comment]
How do you change to the 32 bit IE Driver when using Webdriver-manager?

**Comment by codecadwallader** [comment]
@dpaquette I've been struggling with the same this week, here's what I found:

The Webdriver-manager asks Node to provide the system architecture through an 'os.arch()' call, and chooses the URL accordingly.  https://github.com/angular/protractor/blob/master/bin/webdriver-manager#L73

There isn't currently a way to pass in a configuration, but there's an open feature request here #1297 

Node actually doesn't report the OS architecture on 'os.arch()', but whether or not the current process is 32-bit or 64-bit: https://github.com/joyent/node/issues/2862  I've confirmed it using Node v0.12.5, but this issue is three years old so it's apparently been that way for awhile.

As a workaround, if you're running the 32-bit version of node instead of the 64-bit version, then the Webdriver-manager will resolve the 32-bit version of the IE driver.  Note: On Windows you may want to make sure your path is pointing to the correct 32-bit version of node (e.g. c:\program files  (x86)\nodejs).

Hope it helps.

**Comment by dpaquette** [comment]
@codecadwallader I managed to get another workaround working for me yesterday. I manually downloaded the 32-bit copy of IEWebDriverServer and overwrote the file in C:\Users\myusername\AppData\Roaming\npm\node_modules\protractor\selenium. The catch was that I had to download the same version as the one that was previously installed (in my case 2.45).

**Comment by Moutaz99** [comment]
Download the 32bit IEdriver and use it insted of the 64 bit

**Comment by yogeshgadge** [comment]
Even 32bit IEDriver gets slower.

**Comment by cs-NET** [comment]
Just to help anyone else that ends up here after hours of searching.

### Install 32bit IE Driver
```
webdriver-manager update --ie32
```

### Start Protractor with the 32bit IE Driver 
_(if you are running 64bit os you must add switch or it will try to load 64bit driver)_
```
webdriver-manager start --ie32
```

**Comment by juliemr** [comment]
@cnishina do you think we should default to the ie32 for webdriver-manager?

**Comment by AdamRzymowski** [comment]
This still seems to be an issue. I tried the webdriver-manager start --32 and it is still very slow.

**Comment by yashhy** [comment]
32Bit IE driver solves this problem.
For those who are searching for the drivers, link is [here](http://selenium-release.storage.googleapis.com/index.html)

**Use in protractor conf like below:**
`exports.config = {`
     `   seleniumArgs: ['-Dwebdriver.ie.driver=node_modules/protractor/selenium/IEDriverServer.exe']`
`}`

**Comment by cnishina** [comment]
After responding to #1999, I think we should just default to ie32 and not bother with the x64 version of IEDriver.

So the following will by default download / start the 32-bit version:

```
webdriver-manager update --ie
webdriver-manager update --ie32
webdriver-manager start --ie
webdriver-manager start --ie32
```

If someone really needs the x64 version, we'll have add a flag:
```
webdriver-manager update --ie64
webdriver-manager start --ie64
```

In the help option, I'll also add that the x64 version has been known to be flaky.

**Comment by cnishina** [comment]
Closing this issue in favor of: https://github.com/angular/webdriver-manager/issues/180

**Comment by santhoshchunchu** [comment]
Finally after 2 years it got closed :) Happy holiday to all :)

**Comment by kalrajyoti** [comment]
i used ie32 driver and my login page is in frame  ,when i tried to run the script ,it is unable to locate my frame using ie32 driver
and same script is working fine with ie64 and its easily handling frame.(but it is type slow as character wise)

Any solution?

**Comment by Harsha509** [comment]
Try to update ie32 bit, webdriver-manager update --ie32. And then start the server.

Also ask debug questions in stack overflow.

Micromax

**Comment by smajazayeri** [comment]
The same issue for me. The --ie32 runs IEDriver 32, but it doesn't resolve the issue of low performance of sendKeys(). Any thoughts?

**Comment by laffuste** [comment]
Another option:
```
capabilities: {
    'browserName': 'internet explorer',
    'requireWindowFocus': true,
    'ignoreProtectedModeSettings': true
},
```
OR
```
multiCapabilities: [
     {
        'browserName': 'internet explorer',
         'requireWindowFocus': true,
         'ignoreProtectedModeSettings': true
      },
      {
        //  ...
      }
],
```

[Source](https://stackoverflow.com/a/32691070/1297812).
