### ISSUE TITLE
Feature idea: interactive element selector 'did you mean'

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#153]
If webdriver can't find an element, maybe we can return a smarter list of 'did you mean this thing'?

**Comment by chelseakomlo** [comment]
Is this feature still pending and of interest? We've been using protractor and it would be nice to help out.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this since we haven't seen any activity on it and [`browser.pause`](https://github.com/angular/protractor/blob/master/docs/debugging.md#pausing-to-debug) is a decent solve for this when trying to figure out the best locator selector for tests.

Please re-open if if this is something we still want on the roadmap :smile:
