### ISSUE TITLE
[docs] allowAnimations link goes to wrong source file

### ISSUE THREAD

**Issue by mitchhentges** [angular/protractor#1659]
**To reproduce:**
1. See the [docs](http://angular.github.io/protractor/#/api?view=ElementFinder.prototype.allowAnimations).
2. Click "View code"
3. You go to `protractor.js` instead of `element.js`.

Once of these days I'm going to start doing PRs. Today is not that day.

**Comment by sjelin** [comment]
I cannot reproduce the problem of it linking to `protractor.js` instead of `element.js`.  I assume that this is just because the docs hadn't been re-generated in a while.

I'm not sure how I feel about the fix Julie is proposing though.  What if someone generates a new set of website docs, then does a `git commit --amend`, changing the hash?  When they push everything to github, the docs they've generated will **all** link to a 404.  The current approach has its problems to be sure, but it's never fails so dramatically.  What I would rather see is some sort of fully-automated process for updating the docs so that they just never get out of sync with the code

**Comment by juliemr** [comment]
That'd be great - or could we link to a version tag like 1.6.0?

**Comment by sjelin** [comment]
How would you do that?

**Comment by juliemr** [comment]
Looks like github is smart enough to use tag names, e.g.

https://github.com/angular/protractor/blob/1.4.0/lib/protractor.js
