### ISSUE TITLE
How to wait until page freezes in protractor?

### ISSUE THREAD

**Issue by iljapavlovs** [angular/protractor#1678]
We have got following logic on frontend - so when new page is loaded, screen is auto scrolling to specific section and I have a script which clicks on the specific element at that time. Hence, while this movement is occurring following error is appearing due to the fact that selenium is clicking on wrong element:
"Element is not clickable at point (x, y). Other element would receive the click..." 

I have added plain sleep, but this solution is not a good one. So does any one know how to wait until page freezes - when auto scrolling is finished?

**Comment by hankduan** [comment]
It depends on how you added the scroll; if your scroll action/library contains `setTimeout`, it will not work, otherwise it should work out of the box if `ignoreSynchronization` isn't set.

That being said, using a click/coordinates to identify an element is never a good idea, as it requires you to change the coordinate every time you make a small change to your app.

**Comment by juliemr** [comment]
I think this is obsolete.
