### ISSUE TITLE
Asserting state on current page after button click, but before next page loads

### ISSUE THREAD

**Issue by ljwagerfield** [angular/protractor#1752]
We have a submission button that becomes disabled while waiting for the operation to complete. In this case, the operation completes by navigating to the `/dashboard` page.

We would like to assert this 'disabled while pending' behaviour in our end-to-end Protractor tests:
```
it('should disable button after submission', function(){
  page.usernameTextBox.sendKeys(username);
  page.passwordTextBox.sendKeys('password1');
  page.signInButton.click();
  expect(page.signInButton.getAttribute('disabled')).toContain('true');
  expect(browser.getCurrentUrl()).toContain('/dashboard');
});
```
The assertion on the `disabled` attribute fails as the next page has already loaded. This is because Protractor waits for the operation to complete before running the assertion - i.e. its not being missed due to a race condition - Protractor actually has it synchronised so that the assertion will not be run until the operation completes.

How can we test the above behaviour?

**Comment by juliemr** [comment]
You can use `browser.ignoreSynchronization = true`, but I would caution against testing this kind of timing-specific thing in end to end tests, because sometimes the test will be running slowly and even without synchronization your test will fail. 

Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
