### ISSUE TITLE
testing sockets

### ISSUE THREAD

**Issue by djindjic** [angular/protractor#1765]
I cant find any resource about testing app connected to backend via sockets. Specifically, I'm trying to test angular/angularfire app with firebase and didn't find any batter solution except `protractor.promise.delayed(xxx)`. Is it regular way to do that? Angularfire team also use this style testing in their [specs](https://github.com/firebase/angularfire/blob/master/tests/protractor/todo/todo.spec.js#L15), but just want to check here does it recommended solution for web sockets testing in general?

**Comment by juliemr** [comment]
It really depends on what you're trying to test or wait for. If there's some indication in your application that an event has happened (e.g. a spinner), then you can wait on the presence or absence of that element using `browser.wait`. If what you want to test is really that something happens after a specific timeout, then `promise.delayed` seems like a good solution.

Since this is not an bug or feature request for Protractor I'm going to close the issue. Please open up a question on Stack Overflow if you'd like to get more opinions.
