### ISSUE TITLE
Drag and Drop testing for slider , with margin defined in percent 

### ISSUE THREAD

**Issue by snehacharkha** [angular/protractor#1800]
Hi ,

Very new to protractor , and i need to do drag and drop testing for a slider bar.

i believe,
ptor.actions().dragAndDrop(slider.find(), {x:100, y:0}).perform() should do the work .

But can some one please tell me where to look for value of x and y ;

Here's the code snippet
![screen shot 2015-02-09 at 5 41 34 pm](https://cloud.githubusercontent.com/assets/6864700/6135434/6570d6f8-b11d-11e4-8d1a-1a3a7ac468c9.png)

**Comment by snehacharkha** [comment]
@juliemr DO u have a suggestion to this

**Comment by sjelin** [comment]
`x` and `y` are coordinates on the screen.  I cannot possibly tell the values without actually looking at the page.  You can, instead of specifying a location, specify a target element though if you're trying to drag one thing to something else.  However, please note that the drag and drop API is buggy, and the bug is out of our control (see https://github.com/angular/protractor/issues/1525)
