### ISSUE TITLE
webdriver manager will not properly update old versions of chromedriver

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#1813]
Testing update to chromedriver 2.14, and `webdriver-manager update` didn't download properly.

**Comment by juliemr** [comment]
This will be fixed in the next release.

In the meantime, a workaround is to remove the old `chromedriver` file (installed to `node_modules/protractor/selenium/chromedriver`) and then run `webdriver-manager update` or to manually download chromedriver from https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by juliemr** [comment]
Done with 1.7.0 release.

**Comment by badrisugavanam** [comment]
i encountered this issue,spend some time to find the root cause and install the new package of protractor which came @juliemr fix for this. working now.

but i could not get to chromedriver logs in verbose from protractor config which would have helped to find the root cause of the issue faster.

is there is a example of protractor config to show verbose logs of chromedriver
