### ISSUE TITLE
Using '%' in by.id selector doesn't work

### ISSUE THREAD

**Issue by Chexpir** [angular/protractor#1832]
I haven't tested which is the exact cases is failing but:
I was using protractor 1.2
element(by.id(''text%text2')) was working
now in protractor 1.4 it doesn't work

I have changed the code to use a colon instead of % and it works,
element(by.id(''text:text2')) was working

I have also found another problem. It doesn't allow to search id's containing spaces. but HTML spec doesn't allow spaces, so that's not an error

**Comment by juliemr** [comment]
It looks like `%` is invalid in HTML4: http://stackoverflow.com/questions/70579/what-are-valid-values-for-the-id-attribute-in-html

Is there a pressing need to include % in ID names?

For the record, this is almost certainly due to some sort of encoding between node, the selenium server, and the browser.

**Comment by juliemr** [comment]
Haven't heard any updates. Closing.

**Comment by Chexpir** [comment]
I agree it is not urgent. I solved it using a workaround, changing the id. But nowadays we use HTML5, and it would be useful to conform to it.
