### ISSUE TITLE
browser.pause() stopped working in new versions

### ISSUE THREAD

**Issue by giladbeeri** [angular/protractor#1914]
I was trying to use browser.pause(). During the process of developing the test, it stopped working.

When the test finishes, I get several errors (printed to console, not test errors) of the same type:
`Failed to open socket on port 5858, waiting 1000 ms before retrying`

I found out that the problem is that there's another zombie node process which uses port 5858. 

I suggest that if `browser.pause()` fails to connect to the necessary port, the test will fail with a relevant message (right now the test continues and an error message is printed in the end, not a test error but something internal). A developer will use `browser.pause()` when developing the test (and not when executing it in the long-term), so it's reasonable to "fail fast" at that point.

**Comment by hankduan** [comment]
When the debugger is unable to find a port, it should be printing to console.log immediately (it doesn't make sense to be a test error, since it has nothing to do with the test itself). 

That being said, making it fail immediately is a good suggestion and I will have a PR out for that. Meanwhile, browser.pause take a single optional parameter, the port number. You can use a different port if 5858 is in use.

**Comment by hankduan** [comment]
Alright, this PR should do what you want: https://github.com/angular/protractor/pull/1898

**Comment by giladbeeri** [comment]
Thank you @hankduan, and yes, what you wrote is what I meant :) (stopping the test but with a system error and not a test error).
