### ISSUE TITLE
Delay in selenium firefox driver

### ISSUE THREAD

**Issue by smahalingam** [angular/protractor#1998]
Hi,
I got latest version of protractor - 2.0.0 and when i try "browser.getCurrentUrl()" it takes few seconds to show the result. 

Is it known issue Or am i doing some thing wrong here ?

Thanks in Advance

**Comment by smahalingam** [comment]
Firefox version - 36.0.4

**Comment by juliemr** [comment]
Works super quickly for me (less than one second). How do you know that the delay is caused by browser.getCurrentUrl()? Is it slow for every page, or just one particular URL?

**Comment by Tekki** [comment]
Maybe it's related to this issue: I noticed that since 2.0 the Firefox tests on Ubuntu 12.04 got very slow, between 2.5 or 3 times slower than the Chrome tests (with and without directConnect). On Windows they run more or less at the same speed.

**Comment by juliemr** [comment]
I haven't heard of any actionable issues, so I'm going to close this for now. If you have some reproducible case that takes a long time, please open up a new issue. Note that any changes are probably due to the upgrade in the version of the selenium server and are not under Protractor's direct control.
