### ISSUE TITLE
Local storage vanishes after test run

### ISSUE THREAD

**Issue by hasanyousuf** [angular/protractor#2027]
I am running protractor using grunt-protractor-runner node package and Chrome browser.
Project configurations:
node: v0.12.1
npm: 2.5.1
OS: windows 2008 R2 64 bit
protrator 2.0
jasmine 1.3

Our application heavily rely on local storage, cookies and indexdb (pouchdb). It is observed that during the test run localstorage, cookies and indexdb get populated and as soon as test run ends. Localstorage, cookies and indexdb get deleted. 

One thought is that protractor starts browser in new thread and as soon as test is finished, it removes all the information related to that thread.

Is there a way, to keep the localstorage, cookies information and indexdb even test is over?

I tried to use chrome flags '--no-sandbox', '--test-type=browser', '--disk-cache-size=10000',  '--v8-cache-options=on' but it did't work.

Any help will be appreciated.

**Comment by juliemr** [comment]
Browsers are started and controlled using WebDriver, which gets a clean session for each test run. So you are correct. This is generally a desirable feature, since it allows tests to be hermetic. The advice is generally to do set up you need for each test run in a `beforeEach` or `onPrepare` block.

Firefox has a way to restore sessions using profiles, but I do not know of a way to do this for Chrome.
