### ISSUE TITLE
browser.wait for non-angular apps in v2.0.0

### ISSUE THREAD

**Issue by djindjic** [angular/protractor#2086]
I have used browser.wait in my non-angular applications tests before and everything was fine, but today after upgrading my protractor to version 2.0.0 it seem like there is some braking change, but I cant find it [here](https://github.com/angular/protractor/releases/tag/2.0.0).

This code:
```js
browser.get('/index.html');
browser.wait(function() {
    return browser.isElementPresent(by.css('someCssClass'));
});

expect(1).toEqual(1);
```
makes this error:
```bash
 Message:
     Error: Wait timed out after 39ms
   Stacktrace:
     Error: Wait timed out after 39ms
```

so 39ms? isn't it to short? :)

**Comment by drslump** [comment]
I think it's a change on the webdriver library, the 39ms is probably just the time it takes to send the actions to the browser. You need to provide a waiting timeout value otherwise once the function is resolved it'll compare the time expend to the default value of `0` so it will time out.

```js
browser.wait(function () {
  return browser.isElementPresent(by.css('someCssClass'));
}, 1000);
```

By the way, perhaps you should adapt to use http://angular.github.io/protractor/#/api?view=ExpectedConditions for these use case.

**Comment by juliemr** [comment]
Yes, this is a change with webdriver. The [changelog](https://github.com/angular/protractor/blob/master/CHANGELOG.md) documents this breaking change.
