### ISSUE TITLE
Hangs when on VPN via Cisco AnyConnect Secure Mobility Client

### ISSUE THREAD

**Issue by tempoc** [angular/protractor#2122]
When pointing it to localhost or 0.0.0.0 I get:
```
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
```
It dies on a timeout.
```
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: Timed out waiting for the WebDriver server at http://192.168.1.104:56508/wd/hub
    at Error (native)
```
Thinking it doesn't know how to properly resolve localhost IP. It's looking for 192.168.1.104 which is my local WiFi IP at the time I ran it, but I doubt that's my IP on the VPN.

**Comment by hankduan** [comment]
Protractor is merely calling out to webdriver with whatever url you pass, and doesn't do any resolution on its own (https://github.com/angular/protractor/blob/master/lib/driverProviders/driverProvider.js#L36)

If this is a problem it is likely going to have the same problem on pure webdriverjs. If this is a huge deal for you, you should try to open a ticket with webdriverjs. Otherwise consider just using the correct ip directly.
