### ISSUE TITLE
For/While loop struggles with async calls

### ISSUE THREAD

**Issue by gpmishra** [angular/protractor#2150]
I am trying to check element on regular interval and click only if it is present. Some times this element appears in 2-3 minutes. If it is not present, i want to wait for few seconds and then refresh page

Here is what i tried:
```
for(var i = 1; i < 60; i++){
    element(that.proposalByOrderPath(num)).isPresent().then(function(result){
        if(result){
            console.log(i);
            return element(that.proposalByOrderPath(num)).click();
        }
        else{
            browser.sleep(15000);
            browser.refresh();
       }
    });
}
```
As an output, it prints **60** twice. It clicks on the element once but tries to look again for the element and throws "element not visible" error.

**Comment by sjelin** [comment]
`isPresent` just checks that an element is on the page.  It looks like in your example the element is present but not visible.  You'll probably want to check out [`ExpectedConditions`](http://angular.github.io/protractor/#/api?view=ExpectedConditions) and [`visibilityOf`](http://angular.github.io/protractor/#/api?view=ExpectedConditions.prototype.visibilityOf).

You're getting `60` twice because by the time `console.log(i)` gets called the for loop has run all the way through.  This is a common weird case of using callbacks inside of loops.

**Comment by gpmishra** [comment]
@sjelin element is present and visible, because it clicked on the element and again looking for it and at last gives not found error.

**Comment by sjelin** [comment]
I don't know the details of why the element isn't clickable after the first two times.  I'd have to be actually debugging your app.

As for loops/callbacks, I'd check out the explanation here: http://www.apaxsoftware.com/2012/05/common-javascript-mistakes-loops-and-callbacks/

Also, please ask questions like this on StackOverflow.  GitHub issues are more for bug reports & feature requests and the like.
