### ISSUE TITLE
test cases not working  proper

### ISSUE THREAD

**Issue by satyavanu** [angular/protractor#2249]
I am seeing some weird issues using  Protractor . when I ran my tests  some times I see all my assersertions  100% , If same  I run  with some delay  I am getting error's like angualr reloading  exceeded . This is weird  behaviour

**Comment by sjelin** [comment]
As mentioned in [`timeouts.md`](https://github.com/angular/protractor/blob/6ebc4c3f8b557a56e53e0a1622d1b44b59f5bc04/docs/timeouts.md#timeouts-from-protractor), this is because your delays have caused Angular to take too long to show up on the page, and thus caused Protractor to think that Angular might not exist on the page

**Comment by satyavanu** [comment]
Thanks for the reply . I did used this  however  while executing the same tests at times I get 100% and sometimes  not  , due to  angular exceeding  / angular app bootstrapped already  :( . 

I  am using to require.js  to load angualr.js , but timeouts  are not really  helping me  for consistent behavior

**Comment by sjelin** [comment]
Race conditions like that are often inconsistent.
