### ISSUE TITLE
Chrome cannot focus on div for sending keys

### ISSUE THREAD

**Issue by bcherny** [angular/protractor#2258]
I have a `<div>` that I am trying to send a backspace key to.

```js
// crashes Chrome
$('#myDiv').sendKeys(protractor.Key.BACK_SPACE)

// crashes Chrome
$('#myDiv').click().sendKeys(protractor.Key.BACK_SPACE)

// works!
browser.actions().sendKeys(protractor.Key.BACK_SPACE).perform()
```

Related to:

- https://github.com/angular/protractor/issues/1622
- https://github.com/angular/protractor/issues/562
- http://stackoverflow.com/questions/21991003/cannot-focus-web-element-to-send-keys

**Comment by sjelin** [comment]
Not sure what's wrong with the first one.  What error message are you getting?

`$('#myDiv').click().sendKeys(protractor.Key.BACK_SPACE)` is wrong.  You can't chain those commands together like that.

**Comment by juliemr** [comment]
@sjelin You should be able to chain commands, the commands seem fine.

When executing the first and second commands, the error is `cannot focus element`. The third command works because it isn't sending the keypress to a specific element, just to the browser.

This looks like a recurring issue with chromedriver. See code.google.com/p/chromedriver/issues/detail?id=870, and https://code.google.com/p/chromedriver/issues/detail?id=35, and https://code.google.com/p/chromedriver/issues/detail?id=999

**Comment by juliemr** [comment]
External bugs are closed, so I'm going to close this issue as well - please open up an issue with ChromeDriver if you are still seeing this with the latest version.
