### ISSUE TITLE
How to fix errors like: " 'element' is not defined.  or  'by' is not defined or $' is not defined.

### ISSUE THREAD

**Issue by nserebry** [angular/protractor#2267]
I'm getting this error even with: 
```var username = element(by.id('username'));```

test/e2e/Page.spec.js
  ```line 15   col 22  'element' is not defined.
  line 15   col 30  'by' is not defined.```


can someone please help resolve this problem.

**Comment by sjelin** [comment]
Where is this code being executed?

**Comment by juliemr** [comment]
Maybe you are trying to run `protractor myTestFile.js` instead of `protractor myConfFile.js`? Or maybe you are running your files with plain old node instead of using Protractor's command line tool?

In any case, closing as not a general issue.  Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
