### ISSUE TITLE
Should browser.navigate() use waitForAngular() before it fires?

### ISSUE THREAD

**Issue by martin770** [angular/protractor#2306]
We have a search engine type of application, and in our test we want to perform a search then go back to the previous page and verify some stuff:

    element(searchButton).click();
    browser.navigate.back();
    expect(searchButton.isPresent()).toBe(true);

Sometimes the clicking of the search button takes a bit of time to load the results page, but the browser is more than happy to fire off the back button immediately, in which case the expectation fails.

My workaround seems to be:

    element(searchButton).click();
    browser.waitForAngular(); // make sure we get the results page loaded before clicking Back
    browser.navigate.back();
    expect(searchButton.isPresent()).toBe(true);

Or I suppose I could:

    element(searchButton).click();
    expect(resultsPage.isPresent()).toBe(true); // unnecessary verification to force page load
    browser.navigate.back();
    expect(searchButton.isPresent()).toBe(true);

Please correct me if I'm wrong but my understanding is that any time protractor is performing an action on an element, it will wait for angular before performing that action, but not wait after the action. Because the browser.navigate() things are not actions on an element, I don't think it knows to wait before performing those actions. If that is the case, could the browser.navigate() things be patched to automatically waitForAngular() ?

Of course, the examples above are pseudo-code, so if the message is not clear enough I can try to provide other examples. And yes, the pages I am referring to are angular ;) Thanks!

**Comment by sjelin** [comment]
Your understanding is correct.  `browser.navigate()` is just there to create a navigation object, so it would be a little weird to include a `waitForAngular()` call there.  The functions on the navigation object (e.g. `back`) are provided by webdriver, which is why they don't call `waitForAngular()`.  I suppose we *could* add a call to `waitForAngular()` in `browser.navigate()`, but that might be weird if someone does something like the following:

```js
var nav = browser.navigate(); //waitForAngular() called here
element(searchButton).click();
nav.back(); //No waitForAngular() here
```

We could wrap all the WebDriver navigation functions, which would probably be the better option

**Comment by martin770** [comment]
Thanks for the explanation. I do see a wrapped version for refresh in the source code. For now, my helper functions seem to get the job done.

    navigateBack = function() {
      browser.waitForAngular();
      browser.navigate().back();
    }
