### ISSUE TITLE
Expose configuration of Jasmine plugins

### ISSUE THREAD

**Issue by ctapobep** [angular/protractor#2340]
I'm writing a reporter for protractor+jasmine. Because Protractor doesn't provide all the necessary data in postTest(), I'd like to be able to add Jasmine plugins to get data directly from there. Currently what I see in `frameworks/jasmine2.js`:
```
  var reporter = new RunnerReporter(runner);
  jasmine.getEnv().addReporter(reporter);
```
Would be useful to configure jasmine reporters so that Protractor invokes `jasmine.getEnv().addReporter(configuredReporter)`.

### Back story 
The problem is Protractor doesn't provide all the necessary info like errors, it truncates Jasmine's props. Here is `frameworks/jasmine2.js`:
```
RunnerReporter.prototype.specDone = function(result) {
  var specInfo = {
    name: result.description,
    category: result.fullName.slice(0, -result.description.length).trim()
  };
  if (result.status == 'passed') {
    this.emitter.emit('testPass', specInfo);
  }
```
And also Protractor exposes a very limited API (only `postTest()`, but where is `preTest()`?). My only assumption - because different frameworks provide different level of details, the lowest common denominator was chosen.

**Comment by sjelin** [comment]
Not totally sure what you're asking.  You can do `jasmine.getEnv().addReporter(reporter);` inside your spec file without any difficulty.  

#### Re: Backstory

It's not *exactly* that the lost common denominator was chosen - more like the Plugin API is still relatively new and we've been adding features one at a time as people have asked for them.  But yes, the fact that Protractor supports many frameworks does hold us back.

**Comment by ctapobep** [comment]
Well, spec is probably not the place I was looking for. Since I'm creating a reporter the only place I'd like it to appear is `protractor-conf.json`. Otherwise users will be forced to add my reporter in every spec. So what I was imagining is:
- _Option1._ In `protractor-conf.json` I can specify not only the plugins for Protractor, but also the framework plugins. 
- _Option2._ In plugins we could have a reference to `jasmine` object (and other framework objects) and thus we could configure it in whatever way we want (including adding reporters).
- _Option3._ Protractor can provide more information in its Plugins API. Including more listening methods (beforeTest, beforeSuite, afterSuite) and more information in the test result objects (e.g. reference to the original jasmine result).

_Option1_ is the best I think because we could leverage existing reporting tools that are provided with the frameworks. _Option2_ is worse because for every framework reporter we'd need to write Protractor adaptor which simply triggers the framework reporter. _Option3_ is the worst I guess since we'd need to write brand new reporters for Protractor.

**Comment by sjelin** [comment]
Well, if you used an [inline plugin](https://github.com/angular/protractor/blob/master/docs/plugins.md#using-plugins) I don't think option 2 would be so bad, but sure - I see the problem.

**Comment by ctapobep** [comment]
So what option do you think is worth implementing? I could try to send a PR if we agree on the approach (need that reporter badly :)).

**Comment by sjelin** [comment]
Ok, so here are my thoughts:

- *Option 1*: I'm not super interested in making it more complicated to write frameworks.  I think ideally we'd spin the frameworks out into separate repos (we're already planning on doing this cucumber at some point), and I'd like people to feel comfortable to write their own.  This would be a weird ask for framework writers, because there's very little similarity between reporters in different frameworks (do they even all have a concept of a reporter?).  Also, I'm not super interested in introducing a bunch of different ways to do the same thing (e.g. get information about tests that just ran).
- *Option 2*: Not a huge fan of this option either because I'm not sure how to implement it, it seems pretty silly (you use one type of plugin to inject another type of plugin?), and it ties plugins to specific frameworks.
- *Option 3*: My biggest problem here is the lowest-common-denominator problem.  I don't want to start saying "frameworks must also pass `XYZ` information to plugins" because `XYZ` might not be available in each framework.

I think the best option is a variant on 3: Allow frameworks to pass one extra `allInfo` object to plugins.  This would contain everything the framework knows about the test that just ran (not formatted in any specific way).  In the case of jasmine, that would mean putting the entire `result` object into [`specInfo.otherInfo`](https://github.com/angular/protractor/blob/master/lib/frameworks/jasmine2.js#L20).  This avoids the lowest-common-denominator problem because each framework merely passes whatever information it has, and it allow allows plugin writers to access framework-specific information if they so desire.

@hankduan @juliemr Any thoughts?

**Comment by hankduan** [comment]
Maybe I'm misunderstanding the discussion, but why can't you load the framework in `onPrepare` within a conf.js file (is that what you mean by protractor-conf.json)?

Here's the doc on onPrepare: https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L200

Specifically:
```javascript
    // At this point, global variable 'protractor' object will be set up, and
    // globals from the test framework will be available. For example, if you
    // are using Jasmine, you can add a reporter with:
    //     jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter(
    //         'outputdir/', true, true));
```

It makes little sense for people to write a reporter for *all* frameworks as that adds a ton of complexity and restrictions.

**Comment by ctapobep** [comment]
Wow, that may solve all the problems :) Will try it out soon.

**Comment by hankduan** [comment]
Cool, please let us know if this satisfies your needs.

**Comment by ctapobep** [comment]
Works like a charm, many thanks!
