### ISSUE TITLE
How to access the widgets within the cells of a row in a grid?

### ISSUE THREAD

**Issue by PrashantZeus** [angular/protractor#2373]
Hi All,
            I've an issue with accessing the widgets or controls within the cell of a row of a complex grid in my application. Even if I get access to the row object, I'm not able to obtain the cell or get access to the checkbox within the cell.
           In the below case as seen in the image, I want to select the checkbox in the last column of the first row.

![query](https://cloud.githubusercontent.com/assets/13470944/8855893/3d4a82b2-3185-11e5-9b0b-1aeffc75b0b4.png)

I've already tried various different combinations to help with my issue few of them i've mentioned below:

element.all(by.model('ng-yyyy')).then(function(rows) {
     // rows => gives me an array of objects corresponding to the rows in the grid
    // any operation that i try to do henceforth to get to the last column cell of each row ends in a failure
   rows[0].element(by.model("cell")).anyoperation // doesn't work
});

I've even tried with the map and filter.

Any suggestions on this would be really helpful.
Thanks in advance.

**Comment by sjelin** [comment]
Hi, sorry for the extremely slow response.  Then object you're getting from inside a `then` block is a raw webdriver object, which is why it isn't working.  You'd want to chain commands together like this:

`element.all(...).element(...)`

Regardless, as per our [`CONTRIBUTING.md`](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md), please ask this kind of question on StackOverflow
