### ISSUE TITLE
Not able to set chrome user agent from spec

### ISSUE THREAD

**Issue by gpmishra** [angular/protractor#2387]
I have a test where i need to launch 2 browsers, 1 with android user-agent and other with windows-mobile user agent. I have set android user agent in conf file. For windows mobile, i am trying following:

driver1 = new protractor.Builder()
            .usingServer('http://localhost:4444/wd/hub')
            .withCapabilities(protractor.Capabilities.chrome()).setChromeOptions(new chrome.Options().addArguments("--user-agent=" + userAgent)).build();

On run, it says "Failed: chrome is not defined"

**Comment by gpmishra** [comment]
I am still looking forward for any suggestion or help.

**Comment by sjelin** [comment]
It looks like `chrome` is not defined in the snippet `new chrome.Options().addArguments("--user-agent=" + userAgent)`.  Maybe you forgot to import it?  Also, it looks like you're trying to user the underlying webdriver APIs directly, rather than doing this kind of thing through a [Protractor Config File](https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L147).
