### ISSUE TITLE
IE11: A Jasmine Spec has timed out: Resetting the webdriver control flow  error (Jasmine2)

### ISSUE THREAD

**Issue by mfsiabhishek** [angular/protractor#2389]
Its giving Spec timeout error for 11th spec and test gets stuck there.
This is only an IE11 issue with Jsmine2 as framework, work fine for Jasmine 1.

Works fine on Chrome.

  jasmineNodeOpts: {
        showColors: true,
        includeStackTrace: true,
        isVerbose: true,
        defaultTimeoutInterval: 1800000
    },

**Comment by JayHuang** [comment]
+1

**Comment by icvitkovac** [comment]
You can bypass the issue with this settings:

http://stackoverflow.com/a/29901371/1654410

**Comment by sjelin** [comment]
As per our [`CONTRIBUTING.md`](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md), please ask this question on Stack Overflow.  Also, when you do that, please provide more details about your failing test.

**Comment by makwanaparth94** [comment]
Getting an error while running the protractor test on IE.
Error: A Jasmine spec timed out. Resetting the WebDriver Control Flow.
Request you to give me steps to run it on IE as well as on Firefox

**Comment by abhishek153** [comment]
This issue is still there. Kindly provide a resolution to this issue. I am getting this issue in IE11 and latest selenium driver and protractor version 5.3.1 but still the issue is there.

Even i used browser.driver.get() instead of browser.get() in my tests which is mentioned in some of the issue links for this time out issue but that is also not working.

Can you please let me know if IE11 supports running  protractor using selenium??
