### ISSUE TITLE
Issue while using by.id locator

### ISSUE THREAD

**Issue by Dharam625** [angular/protractor#2459]
i have an input element for userid. I am trying to input a user id there using sendkeys as shown below.

element(by.id('userId')).sendKeys(Id); which is not working. it says input is not focused. Also it does not work with by.model.

It works well if i use - element(by.css("input[name=userId]")).sendKeys("wrongUserId");

My input element is created using a directive and it looks like below.  

`<div class="eam-required ea-input-with-label ng-pristine ng-valid ng-isolate-scope" ng-class="{ 'eam-selected': hasFocus }" ng-form="eaForm" name="userId" type="text" id="userId" placeholder="Käyttäjätunnus" label="Käyttäjätunnus" ng-model="retrievePasswordCtrl.userId" style="">
<label ng-class="{ 'visible': model.length > 0 }" class="ng-binding">Käyttäjätunnus<span style="visibility: hidden">fix autofill</span></label>
    <div class="input-container">
        <input class="ea-input ng-pristine ng-valid ng-touched" type="text" placeholder="Käyttäjätunnus" name="userId" ng-model="model" ng-focus="hasFocus=true" autocapitalize="off" autocorrect="off" ng-blur="hasFocus=false" style="">
    </div>
    
</div>`

If i use a simple input element then by.id and by.model works fine.

Any help is appreciated....

**Comment by kisanme** [comment]
Hopefully this is because your elements loaded by the directive are not rendered when the test is being executed. Or it is not inside the scope of the window (browser window).

If its the case 1, try executing your command after a 
```
browser.wait(4000);
element(by.css("input[name=userId]")).sendKeys("wrongUserId");
```
which will make the browser to wait for 4 seconds before executing the next line.

If it is case 2, try maximizing your window before executing the test.
```
browser.driver.manage().window().maximize();
element(by.css("input[name=userId]")).sendKeys("wrongUserId");
```

Hope this goes right.

**Comment by Dharam625** [comment]
This is already working with element(by.css("input[name=userId]")).sendKeys("wrongUserId"); without using any wait or browser.driver.manage().window().maximize();

Problem is that same does not work if i use by.id("iuserId") instead of by.css("input[name=userId]").

Any clue why it is not working with by.id ?

**Comment by kisanme** [comment]
Okay i think i found it why. In your code (html) you have declared the id to the division. Which cannot accept any input (which is sent through sendKeys("....")). And why it works for 
```
element(by.css("input[name=userId]")).sendKeys("wrongUserId");
````
is because you have given the name for the `input` as __userId__.

Add the following code into your division. And remove the `id="userId"` from the division.
```
<input class="ea-input ng-pristine ng-valid ng-touched" type="text" placeholder="Käyttäjätunnus" name="userId" ng-model="model" ng-focus="hasFocus=true" autocapitalize="off" autocorrect="off" ng-blur="hasFocus=false" style="" id="userId">
```

This will solve your issue

**Comment by juliemr** [comment]
Thanks for investigation and answering @kisanme! closing as solved.

**Comment by Dharam625** [comment]
Thankyou so much @kisanme.You are right. We have changed our directive now. Its working fine.
