### ISSUE TITLE
opt out from patched mocha/jasmine (async tests by default)

### ISSUE THREAD

**Issue by dmitriiabramov** [angular/protractor#2570]
i found the issue https://github.com/angular/protractor/issues/646

and what i got is that webdriver patches mocha in runtime to assume that all the functions are asynchronous and require either calling `done` or returning a promise.

is there a way to opt out from mocha/jasmine patching?
for various reasons (mixing native promise with webdriver.promise and stuff like that, global webdriver.promise error handler, no control over the page objects, etc...) i'm trying to avoid relying on control flow and use ES7 async functions to write tests.

so the test that looks like
```js
it('111', async function() {
  let message = await pageObject.getMessage();
  expect(message).to.equal('123');
});
```

will fail with:
```
Error: Wait timed out after 15078ms
```
unless you call `done` or return a promise or something like that

is there a way to *unpatch* mocha and make all the test synchronous by default?

**Comment by sjelin** [comment]
You don't have to call `done` unless you make it a parameter to the function.  See https://github.com/angular/protractor/blob/master/spec/basic/lib_spec.js#L10 vs https://github.com/angular/protractor/blob/6ebc4c3f8b557a56e53e0a1622d1b44b59f5bc04/spec/unit/runner_test.js#L15

Does this solve your problem?

**Comment by dmitriiabramov** [comment]
@sjelin yeah. that's how mocha works.
but using protractor, my example test will never finish unless i explicitly pass `done` and call it at the end.

**Comment by sjelin** [comment]
In Protractor, be it jasmine or mocha, you only need to explicitly call `done` if you include it as a parameter.  See the examples from the protractor tests.

**Comment by juliemr** [comment]
To answer your original question - you could create your own custom framework. see https://github.com/angular/protractor/tree/master/lib/frameworks#custom-frameworks, and take a look at https://github.com/angular/protractor/blob/master/lib/frameworks/mocha.js for our mocha implementation. You would pretty much just need to copy that without the adapter stuff.

For ES7 - that's tracked at https://github.com/angular/protractor/issues/1214. It's on our todo list for soon!

I'm going to go ahead and close this since I think you've got enough to go on and it's not a general bug. Thanks!
