### ISSUE TITLE
Add ElementFinder's methods to prototype

### ISSUE THREAD

**Issue by stalniy** [angular/protractor#2574]
Instead of adding methods to each instance you can add them only once to prototype. That will reduce memory usage and will speed up ElementFinder creation. I'm talking about this part:
```js
  var self = this;
  WEB_ELEMENT_FUNCTIONS.forEach(function(fnName) {
    self[fnName] = function() {
      var args = arguments;
      var actionFn = function(webElem) {
        return webElem[fnName].apply(webElem, args);
      };
      return self.applyAction_(actionFn);
    };
  });
```
Similar code inside `ElementFinder` class

**Comment by juliemr** [comment]
Given the latency involved in WebDriver commands, the speedup from the creation of an ElementFinder object wouldn't be noticeable, especially since it isn't a really hot path in the code. I don't think we should optimize this unless it's actually proven to cause issues.

Thanks for your attention to detail though! And if someone wanted to actually go ahead and make a clean, passing PR with these changes, I probably wouldn't turn it down.

**Comment by stalniy** [comment]
@juliemr  You are right but anyway that's what is heavily used inside tests. For example for 1000 elementFinders it's almost 8 times works faster

**Comment by awarecan** [comment]
+1

I am working on one project, which requires log all actions made in browser. I am planning decorate ElementArrayFinder.click() to export my custom log. However it failed because click() is defined at element object but not prototype level.

PR #2575
