### ISSUE TITLE
Could someone explain condition to shutdown selenium programmatically

### ISSUE THREAD

**Issue by Matrosskin** [angular/protractor#2627]
I found that in protractor module exists code for stopping selenium server programmatically: https://github.com/angular/protractor/blob/master/bin/webdriver-manager#L290
```
process.stdin.on('data', function(chunk) {
      console.log('Attempting to shut down selenium nicely');
      http.get('http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer');

    });
```

But I do not understand condition or event by which that code will be evaluated.

Could someone explain me for which purposes added that code?

**Comment by sjelin** [comment]
The code is evaluated on the selenium server, not within protractor's codebase.

**Comment by Matrosskin** [comment]
`process.stdin.on('data', function(chunk) {` - it is nodejs code... webdriver-manager file in protractor's repository... So why it is evaluated on the selenium server?

**Comment by Matrosskin** [comment]
I mean I am wondering how and when 'data' event for `process.stdin` is generated. Why does not it wait for receiving of the whole data and shuts down the selenium server by any chunk?

**Comment by sjelin** [comment]
The data event is generated by sending the process something via STDIN.  E.g., if you run `webdriver-manager start` in the console, when you're done you can type `Thank you kindly webdriver, but we're done here\n` and then webdriver will close down.  We don't think too hard about what the data is because we haven't implemented any other commands you can run via stdin.
