### ISSUE TITLE
Add support for constructing ElementFinder from Promise<ElementFinder>

### ISSUE THREAD

**Issue by caseyhoward** [angular/protractor#2730]
I'm not sure if there is already a solution , but I was wondering if there was a way to create an ElementFinder from a promise that returns an element. I have an element that I only know how to find after finding another element.

For example, I only know the id the first element before running the tests. I read an attribute to find the id of the other element, so I end up with a Promise<ElementFinder> instead of an ElementFinder.

```html
<div id="a" other-id="b"></div>
<div id="b"></div>
```

```javascript
var a = element(by.id('a'));
var b = a.getAttribute('other-id').then(function(otherId) {
  return element(by.id(otherId));
});
```

Is there any good way I can make b an actual ElementFinder? Is there a way to construct an ElementFinder from a Promise\<ElementFinder\> or Promise\<Element\>?

I don't want to have to work with a Promise throughout the rest of my tests when element finders are so much nicer to work with.

edit: just noticed "Promise\<ElementFinder\> or Promise\<Element\>" were showing up as "Promise or Promise"

**Comment by NickTomlin** [comment]
I think the way that you are currently handling it makes sense. I can't think of an elegant way to construct these "composite" element finders and so it feels like that should be kept out of protractor core.

Since this falls more under debugging/usage i'd suggest  [asking a question with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) on Stackoverflow or posting in the [Gitter Channel](https://gitter.im/angular/protractor) for additional help.

**Comment by sjelin** [comment]
I don't think there is currently any way to do this.  I think we could add a feature for this if there was enough interest though

**Comment by juliemr** [comment]
Agreed with @NickTomlin that this is probably out of scope for what we'd like to offer - "un-promising" things is not a preestablished pattern.
