### ISSUE TITLE
What is exactMatch in bindings ?

### ISSUE THREAD

**Issue by manoj9788** [angular/protractor#2740]
Hi

Just trying to understand the use of exactMatch in code
https://github.com/angular/protractor/blob/master/lib/clientsidescripts.js#L115 
What value is passed ?

**Comment by sjelin** [comment]
it's a boolean indicating if the `binding` parameter needs to to equal the element's binding or just a substring.  So, for instance, [`by.binding`](http://www.protractortest.org/#/api?view=ProtractorBy.prototype.binding) uses `exactMatch = false`, because it tolerates you just using a substring.  On the other hand, [`by.exactBinding`](http://www.protractortest.org/#/api?view=ProtractorBy.prototype.exactBinding) uses `exactMatch = true`.

Also, please ask this kind of question on [Gitter](https://gitter.im/angular/protractor), as per our [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md).

**Comment by manoj9788** [comment]
Thanks @sjelin  Next time will make sure its in gitter.
