### ISSUE TITLE
Protractor 3.0.0 requires node > v0.12.x?

### ISSUE THREAD

**Issue by scriby** [angular/protractor#2753]
I tried upgrading to protractor 3.0.0 locally, and it errors out trying to load the promise.js file that ships with selenium-webdriver. The exact error is:

```
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (.../node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
```

I checked through selenium-webdriver's changelog and 2.48.0 "is the last release that will support v0.12.x". Protractor references 2.48.2.

Given that an issue was fixed a couple weeks ago for node v0.10.x support, I find it surprising protractor would skip to node v4 without any mention of it. Was breaking compatibility with node <= 0.12 intentional, and is there any plan to bring back support?

**Comment by NickTomlin** [comment]
Yes, the change was intentional; there is a note that support is dropped in the protractor [CHANGELOG](https://github.com/angular/protractor/blob/master/CHANGELOG.md#breaking-changes).

> BREAKING CHANGE: 1) Users will no longer be able to use node versions <4. 2) There is significant changes to the control flow, and tests may need to be modified to be compliant with the new control flow

 While there is no official support for < 4 in protractor 3 you may have some luck using the `--harmony` flag if you are using node v0.12x (this is untested). From the webdriver [CHANGES](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v2480): 

> Node v0.12.x users must run with --harmony. This is the last release that will support v0.12.x

**Comment by scriby** [comment]
Thanks for the info, I must have overlooked that in the docs.

It might be a good idea to start making use of the "engines" setting in the package.json to document/enforce which versions of node are supported.
