### ISSUE TITLE
How to get all the attribute values of an element in protractor??

### ISSUE THREAD

**Issue by SangaviEruvaram** [angular/protractor#2776]
While using "element.getAttributes()" I am getting an error like "has no method getAttributes".

Is there any way to get all the attribute values of an emenet?

**Comment by Miro-H** [comment]
As far as I know there only exists ```.getAttribute() ``` which "Schedules a command to query for the value of the given attribute of the element" (according to the [protractor API](https://angular.github.io/protractor/#/api?view=webdriver.WebElement.prototype.getAttribute)). Which means you have to pass an attribute:
```javascript
element(by.id('whatever')).getAttribute('class');
```
To find all attributes of an element, maybe this [stackoverflow post](http://stackoverflow.com/questions/27694570/get-all-element-attributes-using-protractor) can be of help?

**Comment by NickTomlin** [comment]
Because of its usage/debugging nature, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
