### ISSUE TITLE
Running protractor on async mode skip my tests cases

### ISSUE THREAD

**Issue by houssemFat** [angular/protractor#2786]
Hi, 
I'm running protractor to test a web app that supports multilple locale (ar/en), i need to get the language key from `localStorage` by browser, and then get the json file of this language (in node context).
The issue is that protractor **didn't see any of my tests cases**. here's the code  snippet. 
```
/**
 * This variable must be included in all protractor e2e specs test
 */
var basePath = process.cwd();
var localStorage = require(basePath + '/test/helpers/localStorage');
var locale = require(basePath + '/test/helpers/locale');
/**
 * scenarios
 */
var testScenarios = function () {
    var cityLabel = element(by.linkText(locale.tr.call(locale, 'City')));
    it('test translation on label', function () {
        // check for labels
        cityLabel.getText().then(value, function () {
            expect(value).toEqual("City");
        });
    });
    /**
     *
     */

    it('test update company information', function () {
        update();
        expect(browser.getLocationAbsUrl()).toMatch("/login");
    });
};
/**
 *
 */
describe('Profile page', function () {
    // got to profile
    browser.get(ENV.Protractor.BASE_URL + '#/profile/');
    // get the current language key
    localStorage.getValue("NG_TRANSLATE_LANG_KEY").then(
        /**
         *  Init local dictionary object
         * @param value, current language key
         */
        function (value) {
            // 
            locale.init.call(locale, value);
        }
    )
        // I need that all tests will executed after locale initialisation
    .then(testScenarios);
});
```

**Comment by sjelin** [comment]
This sort of debugging/support question is much better suited for [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) (see our [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md)).  But I think the issue is that jasmine is having difficulty parsing your spec file because you only reach the `it` command asynchronously
