### ISSUE TITLE
Still get throw e syntax error on nodejs 4 

### ISSUE THREAD

**Issue by Leo-G** [angular/protractor#2809]
I m using travis-ci which uses ubuntu 12.04, i am able to install protractor 3.0.0 and nodejs 4 successfully but i still get the the syntax error not sure why

complete logs at https://s3.amazonaws.com/archive.travis-ci.org/jobs/98864715/log.txt

protractor install logs at https://gist.github.com/Leo-G/efdfe9476108a9d89594

**Comment by NickTomlin** [comment]
Can you share your travis.yml? Protractor CI uses travis and has recently run without any issues so this may be a configuration issue.

**Comment by Leo-G** [comment]
Thanks Nick, I started using Ubuntu 14.04 on travis and that sorted this issue, however now I have another issue, I think its related to the xvfb, not sure though

My travis file https://gist.github.com/Leo-G/73fb4c00330626a23709

The new error https://s3.amazonaws.com/archive.travis-ci.org/jobs/98878079/log.txt

**Comment by NickTomlin** [comment]
Hmm, it seems like there's some sort of race condition with selenium-server and your test cases. 

Since this is going to require some debugging, and is not an actual issue with Protractor, would you mind closing this issue and posting a question on [stackoverflow (with the 'protractor' tag)](http://stackoverflow.com/questions/ask?tags=protractor) orin the [Gitter Channel](https://gitter.im/angular/protractor)? I'd suggest including your protractor config as well as an isolated test if you can.

**Comment by Leo-G** [comment]
alright nps
