### ISSUE TITLE
Selenium crashing for a while, then working for a while

### ISSUE THREAD

**Issue by wtiger** [angular/protractor#2828]
When I try to run Protractor, sometimes it will work fine for long periods of time and other times, Selenium breaks on startup, sometimes for a dozen tries in a row. When it breaks, it gives the following error:

Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^

Error: Timed out waiting for the WebDriver server at http://10.0.2.15:60234/wd/hub
    at Error (native)
    at onResponse (/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:89:11)
    at /node_modules/protractor/node_modules/selenium-webdriver/http/util.js:44:21
    at /node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/http/http.js:140:5
    at ClientRequest.<anonymous> (/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:174:7)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

Protractor 3.0.0
Selenium 2.48.2
JDK: jdk-1.7.0_67

Switching between Firefox and PhantomJS to run tests, but this happens in both.

**Comment by NickTomlin** [comment]
Unfortunately this is a common issue with selenium based tests (which may or may not be exacerbated by your application setup).

Because of the nature of your problem, it is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


If you can iron things down to a reproducible bug please feel free to re-open / repost an issue. Thanks!
