### ISSUE TITLE
realtimeFailure no longer working

### ISSUE THREAD

**Issue by F1LT3R** [angular/protractor#2845]
Reporting real-time failures no longer seems to be supported now that the runner has been updated from [minijasminenode](https://github.com/juliemr/minijasminenode) to [jasmine-npm](https://github.com/jasmine/jasmine-npm).

Can you confirm?

With Protractor we used to be able to use realtimeFailure to see the errors output in real tim, is this no longer available?

``` javascript
jasmineNodeOpts: {
  realtimeFailure: true,
}
```

**Comment by juliemr** [comment]
Yup - looks like you've already found the relevant Jasmine issue: https://github.com/jasmine/jasmine/issues/414

I would prefer for this feature to be added to Jasmine, where it makes the most sense, rather than having a shim only for Protractor, so I'm going to list this as an external issue for now.

**Comment by juliemr** [comment]
I'm going to go ahead and close this since the external bug is filed and I don't think it's providing much value to keep track of it in our repo as well.
