### ISSUE TITLE
When running protractors tests, my url changes to https in browser

### ISSUE THREAD

**Issue by seanryano** [angular/protractor#2859]
Hi,

  In the last few days my url is wrapped in https causing the test case not running and a "Secure Connection Failed" displayed on browser.

Anyone know why this is happening. I updated to npm 5.5.0 yesterday so don't know if thats the issue.

<addr>
exports.config = {
  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
	baseUrl: "http://qa-auto-iqservice001.eu-fra.adtech.com:8080/",
	specs: ['specs/demandFeatureSpec.js'],

	capabilities: {
		browserName: 'firefox',
	},

	framework: 'jasmine2',

	onPrepare: function() {
		var jasmineReporters = require('jasmine-reporters');
		jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
			consolidateAll: true,
			savePath: 'testresults',
			filePrefix: 'xmloutput'
		}));

    browser.driver.manage().window().maximize();
		browser.driver.get(browser.baseUrl);

		global.isAngularSite = function(flag){
			browser.ignoreSynchronization = !flag;
		};

		global.getRandomInt = function(min, max) {
			var randomNum = Math.floor(Math.random() * (max - min + 1)) + min;
			return randomNum.toString();
		};
	},
}
</addr>

I get the following error:
Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"

Can anyone help me out, why this is happening?

Ryan

**Comment by NickTomlin** [comment]
Hi there!

This sounds like an issue with your sever setup (did your QA server recently start redirecting `http` urls to `https`? — What happens when you hit the URL manually?).

 Because it will require additional investigation and debugging outside of the scope of an issue with protractor core, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
