### ISSUE TITLE
callback that is executed on each capability launch when restartBrowserBetweenTests is true

### ISSUE THREAD

**Issue by spooky** [angular/protractor#2873]
I run protractor in 'headless' mode using xvfb.
Because this does not have a window manager, I need to resize the browser 'manually' by calling `browser.driver.manage().window().setSize(1280, 1024)`. 

When restartBrowserBetweenTests is false, calling this in onPrepare is sufficient, but when restartBrowserBetweenTests is true, it seems that onPrepare is only called on initial browser launch.

The docs state that onPrepare will be run once per capability which makes sense, though it seems that there's no way to execute code before each browser launch without doing a beforEach call in every suite, or did I miss something?

**Comment by NickTomlin** [comment]
I haven't verified this, but you should be able to perform whatever setup you need by adding a `beforeEach` in your `onPrepare` block that will run globally. 

Also, because of it's usage/debugging nature your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
