### ISSUE TITLE
Is there a way to handle "nested iFrames" in protractor.

### ISSUE THREAD

**Issue by Nikhil0538** [angular/protractor#2875]
I am using protractor to test non-angular application and in a scenario i had nested "iFrames", these iFrames are in div tag. Using protractor i was able to navigate to second iFrame, but could not read any elements on page. Let me know if you have any suggestions on this.

<div class="modal-content" modal-transclude="">	
<iframe id="frame1" name="newContentItemframe" onload="onLoadDone();" 
<iframe name="frame2" id="form_iframe" 
<input type="text" class="iw-formspub-textbox-active" name="Content/Title" id="field_0">
</iframe>
</iframe>
</div>

**Comment by fgather** [comment]
You have to ensure that the content of the outer is loaded before you navigate into the inner iframe. Could you provide a code example?

**Comment by NickTomlin** [comment]
Hi there!

Because of it's usage/debugging nature, your question is a better fit for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
