### ISSUE TITLE
Protractor does not wait to resolve promises w promise.delayed()

### ISSUE THREAD

**Issue by dman777** [angular/protractor#2877]
In testing my Angular app e2e, I have a promise that resolves to quickly and the element does not show(to be clear it does show outside of the test when clicking manually).

I used this code to slow down the promise resolves. It does successfully slow down the protractor test in everything else... but it does not slow down the promise resolves. Any suggestions?

```javascript
origFn = browser.driver.controlFlow().execute;

browser.driver.controlFlow().execute = function() {
  var args;
  args = arguments;
  origFn.call(browser.driver.controlFlow(), function() {
    return protractor.promise.delayed(100);
  });   
  return origFn.apply(browser.driver.controlFlow(), args);
};
```

**Comment by NickTomlin** [comment]
Hi there!

I'm not quite clear what the question is without more context or definition of terms. My guess is that there's something else wrong here outside of the promise flow.

That said, because of the usage/debugging nature of your question, it is a better fit for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck!
