### ISSUE TITLE
Angular could not be found on the page.

### ISSUE THREAD

**Issue by jagsinghk** [angular/protractor#2885]
- I am just trying to browse to URL using protractor 
- I have set up protractor and I am able to launch a demo angular app works like a treat 
- But, when I try to launch the actual web app I am automating at work it throws below error. 
- What I have worked out is, the version is AngularJS v1.4.8 (So protractor supports that)
- The page is using require.js (Just letting you know if this is one of the information you guys will need) 

Here is the test.js file 

describe('successful login to UBET', function() {
it('login to UBET', function() {

browser.get('http://aaoplappdw12.dnbint.net');

});	
});

Here is the conf.js file 

exports.config = {

seleniumAddress: 'http://localhost:4444/wd/hub',
//directConnect: true,
specs: ['test.js'],
framework: 'jasmine2',
jasmineNodeOpts: {
defaultTimeoutInterval : 5000000
}
};

What I am observing is the app is launched .. it shows loading where the login screen is and then it fails with below error. 

I am not sure if this is a timing issue. I thought protractor was good in a way that I don't have to add lot of waits and is smart enough. 

Message:
Failed: Angular could not be found on the page http://aaoplappdw12.dnbint.ne
t/ : retries looking for angular exceeded
Stack:
Error: Angular could not be found on the page http://aaoplappdw12.dnbint.net
/ : retries looking for angular exceeded
at C:\Users\SinghJagat\AppData\Roaming\npm\node_modules\protractor\lib\p
rotractor.js:672:17

at goog.async.run.processWorkQueue (C:\Users\SinghJagat\AppData\Roaming\
npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.j
s:124:15)

Would be awesome to get some help with this as I am stuck on this for a while now.

**Comment by NickTomlin** [comment]
Hi there!

This definitely shouldn't be happening if angular is on the page and properly initialized. That said, it's going to be hard to get to an answer without more extensive debugging.

Because of this, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
