### ISSUE TITLE
addMockModule for $httpbackend breaks protractor test.

### ISSUE THREAD

**Issue by realisation** [angular/protractor#2886]
I put this code in to help me spy on AJAX requests, but then i started to not be able to find any elements on the page like so: `No element found using locator: By.cssSelector("text-field[model=\"coconut.title\"]")
`

Here's the addMockModule I inserted... 
`  browser.addMockModule('httpMocker', function() {
      angular.module('httpMocker', ['ngMockE2E'])
        .run(function($httpBackend) {
          $httpBackend.whenPUT('/api/v1/burts/:id').respond(function(){
            //return [200, expected_response];
            console.log("hello");
          });
        })
    })`

**Comment by NickTomlin** [comment]
Hi there!

Without more details it's hard to know what the issue is here without some more exploration/debugging. Because of this, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help. This will help your question reach a wider range of answerers and keep the issue queue focused on keep protractor's core in great shape.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by realisation** [comment]
Ah, sorry - no problem
