### ISSUE TITLE
Pending tasks: Protractor does not wiat for them

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2887]
It is not the first time it happens, I am struggling since months to make it work and deterministic but using protractor is very hard to me.

Which should be the pending tasks that protractor waits for?

Also Http request (via $http)?

Quite often my test fails, but only because protractor went to the next instruction while the browser was still waiting for the end of the request (I have screenshots where the loading bar is stil proceeding but the test failed).

You will ask me for the code, but I don't think it is a matter of the code, given that this problem sometimes  occurs some other time does not.

Should I always add explicit waiting ?

**Comment by NickTomlin** [comment]
Integration testing is fraught with non-determinism unfortunately :\ especially when testing complex applications that depend on a lot of external services / interactions. 

I've found that using explicit waits is the best solution for this (and are absolutely necessary when mixing with non-angular parts of an application), but often there are changes in the way that I write my tests that can help as well. I'd suggest taking a look at the [styleguide](https://github.com/angular/protractor/blob/master/docs/style-guide.md) and then trying to isolate the non-deterministic parts of your tests and working through them via StackOverflow and Gitter. 

I'm going to go ahead and close this issue, since it's a better fit for the mediums mentioned above (and because of the guidelines in CONTRIBUTING.md). If there's something specific you feel protractor could do to make this easier please feel free to re-open the issue with a specific scenario or open a PR with a fix.

Thanks and good luck!

**Comment by bitliner** [comment]
Which are the non-deterministic parts?

I understand that you prefer that i post on Stackoverflow, at the same time you re the creator of Protractor, and I would expect a more clear answer.

A developer should not deal with non-deterministic software, I am almost taking the decision to remove protractor an integration testing from my tests. Given these reason maybe you should drive better the development best practices to use in these cases.   

Referring to your styleguide, where is the part that talks about "non-deterministic" parts? That is your styleguide, that is why I am posting here.

**Comment by NickTomlin** [comment]
First, I'm not the creator of Protractor (or a member of the core team), i'm just a user of protractor like yourself that happens to help out with the issue queue :smile: 

I totally agree with you about striving for non-determinism, but unfortunately integration tests are one of those areas where is the hardest to achieve. There are _so_ many different causes of instability on every level of the stack that make this difficult. I've struggled with similar issues using webdriver.io, capybara, or just plain webdriver.js. I personally feel that Protractor does a better job than most on this point, but nothing is perfect. I think it _does_ strive to make this easier, so again please feel free to submit an issue or a PR that helps make it better.

The parts of the styleguide I am referring to (among others are): 

- Restoring the browser to a clean state between each test
- Making tests independent from each other 
- Using the most efficient and non-brittle selectors possible

I don't mean to give the impression that all the answers are there, just that there are some helpful bits of advice to make your tests more stable. I apologize if it gave that impression.

Also, I don't want to brush off your question or minimize the difficulty of integration testing. I just want to divert the conversation to a medium that will (hopefully) get you better answers faster :)
