### ISSUE TITLE
Running Protractor with Docker Selenium Grid + Firefox

### ISSUE THREAD

**Issue by nserebry** [angular/protractor#2920]
Hi,
I'm currently running into the problem running e2e tests with  **protractor on Docker selenium grid**.
I have setup Selenium Grid locally  with linked firefox browser (both are docker containers)
My protractor.config file contains selenium grid address and browser as firefox 
  ```
exports.config = { seleniumAddress: 'http://192.168.99.100:4444/wb/hub', 
multiCapabilities: [ { browserName: 'firefox' }], baseUrl: "sameUrl"}
```
Test run failing with the error messages: 
```

"Error while waiting for Protractor to sync with the page: "<html><head><title>Selenium Grid2.0 help</title></head><body>You are using grid 2.50.0<br>
node_modules/selenium-webdriver/lib/atoms/error.js:113
  
   var template = new Error(this.message);
                  ^
 UnknownError:  <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
Error 405 
HTTP ERROR: 405
Problem accessing /wb/hub/session/null. Reason:
  Http method DELETE is not supported by this URL
[launcher] Process exited with error code 1
>> Exited with code: 1.
Warning: Task "exec:runProtractor" failed. Use --force to continue.

```
I'm new to this kind of setup : selenium grid + docker  and probably missing something . tried to google and stackoverflow but no luck for above error.   Maybe someone had a similar problem ? 
Thank you in advance.

**Comment by NickTomlin** [comment]
Hi there!

Because of its usage/debugging nature, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help. Since your issue is specific to selenium grid and docker, which is not the most common use case, you may also need to ask channels specific to those technologies as well. 

Thanks and good luck!
