### ISSUE TITLE
using count value in for loop

### ISSUE THREAD

**Issue by rfbu** [angular/protractor#2937]
hi,

   I am able to get the count value with the following: 

		element.all(by.options('type as type for type in types')).then(function(elems){
			return elems.length;
		})
		.then(function(count){
			cnt = count;
		});

then later in the code I want to use cnt in a for loop where I also use closure:

	for(var x = 1;x < cnt; x++){
		search_options(x);
	}

	function test(y){
		console.log('input'+y);
	}
	
	function search_options(input){
		it('tess', function(){
			test(input);

		});
	}

the problem is that the for does not execute.

Any tips or guidance is appreciated. Thanks

**Comment by Harsha509** [comment]
HI There,

If "option" is the tagName please use element.all(by.tagname("") ), or element.all( by.css("")) . Please recheck the locator, as per my knowledge there is no locator with 'by.options'. For your reference to please look at this doc to take efficient locators in protractor.

https://github.com/angular/protractor/blob/master/docs/locators.md

Also, In the future, please direct requests like this to StackOverflow or Gitter.

From the the getting help section of the README:

Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
Thanks!

**Comment by NickTomlin** [comment]
Hi there!

This is due to the asynchronous nature of JavaScript. You'll need to ensure that you are using `cnt` in a scope that has access to the resolved value.

In addition, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
