### ISSUE TITLE
Signal-R and Protractor

### ISSUE THREAD

**Issue by mjmilan** [angular/protractor#2938]
I seem to be having problems getting protractor to synchronize with my AngularJS site, and I am beginning to suspect that this is because I could have polling taking place in the form of Signal R... 

Are there any points / common difficulties of using Signal R together with Protractor that I should be aware of? 

I see $timeout can prevent synchronization - are we saying that we should always use $interval for sites that will be tested by Protractor?

**Comment by NickTomlin** [comment]
Hi there!

Because of its usage/debugging nature, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
