### ISSUE TITLE
waitForAngular isn't waiting for $http requests consistently (Pull Request Pending)

### ISSUE THREAD

**Issue by wbyoko** [angular/protractor#2954]
I am having an issue where waitForAngular isn't waiting for $http requests in controllers. `browser.sleep` was used as an quick in-test fix initially.

I was able to identify a possible cause within angular.js where $http requests were not [registering themselves synchronously with the $browser service](https://github.com/angular/angular.js/issues/13782) as an [outstanding request](https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L41) which caused [`$browser.notifyWhenNoOutstandingRequests`](https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L75) (via [`angular.getTestability(el).whenStable(callback)`](https://github.com/angular/protractor/blob/master/lib/clientsidescripts.js#L65)) to return immediately and not wait for requests.

The [change](https://github.com/angular/angular.js/pull/13862/files) would be to register the $http request as an outstanding request immediately by moving that code from [$httpBackend](https://github.com/angular/angular.js/blob/master/src/ng/httpBackend.js#L58) to $http.

In the project where I was having these issues this resolved them.

There is a [pull request](https://github.com/angular/angular.js/pull/13862) outstanding and would hope to get input from those on the protractor side as to whether this is an appropriate fix. 

Should $http requests register as an outstanding request with the $browser service immediately?

This is the initial issue: https://github.com/angular/angular.js/issues/13782

This is the pull request: https://github.com/angular/angular.js/pull/13862

This is a fiddle showcasing that $http isn't registering synchronously: http://jsfiddle.net/awtwff3x/ 

Please ask questions if more explanation is needed; either here or on the pull request itself.

Thanks for your time.

**Comment by juliemr** [comment]
@mgiambalvo and I think that we have a more general way to fix this - `testability.whenStable` should always run `$browser.notifyWhenNoOustandingRequests` asynchronously. This should give http a chance to register all requests with the backend first. We're testing that out now.

**Comment by wbyoko** [comment]
That sounds great!

There are definitely more way to fix this. That seems to be a possible solution as well.

Thank you for taking a look at this!

**Comment by mgiambalvo** [comment]
I'm going to proceed with the PR Julie mentioned, but it's worth pointing out that Protractor already effectively runs $browser.notifyWhenNoOustandingRequests asynchronously, since it only calls this from webdriver calls. The attached fiddle doesn't represent a situation that Protractor would ever encounter, since Protractor would never be calling $browser.notifyWhenNoOustandingRequests synchronously from within your application. The example app in #1641 is problematic for the same reasons.

It is possible there exists a situation where Protractor calls whenStable() when there are no outstanding http requests and there's a callback on the asyncQueue that will initiate one. However, I haven't been able to find a way for that to occur in Angular 1.5.1.

Is your issue consistent, or intermittent? Also, can you describe your app in more detail? Are you using ui-router? Are you using If you could produce an example app that demonstrates the problem when using Protractor, that would be very helpful. However, a more detailed description of when you're seeing this problem would probably suffice.

**Comment by juliemr** [comment]
Closing as stale.
