### ISSUE TITLE
 Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL 

### ISSUE THREAD

**Issue by sashank6** [angular/protractor#2968]
```js
describe('H2ome Title Bar Text description',function(){

  it('Test2',function(){
 browser.get('https://localhost/viewer');




   expect(browser.getTitle()).toBe('Test Screen');
 });

});
```
I have a non-angular login screen before this page, I am able to login with browser.driver. After logging in, the page is redirected to angular 2 app. 

conf.js
```js
spec:['loginTest.js','homeTitleBar.js']
```
After executing loginTest.js, I am getting the error  Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL  in spite of setting the timeout to 120sec.

**Comment by rolandoldengarm** [comment]
Protractor will by default wait until Angular is loaded. Did you set:
````
beforeEach(() => {
        browser.ignoreSynchronization = true;
});
````
to not wait for Angular to load?

**Comment by sjelin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!


PS.  The problem is probably that you need `ignoreSynchronization` for the non-angular page, as @rolandoldengarm  said
