### ISSUE TITLE
webdriver-manager does not respect NODE_TLS_REJECT_UNAUTHORIZED environment variable

### ISSUE THREAD

**Issue by dsebastien** [angular/protractor#3035]
Bug report
---

- Node Version: `4.2.4`
- Protractor Version: `3.2.0`
- Operating System and Version `Windows 10 x64`
- Configured environment variables: 
* HTTP_PROXY
* HTTPS_PROXY
* NODE_TLS_REJECT_UNAUTHORIZED=0
- Environment: our corporate proxy does SSL termination, meaning that when going through it, it only gives back self-signed certificates

- Steps to reproduce the bug

Execute `webdriver-manager update` behind a corporate proxy that performs SSL termination.
Expected behavior: successful download of https://selenium-release.storage.googleapis.com/xxx/selenium-server-standalone--xxx.jar

Result:
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.51/selenium-server-standalone-2.51.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip...
Error: Got error Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN from https://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip
Error: Got error Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN from https://selenium-release.storage.googleapis.com/2.51/selenium-server-standalone-2.51.0.jar

**Comment by dsebastien** [comment]
I've tested with `webdriver-manager update --standalone --ignore_ssl`, which seems a bit better but now I get a 403 and our A/V seems to think that the selenium jar is a virus... :)

You may consider this issue bogus given that the support is there, but maybe consider respecting the NODE_TLS_REJECT_UNAUTHORIZED environment variable?

**Comment by cnishina** [comment]
`NODE_TLS_REJECT_UNAUTHORIZED` looks like it will eventually be deprecated https://github.com/nodejs/node/issues/5258.
Per https://github.com/request/request/issues/1777, it looks like we need to set `rejectUnauthorized` to false in addition to setting `strictSSL` to false.

Since this is probably a setup / scenario that is difficult to test, the proposed solution is to create a branch and for you to test it out. After pulling down the branch `pr_ssl`, run the local webdriver with `node bin/webdriver-manager update --ignore_ssl`

https://github.com/cnishina/protractor/tree/pr_ssl

Let me know if that works.

**Comment by dsebastien** [comment]
The pr_ssl branch does improve the situation a bit, but our corporate A/V and proxy are too strict:
* the jar file is considered a virus by the A/V
* the zip file is not accessible because of the proxy rules (forbidden category)

This is why we're now trying to host the files internally and use the alternate_cdn argument, which does not work like we need it to :p (see #3046).

Your modification should be merged on master though as it does provide an improvement to the scenario described in this issue.

**Comment by dsebastien** [comment]
+1, thanks!
