### ISSUE TITLE
Tests failing when using by.model unknown error: angular is not defined

### ISSUE THREAD

**Issue by smithscripts** [angular/protractor#3057]
Error:      - Failed: unknown error: angular is not defined
  (Session info: chrome=49.0.2623.87)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.1 SP1 x86_64)

Node: 5.9.1

exports.config = {
  baseUrl: 'http://localhost:5555',

  specs: [
    'dist/dev/**/*.e2e.js'
  ],
  exclude: [],

  framework: 'jasmine2',

  allScriptsTimeout: 110000,

  jasmineNodeOpts: {
    showTiming: true,
    showColors: true,
    isVerbose: false,
    includeStackTrace: false,
    defaultTimeoutInterval: 400000
  },
  directConnect: true,

  capabilities: {
    'browserName': 'chrome'
  },

  onPrepare: function() {
    var SpecReporter = require('jasmine-spec-reporter');
    // add jasmine spec reporter
    jasmine.getEnv().addReporter(new SpecReporter({displayStacktrace: true}));

    browser.ignoreSynchronization = false;
  },
  useAllAngular2AppRoots: true
};

Test
  it('should set focus', () => {
    var input = element(by.model('config.value'));
    //input.evaluate('config.value = true');
    input.clear();
    input.sendKeys('test');
    input.sendKeys(Key.TAB);
    input.click();
    var highlightedText = browser.executeScript(function getSelectionText() { return window.getSelection().toString(); });
    expect(highlightedText).toEqual('test');
  });

**Comment by NickTomlin** [comment]
Hi there!

Since there isn't a clearly reproducible test case, and the problem is going to requiring debugging specific to your application, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
