### ISSUE TITLE
Problem with version upgrades 

### ISSUE THREAD

**Issue by Nikhil0538** [angular/protractor#3063]
I updated protract(2.4 to 3.2), Firefox(42-45), webdriver-manager(2.41[I did not remember exactly]-2.52), when i ran this on older versions of protractor it works well but after updating to latest version i am facing lot of issues. It could not navigate between iframes(non-angular page). 
Did any one have the same issue?

please do some one comment, I am struggling from 3 days.

Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing)
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Fill in the information that corresponds to your type of issue below
4. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue)

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by NickTomlin** [comment]
Hi there!

Upgrading protractor means upgrading your selenium version, which can lead to any number of issues. These need to be sorted out on a case-by-case basis and are _not_ an issue with protractor core. 

Please follow the [contributing](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing) guidelines and ask a question on gitter or stackoverflow to get help.

Additionally, i'm going to close this because of the disclaimer in our issue template:

> Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue)
