### ISSUE TITLE
Protractor 3.2.2 depends on a vulnerable version of request

### ISSUE THREAD

**Issue by jedrichards** [angular/protractor#3083]
Protractor depends on request@2.67.0 which has a vulnerability:

https://snyk.io/vuln/npm:request:20160119

I know this vulnerability is only applicable when request is used in a web app, but any users that are automating vulnerability checking (with Node Security Project or snyk etc.) will have failed builds with protractor@3.2.2.

Maybe you should add some vulnerability checking in your build pipeline? This is the second time in a week I've raised an issue on this project about vulnerable dependencies.

**Comment by cnishina** [comment]
Request dependency is being removed from protractor. It will (in the future https://github.com/angular/protractor/pull/3068) use webdriver-tool as a dependency and it uses 2.69.0. See https://github.com/angular/webdriver-tool/blob/master/package.json

If this issue is causing a problem for your testing, feel free to reopen this bug with an example of the test with logs to show how this is causing a security problem for you. This is already a planned pull request and does not seem to be an issue for the next release of protractor.

**Comment by jedrichards** [comment]
In this case this isn't a security problem, rather than automation problem. But good news it looks like it'll naturally go away in the near future. Cheers!
