### ISSUE TITLE
Add custom matchers for better failure errors 

### ISSUE THREAD

**Issue by mohsen1** [angular/protractor#3088]
Currently I get `Expected false to be true` failure error when a test like this fails:

```js
it('shows user information', ()=>{
  expect($('#user .name').isPresent()).toBe(true);
  expect($('#user .id').isPresent()).toBe(true);
});
```

From that error I don't know which assertion failed. 

What if in Protractor `isPresent` and alike methods were extra Jasmine assertion matchers so above test could be written like this:

```js
it('shows user information', ()=>{
  expect($('#user .name')).toBePresent();
  expect($('#user .id')).toBePresent();
});
```
with that the thrown error can know about what was expected to be present. Something like "expected {selector} to be present":

**Comment by Xotabu4** [comment]
@mohsen1 
I am trying to avoid expectations of isPresent() and prefer isDisplayed() - since it also checks element visibility.
As for me additional message works perfectly, this is kind of hidden feature of jasmine - you could pass string message for error:
```javascript
it('shows user information', ()=>{
  expect($('#user .name').isPresent()).toBe(true, 'Expected user name to be present on the page');
  expect($('#user .id').isPresent()).toBe(true, 'Expected user id to be present on the page');
});
```
or even
```javascript
it('shows user information', ()=>{
  expect($('#user .name').isPresent()).toBeTruthy('Expected user name to be present on the page');
  expect($('#user .id').isPresent()).toBeTruthy('Expected user id to be present on the page');
});
```

But for even better redability i currently working on small lib - additional jasmine matchers for protractor. Check this, there currently only few matchers, create issue if you need something, or pull request - 
https://github.com/Xotabu4/jasmine-protractor-matchers
https://www.npmjs.com/package/jasmine-protractor-matchers

**Comment by juliemr** [comment]
I think this is a perfect feature for an external lib, thanks @Xotabu4 !
