### ISSUE TITLE
Unable to resolve "Cancel" button 

### ISSUE THREAD

**Issue by SiddharthMalhotra** [angular/protractor#3110]
Hi, 

We have an admin page where you can save/cancel a user creation. 

![capture](https://cloud.githubusercontent.com/assets/4989369/14405078/0b84d1b4-fea4-11e5-88f8-6dcb866da43d.PNG)

Our protractor test are trying to check the presence of this button

![capture1](https://cloud.githubusercontent.com/assets/4989369/14405097/5c2b480a-fea4-11e5-8799-39caf653e619.PNG)
 
The admin page contains these references 

![capture2](https://cloud.githubusercontent.com/assets/4989369/14405103/85159d92-fea4-11e5-9732-ebd01d42c522.PNG)

However the test case fail on the CI server as below, 

![capture4](https://cloud.githubusercontent.com/assets/4989369/14405113/bffaf39e-fea4-11e5-8fd0-b74ffdfa28fc.PNG)

**Comment by NickTomlin** [comment]
Hi there!

I am able to resolve to an element using `by.buttonText` in an Angular or Angular 2 application. Unfortunately this means that the issue could be any number of things in your application or testing setup and will require some debugging to get to the real problem.

Because of debugging nature of your question, it is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

If after that you still feel that this is an issue with Protractor, please re-open another issue and follow the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) and provide an isolated reproducible example.

Thanks! 😄

**Comment by SiddharthMalhotra** [comment]
Hi Nick, 

We've been stuck at this for quite a while now. None of our angular 2 div/classes/buttons are getting picked up. 

Could you give some debugging solutions.

Thanks! :)

**Comment by NickTomlin** [comment]
Unfortunately, this isn't the right forum for debugging. Please ask on StackOverflow or Gitter. It sounds like there's a configuration issue somewhere in your application or protractor if `div`s aren't even being picked up. 

Thanks!
