### ISSUE TITLE
Memory leak in 3.2.2 or related lib

### ISSUE THREAD

**Issue by gssatcc** [angular/protractor#3112]
Bug report
---

- Node Version: `v4.4.2`
- Protractor Version: `3.2.2`
- Browser(s): `all`
- Operating System and Version `Ubuntu LTS 14.04.4`

Hello,
During execution of spec suites on protractor 2.5.1 I saw that memory usage is no more than 400MB and stays so for hours of runing specs.

Right after update to protractor 3.2.2 I have noticed huge memory usage. I have increased the swap space to 5GB because the Machine under tests has only 2GB of ram and it took only 30min for node/protractor processes to consume the whole memory. I can not find any related issues so may I ask you to share some starting points where to look at for the issue. Thanks!

**Comment by Sabartius** [comment]
Same here, protractor takes up to 10 times of memory than before, but we only upgraded from Protractor 3.1.1 to 3.2.2. 
So it should be a recent commit, that caused this issue.

**Comment by cnishina** [comment]
VM Experiment 1:

Protractor version: `3.3.0`
Node version: `5.7.0`
OS: `Ubuntu 15.10`
CPU: 3
MEM: 12 GB

Running the test suite does not appear to be leaking memory. Although my set up is 12 GB ram. The maximum ram used to run the suite was around 2GB ram. This did not have any noticeable problems.

VM experiment 2:
Protractor version: `3.3.0`
Node version: `4.2.4`
OS: `Ubuntu 15.10`
CPU: 1
MEM: 1 GB

Trying to engage more swap usage. During the test suite, the memory was pinned at 90% with cpu at 100%. Some swap space was used. After the test, the memory went back down to the starting memory usage, around 54%.

**Comment by cnishina** [comment]
@gssatcc Could you detail what is running on your machine? Is it hosting your webapp? Is it running a selenium standalone jar?

Also have you tried a machine with more memory?

**Comment by dlennon0** [comment]
@cnishina did you notice a spike in CPU activity for Node? I dropped in 3.3.0 on my RHEL test system (only 2GB & Node 4.4.0) and the node CPU usage spiked significantly ~80/90%, slowing my tests to a crawl.
When I roll back to 3.1.1, node CPU fell back to ~5/10% and chrome spiking (as expected) to ~80/90%. I am using sharding if that has changed in the latest releases.
Selenium 2.5.3 server memory usage was consistent between the two tests.

**Comment by gssatcc** [comment]
@cnishina The machine is running selenium hub part of 5 node grid. It is running also selenium-server-standalone. I have updated to protractor 3.3.0 to check again. The situation was better but still memory usage is high enough and it is getting worse after the first hour of run. You can find attached screenshot of htop.

Also I have tried on machine with 4 cores and 8GB of ram. I didn't notice something suspicions of memory usage but as @dlennon0 noticed the CPU usage is high enough there.

![selection_0022](https://cloud.githubusercontent.com/assets/2139549/14885467/3335abac-0d54-11e6-9610-aeaf5a09e311.png)

**Comment by cnishina** [comment]
@dlennon0 CPU spikes are not part of this issue. Having CPU usage spike on a sharded test does make sense if you are creating several instances of browsers. In both the tests described below, the CPU usage averaged around 80% to 90%. If this is a concern, there are tools like cpulimit that could help limit the percentage of CPU usage.

@gssatcc 

Investigation:
------------------

1. A single conf with 1 browser that will run the basic configuration tests over a long period of time. The memory measurements will be taken at every ~10 minutes.
2. A single conf with sharding of 3 browsers that will run the basic configuration tests over a long period of time. The memory measurements will be take at every ~10 minutes.

Results:
-----------

1. For the single browser, over the last 2 hours, the memory usage before the test was ~2.1GB. During the test the memory usage varied between 3.4GB and 3.9GB. However, the memory usage trend oscillated and did not grow to indicate leaking memory.

2. For browser sharding, I ran the test for ~1 hour, the memory usage at ramp up was around 4GB and peaked at 7GB and dropped back down. The memory usage trend also oscillated around 6GB and also did not grow to indicate a memory leak.

After testing, I'm closing this issue since there was no evidence of memory leaks.

**Comment by gpmikep** [comment]
I'm not suggesting there is a memory leak, but it would seem that protractor > 3.1.1 requires way more memory (approx 10x) and in our case runs 5x slower.


Memory values in megabytes acquired from process.memoryUsage()

Using 3.1.1:
BeforeScenario:  rss: 70.337 heapTotal: 56.906 heapUsed: 24.307
AfterScenario:  rss: 81.617 heapTotal: 59.989 heapUsed: 40.911
Runtime 0m03.363s

Using 3.2.0:
BeforeScenario:  rss: 92.32 heapTotal: 65.186 heapUsed: 43.866
AfterScenario:  rss: 645.149 heapTotal: 615.024 heapUsed: 541.361
Runtime 0m15.954s

Same test, same environment, only difference is using protractor 3.1.1 or 3.2.0. Approx same memory usage for protractor 3.2.0, 3.2.1 and 3.3.0.
