### ISSUE TITLE
Automation test cases are sporadically failing

### ISSUE THREAD

**Issue by mandip2kaur** [angular/protractor#3192]
Automation test cases are sporadically failing. At times all the test cases are passing, and at times few are failing on Chrome and Firefox. Following Errors are present: 

- Index out of bound. Trying to access element at index: 1, but there are only 0 elements that match locator By(css selector, [ng-click="openMenu($mdOpenMenu, $event)"])[39m 
- Element is not clickable at point (301, 315.6000061035156). Other element would receive the click: <md-list class="md-launchpad-theme" role="list" style="height: 300px"></md-list> 

I found following link on google as answer to my problem:http://www.blaiseliu.com/protractor-error-element-is-not-clickable-at-point-xx-xx/ .
But Approach 2 and 3 might not be feasible as there are large number of elements clicked.

Please let me know the approach to be taken for test cases sporadically failing.
Using angular:1.4.1
protractor:3.0.0

**Comment by jeremycy** [comment]
Hi, are you certain your errors are due to window sizes?  And I assume when you step through your tests all pass.  

My personally experience on either errors above - 
1.  Usually happens when it's data dependent and it fails due to timing.
2.  Other element would receive click - your locator could be returning more than one element and the intended one isn't being picked at the time.

You may want to try something such as click when clickable.  
https://github.com/angular/protractor/issues/1555

-J

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
