### ISSUE TITLE
Protractor doesn't generate "selenium" folder while npm install

### ISSUE THREAD

**Issue by igniteram** [angular/protractor#3225]
While using directConnect: true in the config.js file, and set browser as chrome, protractor tries to find the "selenium" folder in which the chromedriver is present but somehow protractor doesn't generate this folder.
I have gone through various SO threads and tried webdriver-manager update from inside the node_modules/bin folder but it always shows
already upto date and chromedriver upto date.

Note: When i forked the protractor repo i could find selenium folder which has the chrome driver, i manually copied that into my project and it worked but i want to understand why it is not built while installing the protractor modules.
@juliemr @cnishina @NickTomlin any thoughts??

**Comment by juliemr** [comment]
You need to call `<protractor-dir>/bin/webdriver-manager update` to get a selenium folder. We don't automatically install it because the files are large and not everyone will need them (e.g. if you are just using a remote like SauceLabs or already have a selenium server somewhere on your machine).

I'm not sure why calling webdriver-manager always shows up to date for you, but that is a support question better suited for SO or gitter. Thanks!

**Comment by igniteram** [comment]
Thanks @juliemr for the prompt reply, let me just find out why webdriver-manager update is not working for me and yes i would post it in SO or gitter 😄

**Comment by krthknan** [comment]
@juliemr _<protractor-dir>/bin/webdriver-manager update_. It doesn't work out for me, it never creates selenium folder inside my project
