### ISSUE TITLE
Angular 2 link click requires previous blur on validated input

### ISSUE THREAD

**Issue by renehamburger** [angular/protractor#3229]
The issue can be reproduced with the following simple snippet:
```js
it('blur click bug', () => {
  browser.get('https://test-app.leanix.net');
  //$('header').click(); // Test fails without this blur
  $('a').click();
  expect($('lx-reset-password').isPresent()).toBe(true);
});
```
This test fails, unless the click on the header is added back in to trigger a blur (and the initial validation) on the auto-focussed input. `useAllAngular2AppRoots` is set to true and higher timeouts or additional `browser.sleep()` statements don't resolve the issue.

**Comment by juliemr** [comment]
I believe this is working as intended. When I go to https://test-app.leanix.net and try to navigate this as a human user, I see the same behavior - I need to click the link twice or click somewhere else before I can actually navigate through to the password recovery. 

Since Protractor is matching the behavior the user sees, I'd say this is a bug in the application :)

Please open a new issue if I missed a problem.

**Comment by renehamburger** [comment]
Apologies, you're absolutely right! The email field was prefilled in all my browsers, which is why it didn't occur outside of the test. So it's an Angular not a Protractor issue. Thanks for checking.
