### ISSUE TITLE
Protractor tests are unable to click the html elements on Angular Application when MQTT connection is establised

### ISSUE THREAD

**Issue by ssirisha** [angular/protractor#3232]
We are running in to an issue with protractor in following scenario. We have an angular application that uses require.js to load dependencies. We have lot of rest API calls hitting the back-end server via angular http service. We are able to test the application in this scenario without any issues. However, our application also uses PAHO MQTT client to talk to MQTT broker. Whenever our application does something that establishes an MQTT connection via web sockets, the protractor tests are unable to click the html elements. Note that it can still find the element. We have added code to wait until element appears and that logic works fine. However, we are unable to ‘click’ anything through protractor whenever web socket connection is established. From the application side, during troubleshooting this issue, we have eliminated all subsequent things that happen in the app that follows the establishment of the connection, and just made it to connect via web-socket. Even after that, mere existence of a live web socket connection seem to block the protractor test.

- Node Version: `v4.2.6`
- Protractor Version: `3.3.0`
- Browser(s): `Chrome and Firefox`
- Operating System and Version `Windows 7 Enterprise SP1`,System Type: 64bit

**Comment by NickTomlin** [comment]
Hi there!

Because it is tied to specific use case/implementation (PAHO MQTT), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
