### ISSUE TITLE
The browser restarts between 'it' blocks (with restartBrowserBetweenTests: false)

### ISSUE THREAD

**Issue by bbaki** [angular/protractor#3254]
Hi,
I have a problem with the browser that restarts itself after each `it` block. I found an option of `restartBrowserBetweenTests` but switching it to `true` or `false` doesn't really do anything (and I think false is the default option here).

Everything runs ok when I do all my tests in one `it` block but that kind of defeats the purpose of `it` blocks. Doing the page redirection in a beforeEach block is not an option as I need to have several fields completed to get to the next page. 

spec.js:
```
describe('My test spec, ', function () {
	beforeEach(function () {
		browser.get('https://mywebsite.com/property/#/?login=GT_QWER_FTG4');
	});

	it('should have a product line of "moto" that redirects to the "sale" page', function () {
		var motoProductLine = element.all(by.css('.product-line-choice-container__widget')).get(0);

		expect(motoProductLine.isDisplayed()).toBeTruthy();
		motoProductLine.click();
		expect(browser.getCurrentUrl()).toMatch(/https:\/\/mywebsite.com\/property\/#\/sale\/(\d)+\/(\d)+\/calculation\/saleWidget/);

		// --- When placed here, everything works fine ---
		
		// var model = element(by.model('ctrl.fastInput.registrationNumber'));
		// model.sendKeys('ABC1337');
		// expect(model.getAttribute('value')).toContain('ABC1337');
	});

	it('should have a working input with the model "ctrl.fastInput.registrationNumber"', function () {
		// --- When placed here, the test fails ---
		// --- Failed: No element found using locator: by.model("ctrl.fastInput.registrationNumber") ---

		var model = element(by.model('ctrl.fastInput.registrationNumber'));
		model.sendKeys('ABC1337');
		expect(model.getAttribute('value')).toContain('ABC1337');
	});
});
```

config:
```
exports.config = {
	framework: 'jasmine',
	seleniumAddress: 'http://localhost:4444/wd/hub',
	specs: ['spec.js'],
	restartBrowserBetweenTests: false
};
```

_I believe this to be a bug of some sort (that's why I'm not asking on SO)._ Many thanks.

--- Info ---
- Node Version: 4.2.2
- Protractor Version: 3.3.0
- Browser(s): Chrome
- Operating System and Version: Window 7 Professional SP1 x64

**Comment by cnishina** [comment]
Just tried this out and this does not appear to be reproducible. `restartBrowserBetweenTests` when set to true restarts the browser session. When it is set to false it does not restart the browser session.

Looking at your spec, it looks like you are clicking on something and navigating to a different url. After you get to the next page you are sending keys to the model `ctrl.fastInput.registrationNumber`. 

Because you are calling `beforeEach`, it will navigate to the original url before each `it` block ('https://mywebsite.com/property/#/?login=GT_QWER_FTG4'). So this is why the first `it` block uncommented works and the second `it` block does not work. This is independent of restarting the browser or continuing with the same browser session.

You could keep the same two `it` blocks and replace your `beforeEach` with a `beforeAll` with the `restartBrowserBetweenTests` to false.
