### ISSUE TITLE
Error: No selenium server jar found at the specified location Check that the version number is up to date.

### ISSUE THREAD

**Issue by premkh9** [angular/protractor#3268]
Error: No selenium server jar found at the specified location (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/selenium/selenium-server-standalone-2.51.0.jar). Check that the version number is up to date.

I am observing above issue all of a sudden in Jenkins. When I execute below command, observing different issues again

node_modules/protractor/bin/webdriver-manage update

[22:36:28] I/local - Starting selenium standalone server...
[22:36:28] I/launcher - Running 1 instances of WebDriver
[22:36:29] I/local - Selenium standalone server started at http://10.224.247.131:44726/wd/hub

/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/selenium-webdriver/lib/error.js:27
    super(opt_error);
         ^
WebDriverError: null

Everything was working as expected till last Friday. Observing this new issue from Saturday. Attached package.Json for reference 
[package.zip](https://github.com/angular/protractor/files/314525/package.zip)

**Comment by cnishina** [comment]
There's a few details missing but I think this will help:

webdriver-manager v10.0.4 loads the selenium server jar file in the `node_modules/webdriver-manager/selenium` folder and does not use the `node_modules/protractor/selenium` folder by design. When launching a local instance, protractor v3.1.1 is looking for `node_modules/protractor/selenium`. If you are using webdriver-manager v10.0.4 to update, protractor does not know the new location of the folder. The next release of protractor will have these two items in sync.

Because protractor v3.1.1 already has webdriver-manager, prefer using `node_modules/protractor/bin/webdriver-manager` to update your binaries and start your server. In both the next release of protractor and v3.1.1, you should not need to include the dependency of webdriver-manager in your `package.json`. 

If you wish to use both protractor v3.1.1 and webdriver-manager v10.0.4 node modules, this could potentially be your work around: You could specify in your configuration file where the binary files are with `seleniumServerJar` and `chromeDriver` per the [referenceConf.js](https://github.com/angular/protractor/blob/master/docs/referenceConf.js).

**Comment by GabLeRoux** [comment]
Had same error, I had to run ` webdriver-manager update` and it worked

**Comment by florestankorp** [comment]
My solution was to change the version of my `jar` file to the newest in `../e2e-tests/config/protractor.e2e.local.conf.js`
