### ISSUE TITLE
Protractor TypeScript misc items to improve

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3359]
* 'protractor/global' sets the value for browser via `global['browser']` but if a user sets noGlobals to false, we should be using the protractor namespace: `global['protractor']['browser']`
* should continue to have the 'protractor' global object as part of the 'protractor/global'

**Comment by Droogans** [comment]
Can you please expose the `ElementFinder` class (not the type) without having users resort to things like this:

```ts
import {ElementFinder} from 'protractor';
let ElementFinderConstructor: typeof ElementFinder = require('protractor/built/element').ElementFinder;

class InheritsFromYou extends ElementFinderConstructor {
    constructor(rootElement: ElementFinder) {
        super(browser, rootElement.elementArrayFinder_);
    }
};

class MyStuff extends InheritsFromYou {
    constructor(rootElement: ElementFinder) {
        super(rootElement);
    }

    // now my component has `isDisplayed`, etc., for free

    // my custom logic here
};
```

We're about to start using this pattern in a few places, can this be exported formally so that I can feel more confident inheriting from this class? I'm worried that as of right now I'm pulling in private internal members from protractor and might end up regretting the decision later.

[Here's a link to a larger example](https://github.com/Droogans/encore-ui/blob/e8c67759adca09dceef5635a5456948c062818ff/utils/rx-page-objects/src/rxDatePicker.page.ts), if that helps.

**Comment by cnishina** [comment]
@Droogans You should be able to use and extend typings since the TypeScript gets transpiled to JavaScript and the JavaScript require should go to the correct file in the Protractor module. I tried this out:

```
import {ElementFinder} from 'protractor';

export class ExtendElementFinder extends ElementFinder {
  constructor() {
    super(null, null);
  }
}


describe('should work', () => {
  beforeEach(() => {
    let extendElementFinder = new ExtendElementFinder();
    console.log(extendElementFinder);
  });
  // some test...
});
```

console output:
```
{ [Function: Browser]
  wrapDriver: [Function],
  By:
   ProtractorBy {
     className: [Function: className],
     css: [Function: css],
     id: [Function: id],
     linkText: [Function: linkText],
     js: [Function: js],
     name: [Function: name],
     partialLinkText: [Function: partialLinkText],
     tagName: [Function: tagName],
     xpath: [Function: xpath] },
  ExpectedConditions: ProtractorExpectedConditions {} }
```

**Comment by cnishina** [comment]
`protractor/globals` issue has been addressed. Closing this issue.

@Droogans please feel free to direct message me on gitter. If this is still an issue...
