### ISSUE TITLE
ERRORs :angle_platform_impl.cc(33) & gl_surface_egl.cc(594) in protractor log

### ISSUE THREAD

**Issue by vijaybolleypally** [angular/protractor#3411]
Hi Team Protractor,

This issue is a duplicate of " https://github.com/angular/protractor/issues/2957" which was closed due to less info
errors:
[0725/113233:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 5: DXGI 1.2 required to present to HWNDs owned by another process.
[0725/113233:ERROR:gl_surface_egl.cc(594)] eglInitialize D3D11 failed with error EGL_NOT_INITIALIZED, trying next display type

Above mentioned errors are coming in protractor console:
1.This is coming only in windows CMD and intellij IDE Terminal (no such error in git bash)
2.Above error coming after "I/launcher - Running 1 instances of WebDriver" lines in protractor log
3.Above lines printing once for each driver instance

My Config Details:
"devDependencies": {
    "jasmine": "^2.4.1",
    "protractor": "^4.0.0",
    "webdriver-manager": "^10.2.1"
  }

- Node Version: v6.2.0
- Protractor Version: 4.0.0
- Browser(s): Chrome:Version 52.0.2743.82 m
- Operating System and Version winows 7 
- Your protractor configuration file
#####configuration file start####
var myReporterObject = require('./my.html.report.js');
var reporter = myReporterObject.needGlobally;
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  directConnect: true,
  suites: {
    login: 'features/login/login.suite.js',
    tenants: 'features/multiTenant/multi.tenant.suite.js'
  },
  noGlobals: false,
  getPageTimeout: 30000,
  allScriptsTimeout: 25000,
  capabilities: {
    browserName: 'chrome',
    maxInstances: 3,
    shardTestFiles: true
  },

  beforeLaunch: function () {
    return myReporterObject.beforeLaunchMethod();
  },

  onPrepare: function () {
    require('./protractor.prepare.js').toWork(reporter);
  },

  afterLaunch: function (exitCode) {
    return myReporterObject.afterLaunchMethod(exitCode);
  },

  params: {
    lang: {
      name: 'Optimus Prime',
      filepath: "FilePathTo ADD"
    }
  },
  resultJsonOutputFile: "test_reports/josn_reports/Testresult.json",
  restartBrowserBetweenTests: false,
  framework: 'jasmine2',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 90000,
    print: function () { }
  }
};
#####configuration file end####

This is a trivial issue i just want to know what causing this error lines to happen

**Comment by cnishina** [comment]
A quick Google search on: "ANGLE Display::initialize error 5: DXGI 1.2 required to present to HWNDs owned by another process", I end up at this page:
https://productforums.google.com/forum/#!topic/chrome/euWzZX7rnTI;context-place=forum/chrome

...which sounds like a WebGL problem.

Then a quick lookup on how to get WebGL working:
https://support.mozilla.org/en-US/kb/upgrade-graphics-drivers-use-hardware-acceleration

Since this is not a protractor framework bug, I hope this helps. Please use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor) or [Gitter](https://gitter.im/angular/protractor) for support questions. For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
