### ISSUE TITLE
  Module 'ngMockE2E' is not available!

### ISSUE THREAD

**Issue by noor92** [angular/protractor#3420]
I am new to angular, and I am following this tutorial rockabyebb.com.ws4.webshaper.com.my.

Here is my login.test.js 

```
describe ('Clicking on the login button', function()
{
var mockModule;

	beforeEach(function(){
		browser.get('#/loginPage');
		mockModule = require('./mock');
	});


	//check if the api is working and returns the correct value
	it('should check if the api is working and returns correct credentials',function()
	{
		browser.addMockModule('httpBackendMock', mockModule.signin_request);  
		expect (mockModule.signin_request).toEqual('user@gmail.com')

	})


	it('another it', function()
	{
		
	})
})



```

and here is my mock.js file

```
exports.signin_request = function(){
    var expected_response = ('1 - noor.alhabbal@gmail.com')
	angular.module('httpBackendMock', ['app', 'ngMockE2E'])
        .run(function ($httpBackend) {
            $httpBackend.whenGET('http://website.com/api/login?email=user@gmail.com&password=123456').respond(function(){
                return [200, expected_response];
            });
            // $httpBackend.whenPost(/.*/).passThrough();
    });
}
```

I don't understand why I get this error 

> 
>  Error: [$injector:modulerr] Failed to instantiate module ngMockE2E due to:
>  Error: [$injector:nomod] Module 'ngMockE2E' is not available!

**Comment by mgiambalvo** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

That said, maybe there's a problem with the tutorial? You're getting that error because, at least in the code you posted, you never defined an ngMockE2E module. I tried looking into the tutorial, but the link you posted appears to be a site selling bowls for toddlers.

Thanks!

**Comment by noor92** [comment]
thank you for letting me know. I posted it on SO but it got no answer so i thought I'd ask on here, but i'll try Gitter. Sorry for that, this is the correct link http://prashantsahni.in/blog/2014/09/28/mocking-apis-integration-testing-with-protractor.html
