### ISSUE TITLE
Not able to pass spec value from gulp to conf file

### ISSUE THREAD

**Issue by Saurabh06** [angular/protractor#3450]
I am not able to pass 'spec' value to be execute from gulp to conf file

**Comment by NickTomlin** [comment]
Hi there!

Since your question is about gulp + protractor and not protractor core, it is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
