### ISSUE TITLE
Failed expectations log pointing to wrong line in the test

### ISSUE THREAD

**Issue by prabhu43** [angular/protractor#3470]
I am running protractor(3.2.2) tests for angular2 app. when the test fails, the log is pointing to the wrong line as failure happened. I am using typescript for angular2 app and also for protractor tests.

. How to fix this?

**Comment by cnishina** [comment]
There is not enough information to see if this is a framework bug / issue. Please see the issue template for more information.

I will take a guess at what I think is the problem with the wrong line. Since Protractor uses JavaScript to run your test, the line of failure Protractor is reporting is in reference to your JavaScript file. The line of failure should be close/around the line of failure in TypeScript but they are not the same since TypeScript is traspiled to JavaScript.

**Comment by prabhu43** [comment]
@cnishina I think your guess is right.

**Comment by cnishina** [comment]
That's good. I am closing this issue.
