### ISSUE TITLE
Is there a way to restart the webdriver in between the tests execution

### ISSUE THREAD

**Issue by cboddu** [angular/protractor#3476]
Hi ,

 I have a scenario where I need to close browser running on some port and relauch it again at the end of the script which will be used by another script(test). If the do so, I have seen an error "no such window: window was already closed" in spec 2. I think this is occurring because webdriver is not restarted. Is there a way to relaunch webdriver.

- Node Version: `4.2.2`
- Protractor Version: `3.1.1`

**Comment by cnishina** [comment]
If you close your browser window during a test, you will have to get a new browser window for your next test. You could restart browsers between tests `restartBrowserBetweenTests`.
https://github.com/angular/protractor/blob/master/lib/config.ts#L433

If you do not need to restart the browser between every test, there is also a [browser.restart api](http://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.restart).

Hopefully that helps. Anyway, since this is a support question, please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
