### ISSUE TITLE
protractor test end and browser is not closed,I have asked at stackoverflow,no result

### ISSUE THREAD

**Issue by fancyhejianyang** [angular/protractor#3544]
mine config code like below:
`exports.config={
allScriptsTimeout:15000,
specs:["e2e/testjs/*.js"]
}`
the detail website is [rdk](https://github.com/rdkmaster/rdk).
when enter npm run protractor in the terminal,test would start one by one and interrupt if current filename is 'Txxx.js'.
so I renamed it without "T" that it test from beginning to end.
---

- Node Version: `v4.2.6`
- Protractor Version: `1.1.0`
- Browser(s): `Chrome`
- Operating System and Version `Windows_NT 6.1.7601`
- Your protractor configuration file:
`exports.config = {
    //出现过11秒页面载入没完成时候，改为15秒
    allScriptsTimeout: 15000,

    specs: [
        'e2e/testjs/*.js'
    ],

    multiCapabilities: [
        // {
        //     browserName: 'firefox'
        // }, 
        {
            browserName: 'chrome'
        }
    ],

    baseUrl: 'http://localhost:8080/',

    framework: 'jasmine',

    jasmineNodeOpts: {
        defaultTimeoutInterval: 50000000
    },

    ignoreSynchronization: true,

    onPrepare: function() {
        require('jasmine-reporters');
         var capsPromise = browser.getCapabilities();
                capsPromise.then(function(caps){
                    var browserName = caps.caps_.browserName.toUpperCase();
                    var browserVersion = caps.caps_.version;
                    var prePendStr = browserName + "-" + browserVersion + "-";
                    jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter("report/e2e", true, true,prePendStr));
        });
    }
};`
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant):[](https://github.com/rdkmaster/rdk/tree/master/test)

**Comment by fancyhejianyang** [comment]
if probably,I accept email me

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

If you haven't received any answers on StackOverflow, it may be because your question needs to be clarified. It's hard to understand what the issue actually is from the example you've presented here.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
