### ISSUE TITLE
Cannot run element explorer from command line on windows

### ISSUE THREAD

**Issue by venkatpandiri** [angular/protractor#3554]
Hi there!

- Node Version: `
- Protractor Version: ```4.04
- Browser(s): ``NA
- Operating System and Version ``Windows 7
- Your protractor configuration file
#!/usr/bin/env node

console.log('Please use "protractor [configFile] [options] --elementExplorer"' +
  ' for full functionality\n');

if (process.argv.length > 3) {
  console.log('usage: elementexplorer.js [url]');
  process.exit(1);
} else if (process.argv.length === 3) {
  process.argv[2] = ('--baseUrl=' + process.argv[2]);
}

process.argv.push('--elementExplorer');
require('../built/cli.js');
- A relevant example test
**Command used**
C:\Users\pctr168443\AppData\Roaming\npm\node_modules\protractor\bin>elementexplorer http://www.google.com

- Output from running the test
Script:
C:\Users\pctr168443\AppData\Roaming\npm\node_modules\protractor\bin\elementexplorer.js
Line: 1
Char: 1
Error: Invalid character
Code: 800A03F6
Source: Microsoft JScript compilation error.
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

- Is this a breaking change? (How will this affect existing functionality)
Unable to run the elementexplorer. 
So we cannot recognize the objects.
![error](https://cloud.githubusercontent.com/assets/22181524/18519585/7aaee71a-7a72-11e6-9e8f-4de3e438f584.jpg)

Please respond.
my emial id is venkat_pandiri@genpt.com

**Comment by NickTomlin** [comment]
Hi there!

It seems like this is an issue with your environment, because of this your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
