### ISSUE TITLE
Switch tsconfig to output es6

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#3559]
Since we only support node v4+, we should be able to switch our output to es6. Try and verify.

**Comment by mgiambalvo** [comment]
FYI, I just gave this a shot. Turns out Node v4 support for ES6 is [pretty terrible](https://kangax.github.io/compat-table/es6/#node4). Specifically, Protractor breaks because of rest parameters, but it looks like there's so much missing in v4 that we won't be able to do ES6 output until we're at Node v6+

**Comment by mgiambalvo** [comment]
This has been the case on beta for a little bit now.
