### ISSUE TITLE
duplicated definition of typescript

### ISSUE THREAD

**Issue by gitawego** [angular/protractor#3571]
I just noticed, protractor installs @types/jasmine@2.2.33, @types/node@6.0.38, @types/q@0.0.30  as dependencies, it causes conflict while building, because definitions for jasmine and node are already installed in my project. 
I'm wondering what's the point of installing those definitions as dependencies, not every one using typescript. are they supposed in devDepenencies or peerDependencies ?

thanks in advance

**Comment by cnishina** [comment]
We are including ambient typings for modules that are required in dependencies. So a breakdown of these files:

- `@types/q` cannot not be removed since the typings are referenced in the `built/plugins.d.ts` file
- `@types/node` cannot not be removed since tsc needs to understand the `require` statement
   ```
> tsc

example-on-prepare/config.ts(7,19): error TS2304: Cannot find name 'require'.
node_modules/protractor/built/plugins.d.ts(1,1): error TS2688: Cannot find type definition file for 'q'.
node_modules/protractor/built/plugins.d.ts(2,20): error TS2307: Cannot find module 'q'.
   ```

- `@types/jasmine` could be removed. I am against removing `@types/jasmine` type support since we support jasmine and include it as a dependency.

However, I am curious about this issue since I was unable to reproduce it. Please share the part of your `package.json` with your dependencies and tsconfig.

**Comment by gitawego** [comment]
I use mono repo as project structure, one package depends on  another package which have the same type definition (for node and jasmine). 
I ended up installing protractor at the project root, and moving all the type definitions to the project root to avoid conflict.
