### ISSUE TITLE
Protractor tests fail on PhantomJs, but work on Chrome and Firefox

### ISSUE THREAD

**Issue by ariyDez** [angular/protractor#3604]

**Comment by ariyDez** [comment]
Hi everybody. Protractor tests fails on PhantomJs, but passed successfully on Chrome and Firefox. Did anybody had same error, and how to fix it

**Comment by NickTomlin** [comment]
Hi there!

Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck!
