### ISSUE TITLE
Making tests run on different Urls parallely

### ISSUE THREAD

**Issue by ashubham** [angular/protractor#3607]
I want to run tests in parallel. Tried to use `shardTestFiles:true` with `maxInstance:2`. But what I need is being able to specify different URLs for these tests to hit, as my application is not completely stateless.

I tried to give multiple chrome capabilities to achieve this, and identifying by name. But protractor does not shard the tests between capabilities.

Thanks for the help.

**Comment by mgiambalvo** [comment]
Hi there!

Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

That said, it sounds like you want to be running multiple Protractor instances with different config files. You can set a different baseUrl for each instance of Protractor that you start. However, I don't know all the details of your test setup, and you'll get better results asking a detailed question in StackOverflow or Gitter.

Thanks and good luck!
