### ISSUE TITLE
Pls confirm if we can use all three wait approach in the framework (implicit wait, explicit wait, thread.sleep) for automating angularJS application

### ISSUE THREAD

**Issue by bharathssubramanian** [angular/protractor#3617]
Hi there,

We are using Protractor 3.6 version in our project to automate the angularJS application. We have master angular application where many standalone angular apps been implemented as iframe.

that is we can access those apps directly hitting the SPA and also through our master integrated application.

Current Approach:
Team is using Implicit wait() with 30 seconds and static wait (may be 60 seconds) in places where implicit wait does not help.

Problem:
Could see inconsistent results every time we execute test scripts and more over execution time is considerably high.

Solution: 
We brought up explicit wait added to implicit wait and static wait which improved the consistency and reducing in execution time. 

Question: 
Is it correct using all three waits ( Implicit wait, explicit wait, thred.sleep) together in the framework. 
Note: In few navigation we had to use thread.sleep (). Both implicit wait and explicit wait is not working.

**Comment by mgiambalvo** [comment]
Hi there!

Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck!
