### ISSUE TITLE
Protractor not able to run tests for an AnguarJS app without browser.ignoreSynchronization = true

### ISSUE THREAD

**Issue by wlsf82** [angular/protractor#3625]
Bug report: Even being an AngularJS app, I need to use `browser.ignoreSynchronization = true;` in order to use Protractor to test it.
---

- Node version: `v6.3.1`
- Protractor version: `4.0.3`
- Angular version: `1`
- Browser: `Chrome 53.0.2785.143 (64-bit)`
- Operating System and version `OS X El Capitan 10.11.6 (15G1004)`
- Protractor configuration file:
```
var SpecReporter = require('./node_modules/jasmine-spec-reporter');

module.exports.config = {
  directConnect: true,
  baseUrl: 'https://appear.in/',
  specs: [
    'specs/*.spec.js'
  ],
  capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {'args': ['--use-fake-ui-for-media-stream']}
  },
  onPrepare: function() {
    jasmine.getEnv().addReporter(new SpecReporter({
      displayFailuresSummary: true,
      displayFailedSpec: true,
      displaySuiteNumber: true,
      displaySpecDuration: true
    }));
    browser.driver.manage().window().maximize();
    // browser.ignoreSynchronization = true;
  },
  jasmineNodeOpts: {
    onComplete: null,
    isVerbose: false,
    showColors: true,
    includeStackTrace: true,
    defaultTimeoutInterval: 999999,
    allScriptsTimeout: 999999
  }
};
```
- Test example:
```
var AppearInRoom = require('../page-objects/appear.in-room');
var Helper = require('../helper');
var SignUpForm = require('../page-objects/sign-up-form');
var shortid = require('../node_modules/shortid');

describe( 'Inside Appear.in room', function() {
  var appearInRoom = new AppearInRoom();
  var helper = new Helper();
  var signUpForm = new SignUpForm();

  beforeEach(function() {
    var randomRoomName = shortid.generate();

    appearInRoom.visit(randomRoomName);
    helper.sleepThreeSeconds();
  });

  it( 'try to claim room not logged in', function() {
    appearInRoom.claimButton.click();

    expect(signUpForm.signUpModalForm.isDisplayed()).toBe(true);
  });
});
```
- Output from running the test:
```
Failed: Timed out waiting for Protractor to synchronize with the page after 11 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md
``` 
- Steps to reproduce the bug:
Execute a simple test only trying to perform a `browser.get('any-room-name');` with the provided config file, where `browser.ignoreSynchronization = true;` is commented out.
Uncomment `browser.ignoreSynchronization = true;` and you will see that the test will pass.
- The URL you are running your tests against:
https://appear.in/any-room-name

**Comment by mgiambalvo** [comment]
Hi there!

I tried running `angular.getTestability($('html')).whenStable(() => { console.log('stable') });` on the URL you provided, and the whenStable() callback was never called - this is same method Protractor uses to wait for stability. It's impossible to say without seeing how your app works, but it's likely you have some polling behavior that's blocking Protractor synchronization. See the docs on [timeouts](https://github.com/angular/protractor/blob/master/docs/timeouts.md) for more details.

Since it involves something particular to your application or test environment, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck!
