### ISSUE TITLE
Error forwarding the request Read timed out [chrome #11-12] at WebDriverError ONLY on the last browser instance.

### ISSUE THREAD

**Issue by jahnavi310** [angular/protractor#3631]
I keep on running into this issue whenever the last test is being run.
We run our protractor tests on a selenium grid that is fired up via docker and kicked off whenever a commit is made.

But this is the super weird thing:
Sometimes all the tests pass flawlessly and sometimes any test that is being run on the last firefox or chrome instance just hangs and sits there and eventually throws the following error:

```
WebDriverError: Error forwarding the new session Error forwarding the request Read timed out [chrome #11-12]     at WebDriverError
```
The test is random because we have ```shardTestFiles: true,``` and we have ```max instances``` set to ```10```

Also due the fact that this is being run on the grid it is impossible to figure out whether there is something wrong with the test or not, because the same test would pass if it is not the one randomly picked to run on the last browser instance. 
I am also not too sure if this is a protractor issue or a docker-selenium issue.
Is anyone else experiencing the same issue?

**Comment by mgiambalvo** [comment]
Hi there!

That error message is definitely a networking related error from Selenium Grid, so I don't think this is a Protractor issue. Because it involves usage and your test environment, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck!
