### ISSUE TITLE
ECONNREFUSED connect ECONNREFUSED 127.0.0.1:62144 When I run the tests

### ISSUE THREAD

**Issue by djom20** [angular/protractor#3667]
When I was running the tests I had this issue where somehow protractor lost a connection with selenium server. I never ran this "webdriver-manager update" command for run the tests.

![image](https://cloud.githubusercontent.com/assets/1834808/19702034/92b68522-9ac3-11e6-8894-5dcdfbd00ce5.png)

**Comment by mgiambalvo** [comment]
Hi there!

Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

That said, it does look like maybe you need to run `webdriver-manager update` to get the latest chromedriver. 

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck!

**Comment by djom20** [comment]
I have used the issue template to indicate this case. I think that is a issue in your updates because somehow the issue is in webdriver.js that is use for protractor.
