### ISSUE TITLE
Protractor throws an exception for Angular 2 app when browser.ignoreSynchronization = false

### ISSUE THREAD

**Issue by maazzali** [angular/protractor#3668]
I have been writing e2e tests for my angular 2 app and i am facing a few issues. I have tried to fix them using `browser.ignoreSynchronization = true;` and `useAllAngular2AppRoots: true` for my Angular2 App but I have to add static waits for my angular app to load properly which is not a good approach in longer run. 

When i use `browser.ignoreSynchronization = false;` and `useAllAngular2AppRoots: true;` in my config file, the tests hang and exception is thrown. I have pasted my config file and screen shots below. 

Config File:
`
'use strict';

const config = {
    framework: 'jasmine2',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    //allScriptsTimeout: 110000,
    jasmineNodeOpts: {
        showTiming: true,
        showColors: true,
        //defaultTimeoutInterval: 150000,
    },
    multiCapabilities: [{
        browserName: 'chrome'
    }],

    onPrepare: function() {
        browser.ignoreSynchronization = false;
    },
    specs: [
        'test/specs/adminDrivers/addNewDriver.spec.js'
    ],

    useAllAngular2AppRoots: true
}
exports.config = config;`

Protractor console:

![screen shot 2016-10-25 at 3 56 57 pm](https://cloud.githubusercontent.com/assets/22958109/19717040/3da93c22-9b78-11e6-936b-4abacfe51144.png)
![screen shot 2016-10-26 at 12 08 52 pm](https://cloud.githubusercontent.com/assets/22958109/19717050/47303b06-9b78-11e6-8e1d-5c99cfda0c5d.png)

Webdriver Console:

![screen shot 2016-10-26 at 12 20 49 pm](https://cloud.githubusercontent.com/assets/22958109/19717578/c582ae42-9b7a-11e6-8e32-910a8910bb78.png)

Your help would be much appreciated. Let me know if you need more data on this issue.

- Node Version: `6.2.0`
- Protractor Version: `4.0.9`
- Angular Version: `2`
- Browser(s): `Chrome`
- Operating System and Version `MAC OS Sierra`

**Comment by cnishina** [comment]
It appears that you have two tests that are passing... which does not appear specific to `browser.ignoreSynchronization`. Please review "[Waiting for Page Synchronization](http://www.protractortest.org/#/timeouts)".

Closing this since it appears to be a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by mgiambalvo** [comment]
In Angular 2, you'll need to use runOutsideAngular for any async tasks you don't want Protractor to block on. Please see the discussion in #3349 for details.
