### ISSUE TITLE
Custom Framework using details

### ISSUE THREAD

**Issue by aliemrahpekesen** [angular/protractor#3705]
Hi Team!
Actually I could not find a direct contact for thsi issue that is why I create an issue.

I need more explanation about the custom framework for testing purposes but links are broken at the bottom of the "Custom Framework" page on documentation. Could you please check and fix it? Or could you please let me know if you have another reference for that topic?

![resim](https://cloud.githubusercontent.com/assets/4151986/20051224/fd1db6ae-a4de-11e6-96c2-75b9c43f2811.png)

Thanks in advance.

**Comment by igniteram** [comment]
@aliemrahpekesen This issue has been already logged https://github.com/angular/protractor/issues/3671 and  should be fixed with https://github.com/angular/protractor/pull/3674. You could access the custom frameworks page directly for your reference. Please find the raw link for that : https://github.com/angular/protractor/blob/master/lib/frameworks/README.md#custom-frameworks

**Comment by aliemrahpekesen** [comment]
Thank you @igniteram , I'm closing the issue as well.
