### ISSUE TITLE
Upgrading Protractor to >4.0.5  causes installation issue

### ISSUE THREAD

**Issue by thyagab** [angular/protractor#3736]
Bug report
---

- Node Version: `node v7.0.0`
- Protractor Version: `~4.0.5`
- Browser(s): `Chrome`
- Operating System and Version `Mac`

Installing protractor with version above 4.0.5 makes install fail with 
npm ERR! code E403

npm ERR! user xyz is not allowed to access package @types/q : @types/q

Everytime I try to install, it is a different package permission issue.
@types/node : @types/node
@types/selenium-webdriver : @types/selenium-webdriver

**Comment by NickTomlin** [comment]
Hi there!

This sounds like an issue with your system / environment and not an issue with Protractor itself.

Because of this, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
