### ISSUE TITLE
breaking VSTS build

### ISSUE THREAD

**Issue by ialex90** [angular/protractor#3754]
Hi there!

I've been having problems in my build on VSTS after I added protactor. I created a question on SO that could give you all the details, but basically, it was complaining about node-sass dependency and not locally but on VSTS.

Hope this is useful for you guys,

[Error detailed](https://stackoverflow.com/questions/40675155/npm-install-fails-on-vsts-not-locally/40677119#40677119)

**Comment by NickTomlin** [comment]
From reading the StackOverflow I don't understand what the actual issue is. Could you add more detail (and follow the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE)? 

If this is something that Protractor is doing wrong then we should fix it; my gut tells me this may be an issue with VSTS itself (and therefore outside the scope of what we can do in the issue thread here). Thanks!

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this. If you believe this is an actual issue with Protractor please open a new issue using the  [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE).

Thanks!
