### ISSUE TITLE
Angular 2 E2E Test cases runs on local system but not on server?

### ISSUE THREAD

**Issue by Bhushan001** [angular/protractor#3759]
I have deployed my angular2 app using ng build --prod.

Now When I Test My app using protractor in local system, all my test cases run successfully i.e. links are being clicked, users are getting created & deleted.

But When I deployed the code on server , few testcases run successfully like creating & deleting users but few test cases like drag & drop, opening modal always give time out.

> asynchronous script timeout: result was not received in 60 seconds

After building angular2 app , I am using express to host the app.

Configurations:

Local: Windows 7 
Server : Windows server 2012 R2 Standard Build

Are there any extra configurations required?

Thanks

**Comment by cnishina** [comment]
I just created a starting app with the angular-cli, and ran `ng build --prod`. When serving the `dist` folder, it appears to have `window.getAllAngularTestability`. Since this works locally and not in production, we recommend checking out our documentation on timeouts. http://www.protractortest.org/#/timeouts

Please ask additional support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
