### ISSUE TITLE
@types/angular-protractor for managing typings

### ISSUE THREAD

**Issue by pumano** [angular/protractor#3776]
Feature Request
---

- Reasons for adopting new feature
_I would to request migrate from "old" typings from definitely typed angular-protractor to something @types/angular-protractor for better managing via npm_

- Is this a breaking change? (How will this affect existing functionality)
_no_

**Comment by cnishina** [comment]
Protractor has type support and does not need @types/protractor. The PR that removed it from types-2.0 branch is https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12482. Anyway, since we have types support, we have several examples:

https://github.com/angular/protractor/tree/master/exampleTypescript
https://github.com/angular/protractor-cookbook/tree/master/protractor-typescript

Closing this issue since the feature request has been resolved a while ago. 

Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
