### ISSUE TITLE
Bug - browser.d.ts isElementPresent using ProtractorBy instead of Locator

### ISSUE THREAD

**Issue by matenwego** [angular/protractor#3864]
Just started converting our older Protractor tests to start using TypeScript and I noticed I was getting errors when using `browser.isElementPresent(by.css('example-css'))` saying that it should be a type of `ProtractorBy`.

I'm pretty sure this is supposed to be `Locator` like it is in the element.d.ts file.

I'm using protractor version 4.0.13. And looking at 4.0.14 doesn't look like that was updated to match either. 

If I'm wrong please let me know what I should be using for `browser.isElementPresent` or should I just abstain from using that and using `element(by.id('parent-element')).isElementPresent(by.css('example-css')`. Going to continue to see if I can actually get the `element(by.id('parent-element')).isElementPresent(by.css('example-css')` working.

**Comment by sjelin** [comment]
1) That does sound wrong
2) When investigating this bug, I discovered that `browser.isElementPresent` was broken for raw `WebDriver` elements (e.g. `browser.isElementPresent(browser.driver.findElemet(by.id('my-elem')))` would fail).  It will be fixed with #3871, which will also fix your typing issue.

**Comment by matenwego** [comment]
Awesome thank you! 

For now I did end up using a `element(by.tagName('body')).isElementPresent(by.css('example'))` in case anyone encounters this issue before the fix is in.
