### ISSUE TITLE
on IE8, sometimes report A Jasmine spec timed out. Resetting the WebDriver Control Flow.

### ISSUE THREAD

**Issue by andonr** [angular/protractor#3874]
- Protractor Version: `4.0.12 and selenuim-server-standalone-2.53.1.jar`
- Browser(s): `IE8`
- Operating System and Version `Win 7`
Hi, I meet some problem when upgrade protractor from 1.5.0 to 4.0.12
We have some cases like this
```
it('001. Click Plotting ---IE8',function(){
    // get a url
    browser.get('x.html');
    // click a plotting node
    browser.actions().click($('#xx')).perform();
    //move mouse to some place to click(to drow the node)
    browser.actions().mouseMove(
        {
            x:500,
            y:-10
        }).click().perform();
    // expect the node exits
    expect($$('#xxx').count()).toBe(1);
});
```
I connected a remote server(Windows 7)to build the environment(jenkins, test server, protractor), jenkins can automatically start the test server(Tomcat) and excute protractor on the remote server.
The problem is that when jenkins excute protractor and **I disconnect the remote server**, it will report the following error:
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
Error: Timeout - Async callback was not invoked within timeout specified by jasmine. DEFAULT_TIMEOUT_INTERVAL

And all the following cases report it
[31mF [0m A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF [0m A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF [0m A Jasmine spec timed out. Resetting the WebDriver Control Flow.
...
[31mF [0m A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF [0m A Jasmine spec timed out. Resetting the WebDriver Control Flow.

And when I reconnect the remote server,  **there are two iexplorer.exe.** 

It is OK when I use protractor 1.5.0 and selenuim-server-standalone-2.44.0.jar

**Comment by cnishina** [comment]
Closing this issue since we support / try to support the latest browsers. Although I am closing this issue, I have a few thoughts on this:

**Option 1: try to use old binaries with latest Protractor **

You could download the binaries that were in protractor@1.5.0. This might be work but may not due to the selenium-webdriver client / selenium standalone server mismatch. Unfortunately, I cannot verify that this will work since I have IE11 installed.

```
webdriver-manager update --versions.standalone 2.44.0 --ie32 --versions.ie 2.44.0
webdriver-manager start --versions.standalone 2.44.0 --ie32 --versions.ie 2.44.0
```

**Option 2: continue using Protractor 1.5.0 and selenium-server-standalone-2.44.0.jar**

The tests work, maybe do not change the Protractor version for this suite of tests.

**Option 3: upgrade to IE11 since this is the only version of IE Microsoft is supporting**

See [End of IE Support](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support).
