### ISSUE TITLE
Wrap `useAllAngular2AppRoots` and `rootEl` in control flow

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#3905]
Like we did for `ignoreSynchronization` (see `beta` branch if we haven't merged `beta` into `master` yet).  @mgiambalvo I'm assigning you, since it seems blocking-proxy related.  This will be a breaking change, so we might want to hold off on the 5.0 release until we do this?

**Comment by mgiambalvo** [comment]
This isn't actually necessary - rootEl is read in the waitForAngular call outside of the control flow, so the current behavior is correct. 

The Blocking Proxy integration will need to change so that rootEl can be updated at the right place in the control flow, which will come with https://github.com/angular/blocking-proxy/issues/16

**Comment by sjelin** [comment]
As per our conversation offline, I actually would like this to be a function set in the control flow anyway for use cases like the following:

```ts
browser.setRootEl('root1');
browser.get('/ng1_page').then(() => {
  browser.doStuffWithRoot1();
});
browser.setRootEl('root2');
```

This use case is strange, but would be expected behavior.  Also, I'm just generally bothered by the idea that `ignoreSynchronization` is being replaced with a function and `rootEl` is not.  They're similar flags and should be set/used the same way.

**Comment by sjelin** [comment]
Sorry, closing in favor of https://github.com/angular/protractor/issues/3947
