### ISSUE TITLE
Update jasmine dependency to allow users disable default reporter

### ISSUE THREAD

**Issue by xkamil** [angular/protractor#3916]
Please update jasmine dependency to 2.5.2
It allows clearing default reporters so adding custom one won't show duplicated reports in console.

**Comment by cnishina** [comment]
We are waiting a new release from jasmine. The previous discussion starts here. https://github.com/angular/protractor/issues/3811. Created a new issue to jasmine-npm since the hot fix is not out yet. See:  https://github.com/jasmine/jasmine-npm/issues/102.

Leaving this issue open since the duplicate version was previously closed.
