### ISSUE TITLE
Safari 10 failing with the latest protractor

### ISSUE THREAD

**Issue by shavo007** [angular/protractor#3968]
Bug report
---

- Node Version: `6.9.1`
- Protractor Version: `5.0.0`
- Angular Version: `1.5`
- Browser(s): `Safari 10.0.2`
- Operating System and Version `Mac OS X 10.11`

Now when I run protractor against safari i get the error:

  0.006s] [safaridriver.client] Connecting to SafariDriver browser extension...
[  0.016s] [safaridriver.client] This will fail if you have not installed the latest SafariDriver extension from
http://selenium-release.storage.googleapis.com/index.html
[  0.017s] [safaridriver.client] Extension logs may be viewed by clicking the Selenium [✓] button on the Safari toolbar

I read that safari has the web driver built in now. Thats why I find this message confusing!

Thanks,
Shane.

**Comment by mgiambalvo** [comment]
Although Protractor is updated to the Selenium 3.0 client, we're still using version 2.53 of the Selenium standalone server by default which uses the old Safari extension, which is why you're seeing that message. We'd like to upgrade to Selenium 3 for the standalone server soon, but there's a bug in 3.0.1 so we're waiting on a new release. 

If you'd like to try it out early, you could do 

```
webdriver-manager update --versions.standalone 3.0.1
webdriver-manager start --versions.standalone 3.0.1
```

and I think Safari 10 should work. But keep in mind we don't fully support this quite yet.

**Comment by shavo007** [comment]
Hi @mgiambalvo ,

I appreciate the response. But why close the issue until it is resolved in the future release?

That way other people can find this issue easier and be able to follow when it is resolved in a later milestone.

Thanks,
Shane.
