### ISSUE TITLE
jasmine-reporters

### ISSUE THREAD

**Issue by fernandogutierrez** [angular/protractor#3975]
I everybody, I am using the following configuration 

jasmine.getEnv().addReporter(
    new reporters.JUnitXmlReporter('../reports/junit-reports', true, true));

The problem is that the xml result is always generated on the **root file**. I want to generate the xml reports on the reports folder.

**Comment by NickTomlin** [comment]
Hi there!

Because it deals with usage of a custom reporter, and not an issue with Protractor itself, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
