### ISSUE TITLE
Protractor CLI rejects `cucumberOpts` as invalid

### ISSUE THREAD

**Issue by jan-molak** [angular/protractor#3978]
Hello there!

It looks like the whitelist defined in the [`cli.ts`](https://github.com/angular/protractor/blob/cd9182618c768ccd2375e187fd85396853bd10de/lib/cli.ts#L35) rejects the `cucumberOpts` key which the [`protractor-cucumber-framework` uses](https://github.com/mattfritz/protractor-cucumber-framework).

- Node Version: `6.9.4`
- Protractor Version: `5.0.0`

Running protractor with the below config file results in this output:

```
Error: Found extra flags: cucumberOpts
```

```javascript
exports.config = {
    seleniumServerJar: path.resolve(node_modules, 'protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar'),
        
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    specs: [ 'features/**/*.feature' ],
    cucumberOpts: {
        require:    [
            'features/**/*.ts'
        ],
        format:     'pretty',
        compiler:   'ts:ts-node/register',
    }
};
```

I guess there are several ways to resolve this issue:

1. run the protractor/cucumber combo with a `--disableChecks` switch (that's more of a workaround, though)
2. change the whitelist to include `cucumberOpts`, which allows people to run their cucumber tests same as they used to, but requires the Protractor Team to amend the whitelist whenever a new framework comes along or changes the way it's configured (which breaks "half of SOLID" ;-))
3. change the CLI to only perform the checks on keys recognised and supported by Protractor, ignoring any additional keys, which to me seems the most sensible approach.

Looking forward to hearing your thoughts!
Jan

**Comment by mgiambalvo** [comment]
The goal of the flag checks is to help catch when people misspell a flag name, so ignoring additional keys would defeat the purpose. However, there should be a way for protractor-cucumber-framework to add to the whitelist, we can work on that.

**Comment by jan-molak** [comment]
I guess there could be an API to allow plugin authors to register additional commands perhaps?

**Comment by igniteram** [comment]
@jan-molak This is strange you should not face this issue. Are you sure you are not passing `cucumberOpts` flag through command line?

As you see protractor's config interface was recently updated to support any optional key i.e. it allows us to use `cucumberOpts` with minimal dependencies. Coming to new changes to protractor's CLI, I agree with @mgiambalvo ignoring additional flags would not help users know the protractor's actual cli commands. 
If you want to use your custom flag you would  have to use `--disableChecks` flag.

But since you are passing `cucumberOpts` in config itself you should not get this issue. I have been using this setup and did not face any issues.

For your reference also pls check **protractor-cookbook** [protractor-typescript-cucumber example](https://github.com/angular/protractor-cookbook/tree/master/protractor-typescript-cucumber) which was recently upgraded to Protractor 5.0 with no issues.

**Comment by jan-molak** [comment]
Thanks @igniteram, I didn't realise the behaviour is different when the option is specified on the command line.

Now that you pointed that out it might be relevant that I'm doing both:
- I set the `cucumberOpts` in the protractor config file to register `ts-node`
- I pass the `cucumberOpts.name` flag to run a specific test

A complete example to demonstrate the behaviour I'm seeing would be this:

```typescript
// protractor.conf.js

exports.config = {
    seleniumServerJar: path.resolve(node_modules, 'protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar'),
        
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    specs: [ 'features/**/*.feature' ],
    cucumberOpts: {
        require:    [
            'features/**/*.ts'
        ],
        format:     'pretty',
        compiler:   'ts:ts-node/register',
    }
};
```

```json
// package.json

{
  // ...
  "scripts": {
    "pree2e": "npm run webdriver:update -- --standalone",
    "e2e": "protractor ./protractor.conf.js",
    "e2e-single": "protractor ./protractor.conf.js --cucumberOpts.name",
    "webdriver-manager": "webdriver-manager",
    "webdriver:update": "npm run webdriver-manager update",
    // ...
  }
}
```

Now, although running `npm run e2e` (without specifying the `cucumberOpts.name` on the command line) works fine, running the `e2e-single` results in an error:

```
npm run e2e-single "Subtract two numbers"

/some/path/node_modules/protractor/built/cli.js:172
        throw new Error('Found extra flags: ' + unknownKeys.join(', '));
        ^

Error: Found extra flags: cucumberOpts
    at Object.<anonymous> (/some/path/node_modules/protractor/built/cli.js:172:15)
```

**Comment by igniteram** [comment]
@jan-molak This is expected behaviour! since protractor 5.0, there is a check for unidentified command line flags, i.e. it would throw the above error if you use any flag which is not part of protractor's command line options which can be found [here](https://github.com/angular/protractor/blob/master/lib/cli.ts#L111) .

You could see that `cucumberOpts` doesn't belong to the list of identified command line flags in protractor, so in case you are passing this as a custom flag, as I said earlier you have to use `--disableChecks` flag along with this. So in your case you would have to do this- 

```
"e2e-single": "protractor ./protractor.conf.js --cucumberOpts.name --disableChecks"
```

Now your script should run successfully, The job of `disableChecks` flags is to ignore any unidentified flags just as it was working in the earlier versions.

 In the next version of protractor you would get a better error message for these scenarios. I hope this clarifies your query!

**Comment by jan-molak** [comment]
Thank you for getting back to me so quickly!

If I may make a suggestion, perhaps allowing plugin authors to register additional flags for the CLI and configuration options for the `protractor.conf.js` via the [plugin API](https://github.com/angular/protractor/blob/master/docs/plugins.md#writing-plugins) might be a nice way of avoiding having to specify the `--disableChecks`, which, granted, gets rid of the warning, but also disables other, potentially useful checks?

This way the white list we discussed earlier could stay as it is, but optionally get expanded via plugins.

Looking forward to hearing your thoughts!

**Comment by igniteram** [comment]
Expanding the white list via plugin api should be a viable option in future.

 @cnishina what are your thoughts on it? you are the right person here :smile:

**Comment by mgiambalvo** [comment]
There might be a better way to do this that we could do in the future. In the meantime, #3994 will allow frameworks to specify extra flags that they accept in the call to `runTestPreparer()`.

This should go out in Protractor 5.1

**Comment by jan-molak** [comment]
Awesome, thanks for your help @mgiambalvo 👍

**Comment by AlexMarchini** [comment]
I use the default jasmine framework, but I define additional CLI options in my project, such as account options for the app I'm running tests against. These get picked up as unknown flags. 

Is there currently any way for me to plug these into the call to runTestPreparer to get rid of the warning?

**Comment by pawelus** [comment]
I'm facing the same thing as @AlexMarchini 
We pass a bunch of parameters from our CI jobs - things like environment to run on, build numbers, etc.

It would be good to have a way to tell protractor those are to be expected.

**Comment by igniteram** [comment]
This feature is already available in protractor, Since v5.1.1 you have 2 options
* Either set `disableChecks` option to `true` which would disable the console options check. i.e. Any extra flag you pass it would ignore.

Please check the [config.ts](https://github.com/angular/protractor/blob/master/lib/config.ts#L628) interface on how this could be set.

* You can specify your custom flags in `unknownFlags` option in config file, you can pass in your flags as array of strings.

it is also available in [config.ts](https://github.com/angular/protractor/blob/master/lib/config.ts#L665)
I know there is a lack of documentation on this, If you have time please feel free to raise a PR. cheers!

**Comment by djom20** [comment]
I have the same issue but my problem is that I have a lot of arguments in the cucumberOpts something like that:

```
cucumberOpts: {
        require: ['step_definitions/**/*_steps.js', 'support/*.js'],
        format: 'pretty', // format: 'json',
        tags: ['@complete', '~@displays_date_question_results', '~@analyzingSurveyExpression', '~@stressTests', '~@widgets', '~@assuring', '~@todo', '~@tests', '~@noRunLocal'],
        keepAlive: false
    }
```

is possible to pass all those params by the cli at the same time?

**Comment by djom20** [comment]
I tried to run this:

`protractor cucumber_conf.js --cucumberOpts.require="step_definitions/**/*_steps.js" --cucumberOpts.tags="@surveyMakingImagesDesktopSmokeTest" --cucumberOpts.tags="~@todo" --cucumberOpts.tags="~@noRunLocal" --disableChecks`

but the steps were not found by protractor.

**Comment by drew-royster** [comment]
Where can I adjust the default cucumber timeout?  I haven't found a list of all available cucumberOpts.

**Comment by wswebcreation** [comment]
@drew-royster 

You can't adjust it through the command line. See the CucumberJS [timeouts](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md)-docs to adjust this.

Maybe if you create something custom you can add it like for example using [yargs](https://www.npmjs.com/package/yargs) and do something like this

```
// You CucumberJS timeout file that you load through your `cucumberOpts.require` in your
// Protractor conf
var {defineSupportCode} = require('cucumber');
// Add yargs
var argv = require('yargs').argv

defineSupportCode(function({setDefaultTimeout}) {
  // Then add the property `defaultTimeout` that will be passed through the cli with
  // npm run protractor -- --defaultTimeout=60000
  setDefaultTimeout(argv.defaultTimeout);
});
```
