### ISSUE TITLE
running single scenario from feature file

### ISSUE THREAD

**Issue by Galileo1** [angular/protractor#3984]
- Node Version: 4.5.0
- Protractor Version: 4.0.1
- Angular Version: 1.59
- Browser(s): Chrome
- framework: Custom
- framework Path: 'protractor-cucumber-framework'

Problem Statement - Running single scenario from a feature file. 
Trying to run single scenario by using expression from command line. This is also mentioned in #2445. 

`--spec=['\features\**\Feature Editor.feature:12']`

I am not really sure whether protractor is supporting it or not as it is cucumber related feature. The config Parser doesn't show logic that it is supported but Just wanted to confirm that from you guys. If this is not supported then is there any other way that we can achieve running targeted scenario (apart from tagging). 

Or is there any plan in future to support this feature in protractor?

Can you please help? Stack overflow refers back to issue #2445 and cucumber-js documentation suggests the same way for doing this.

**Comment by NickTomlin** [comment]
Hi there!

Because it is about a 3rd party framework, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by Galileo1** [comment]
for those who have been seeking the answer for this question passing cucumberOpts.name=['name of scenario'] as command line argument will solve this issue.
