### ISSUE TITLE
PhantomJS could not find this element “driver.findElement(By.name(”q")) selenium web driver Java

### ISSUE THREAD

**Issue by BhavanaP** [angular/protractor#3987]
Hi there!

I have read the previous issues related to this. So i am posting this hoping you could help in this. PhantomJS could not find this element “driver.findElement(By.name(”q")) 

1) My window size is set to new Dimension(1280, 1024)
2) Tried with id too driver.findElement(By.id("lst-ib") 

But PhantomJS not able to find the driver.findElement(By.name(”q")) in the below code

               driver.get("https://www.google.com");
	       driver.manage().window().setSize(new Dimension(1280, 1024));		
		// find the text input element by its name
		WebElement element = driver.findElement(By.name("q"));

an error is thrown that it could not find the element name='q'.

**Comment by NickTomlin** [comment]
Hi there!

Because your question involves usage, and PhantomJS is not officially supported, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
