### ISSUE TITLE
TypeScript: ElementArrayFinder::filter uses `wdpromise` instead of a standard `Promise`, breaking backwards compatibility

### ISSUE THREAD

**Issue by jan-molak** [angular/protractor#4049]
Protractor `5.1.0`
File: [element.ts:232](https://github.com/angular/protractor/blob/f1971b72a6955889fba247906b173af6c73a87f5/lib/element.ts#L232)

---

Hey @sjelin!

It seems like the change in the signature of the `ElementArrayFinder::filter` introduced in commit [995b1466](https://github.com/angular/protractor/commit/995b1466d8a9d89be887e6e87c59a0bfe61c2bd4), breaks some of the more advanced filter functions.

Changing the definition of the `filterFn` from

```typescript
(element: ElementFinder, index?: number) => boolean | wdpromise.Promise<boolean>
```
to 
```typescript
(element: ElementFinder, index?: number) => boolean | Promise<boolean>
```
or even 
```typescript
(element: ElementFinder, index?: number) => boolean | PromiseLike<boolean>
``` 
should fix the problem.

---

## The problem in more detail.

From what I can see, the signature has changed from:

```typescript
filter(
    filterFn: (element: ElementFinder, index?: number) => any
): ElementArrayFinder
```

to

```typescript
filter(
    filterFn: (element: ElementFinder, index?: number) => boolean | wdpromise.Promise<boolean>
): ElementArrayFinder
```

This breaks backwards compatibility and forces any existing `filterFn`s to now return a `wdpromise.Promise`, rather than a standard `Promise` or even better - a `PromiseLike`.

One example of such `filterFn`, coming from the [Serenity/JS code base](https://github.com/jan-molak/serenity-js/blob/dca8be0aee478b9943cb97f8e701d0a3cdf3ccd3/src/serenity-protractor/screenplay/interactions/select.ts#L29), could look like this:

```typescript
const hasRequiredText      = (option: ElementFinder) => option.getText().then(value => !!~this.values.indexOf(value)),
      isAlreadySelected    = (option: ElementFinder) => option.isSelected(),
      ensureOnlyOneApplies = (list: boolean[]) => list.filter(_ => _ === true).length === 1,
      select               = (option: ElementFinder) => option.click();

const optionsToClick = (option: ElementFinder) => Promise.all([
        hasRequiredText(option),
        isAlreadySelected(option),
    ])
    .then(ensureOnlyOneApplies);

element(by.css('select'))
    .all(by.css('option'))
    .filter(optionsToClick)            // <- here's the trouble
    .each(select);
```

As you can see, the signature of the `optionsToClick` function above is

```typescript
(element: ElementFinder) => Promise<boolean>
```

which, even though working perfectly fine with Protractor 5.0.0, no longer works with 5.1.0.

Looking forward to hearing your thoughts!

Best,
Jan

**Comment by sjelin** [comment]
Sorry for the slow response, I've been very busy wrapping things up before I transfer to a new team.

Here's the thing: you really *should* be returning a `wdpromise.Promise`.  The Serenity/JS example you've shown me is actually wrong (they should be using `protractor.promise.all` instead of `Promise.all`).  Using a different promise implementation could cause control flow problems and introduce race conditions.  So a type error is appropriate.

That said, [`@types/selenium-webdriver`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/selenium-webdriver) needs to publish types for `selenium-webdriver@^3.0.0`, which should include the option to use promise-likes in these situations when the control flow is disabled.

**Comment by jan-molak** [comment]
No worries, that's a shocker, I'm sad to see you go! Hope the new team is fun :-)

To address the issue you've raised - I don't think using `Promise.all` is a problem there, since Serenity/JS wraps the whole promise chain into a `webdriver.Promise` anyway, so it's executed within the control flow.

Using standard promises also allows for chaining webdriver and es6 promise-based library calls together (which I don't believe need to be themselves wrapped in webdriver.promises, since a standard promise chained onto a webdriver promise will not be executed until the webdriver one is completed from what I've witnessed). But if I missed anything, please do let me know! :-)

On your second point - is there any ticket related to [@types/selenium-webdriver](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/selenium-webdriver) publishing the changes you mentioned? Do I understand correctly that they've already been implemented and only need to be published?

Thanks!
Jan

**Comment by sjelin** [comment]
I've had issues with native promises wrapped in webdriver promises in the past.  From Protractor's point of view, it's best to just have this be a type error for now.

The `selenium-webdriver@^3.0.0` is implemented, but its types are not.  The selenium team doesn't maintain the `@types`, although the comments in [their source code](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver) have very clear jsdoc types.  If you want to be a *hero* you could update the `@types` for `selenium-webdriver` yourself.

**Comment by massimocode** [comment]
I'm not so convinced that sticking with the wdpromise.Promise is not the best course of action. I've raised an issue https://github.com/angular/protractor/issues/4058 which shows that async/await is broken because of this. We've had to force version `5.0.0` to prevent this breaking change.

**Comment by jan-molak** [comment]
I've pinned [Serenity/JS](https://github.com/jan-molak/serenity-js/) peer dependency on Protractor to 5.0.0 as well, until I have some time to investigate @sjelin's suggestion further. 

@massimocode - I'm curious, how does the issue affect async/await?

**Comment by sjelin** [comment]
Indeed, async/await returns a native promise.

I want to be clear: A bug I encountered while trying to support `async`/`await` was actually the motivation behind sticker types for promises: https://github.com/SeleniumHQ/selenium/issues/3037

Don't have to pin yourself to 5.0.0 to get around this problem - you could just use type casting.  But I want to be clear: you *are* playing with fire here.  For instance, if you were to do:

```ts
els.map(async function clickFooBars(el: ElementFinder): boolean {
  if (await el.getAttribute('foo') == 'bar') {
    // Because of the native promise generated by async/await, we are now in a separate
    // control flow task
    el.click();
  }
}).each((el) {
  expect(el).toHaveBeenClicked(); // Race condition here
})
```

Obviously that's `map` and not `filter`, and you shouldn't be doing `click`s in filters, but people do all sorts of things.

You could argue that the issue is just that `clickFooBars` should have done `await el.click();`.    In some sense, you'd be right.  Because Protractor doesn't internally rely on the control flow working properly, and because at the end of `filter` the final results are put back on the control flow, as long as your filter function chains all its promises together, you can ***probably*** get away with native promises.  But you're relying on the specifics of Protractor's internal implementation here.  The only 100% safe way to make sure you're not breaking the control flow is to stick to webdriver promises.

**Comment by jan-molak** [comment]
Thanks for the link to SeleniumHQ/selenium#3037, @sjelin. That's a very interesting conversation indeed!

After further investigation I decided to provide the `filter` method with a `protractor.promise.all`, as per your suggestion. That makes perfect sense as the input fed into `filter` is the result of a `getText` and `isSelected`, which both return a `webdriver.promise`, so the whole chain remains consistent.
Since the change only had to be applied in the local scope, I could also avoid leaking the `webdriver.promise` abstraction.

I think that your observations from SeleniumHQ/selenium#3037 make perfect sense - mixing up webdriver and native promises can be problematic. However, since in Serenity/JS we chain the _scheduling_ of a native promise, rather than the already started promise, onto a `webdriver.promise` we can get away without synchronisation problems.

Thanks for your help!

**Comment by sjelin** [comment]
It's true, Protractor is perhaps a little overly strict here.  But if you're using native promises, you should really turn the control flow off.  And with the control flow off, `ManagedPromise` will be replaced with native promises.  `@types/selenium-webdriver` should theoretically react to the control flow being turned off, though that's not implemented yet.  Once that's implemented, you'll only run into this problem if the control flow is enabled but you're returning a non-`ManagedPromise` to `filter`, which really implies that you're mixing sync/async styles.

**Comment by massimocode** [comment]
@sjelin I noticed a missing await in the example code you posted on this comment https://github.com/angular/protractor/issues/4049#issuecomment-278809243

I think you meant to do `await el.click()` because click returns a promise that indicates the click has been performed.

**Comment by Xotabu4** [comment]
Any updates on this? Looking for a way to use `.filter()` with async/awaits, but seems it is a bit tricky to wrap async function to return wdpromise instead of native promise.
