### ISSUE TITLE
get() method is not working with browser.driver.findElements when running a test for non angular site

### ISSUE THREAD

**Issue by samsul-kabir** [angular/protractor#4104]
Hi there!

I am having this issue while I am trying to work with a non-angularjs site. When I am trying to access an element using 

`browser.driver.findElements(by.css(".menu")).get(0).click();`

This is giving me this error:

`Failed: browser.driver.findElements(...).get is not a function
  Stack:
    TypeError: browser.driver.findElements(...).get is not a function
        at Object.<anonymous> (/Users/skabir/Documents/protractor-room5/test/nav.js:24:54)
        at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:102:25
        at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at controlFlowExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:87:18)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
`

Any idea why is this happening?

Thanks

**Comment by NickTomlin** [comment]
This is happening because you are attempting to mix protractor and webdriver methods. `get` is a method of [ElementArrayFinder](https://github.com/angular/protractor/blob/master/lib/element.ts#L82) which is returned by protractor locators. 

`browser.driver` methods like [`findElements`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/ie_exports_Driver.html#findElements) use the underlying webdriver implementation, and return a promise that resolves to a `WebElement` (or in this case, an array of `WebElement`s). The promise has no `get` method, hence the `.get is not a function` error.

Since you are attempting to select the first available element with the `.menu` class, `browser.driver.findElement` should be sufficient.

If you are still having issues, please [ask a question on StackOverflow with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by samsul-kabir** [comment]
Thanks Nick. The tip was helpful and I made it working by following this.

browser.driver.findElements(by.css(".menu")).then(function(elem){
elem[0].click();
});
