### ISSUE TITLE
Webdriver-manager start does not work when connected to VPN, unhandled error message is displayed

### ISSUE THREAD

**Issue by TwinkleA** [angular/protractor#4135]
I trying to run this command when connected to VPN,

webdriver-manager start

but below error message is displayed 
![webdriver-manager start does not work when connected to vpn](https://cloud.githubusercontent.com/assets/18376082/23606159/9290ea2c-0285-11e7-8626-4f2fbca68ec5.PNG)

**Comment by NickTomlin** [comment]
If you are behind a VPN that blocks access `googleapis` you'll need to use a proxy via the `HTTP_PROXY` or `HTTPS_PROXY` environment variables.

I think this is best handled as a troubleshooting question raised on Stack Overflow since it's about an issue with your VPN (not all VPNs do this). I'm going to close this now, thanks 😄
