### ISSUE TITLE
Browser.refresh function does not keep Referer and other header parameters.

### ISSUE THREAD

**Issue by mmikirtumov** [angular/protractor#4140]
In some cases of our business logic we need to refresh the page and keep in request header Referer value and other values. But actually when we use method browser.refresh it does not send all these information in header. In protractor when we do not set ignoreSynchronization=true, protractor using browser.get(href).
And in documentation there is the following 
# Makes a full reload of the current page and loads mock modules before

We need to have the method to refresh the page and get Referer value from request header without using ignoreSynchronization=true.

**Comment by NickTomlin** [comment]
You should be able to use a combination of ignoreSynchronization and `waitForAngular` to preserve the referrer. 

Because of its usage and debugging nature, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help. 

If you are not able to find a solution and believe this is an issue with Protractor core, please submit an issue and follow the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE).

Thanks! 😄

**Comment by mmikirtumov** [comment]
Hi Nick,

Thank you very much, but after when I use waitForAngular, it does not fix my problem, because from any action .click(), .isDisplayed() etc., our team should use then logic. And it is hard to maintain code. So every time we should use 
```
element.click().then(function(){
})
```
I have created on pull request to solve this problem.

https://github.com/angular/protractor/pull/4142
