### ISSUE TITLE
Execution order of Suites and Specs in Conf file Protractor

### ISSUE THREAD

**Issue by kunalshokeen** [angular/protractor#4206]
Hi All,

I want to know the execution order of Suites and Specs in conf file for Protractor.I have read at few places that it is in alphabetical order a->z but while running specs on my file I find they are executed in the order they are defined in conf.Can someone please confirm the behavior for this ?

![image](https://cloud.githubusercontent.com/assets/26962705/24750743/9cd3fca0-1ae4-11e7-943d-b1fa1bdbdc36.png)

Regards,
Kunal

**Comment by NickTomlin** [comment]
The ordering of suites will be respected since we [iterate over the keys of suites](https://github.com/angular/protractor/blob/master/lib/configParser.ts#L102). Alphabetical order typically comes into play with "globs" like `*-spec.js`, those will be sorted in alaphabetical order.

I'm going to go ahead and close this; please ask any additional questions on StackOverflow.

**Comment by kunalshokeen** [comment]
Thanks Nick things are clear now .
