### ISSUE TITLE
Expected text and toequal text are same but text case is failing in protractor.

### ISSUE THREAD

**Issue by VineethMadathil88** [angular/protractor#4208]
Hi,
Here I have attached the code and result.
 expect(element(by.binding('warningMsg')).getText()).toEqual('The block time cannot span across two days. Please fix the duration or start time and try again.');

![p1](https://cloud.githubusercontent.com/assets/23114718/24794609/16ccbf1e-1b3b-11e7-8fb3-e5ead114e417.PNG)

Bug report
---

- Node Version: ``7.5.0
- Protractor Version: 5.1.1``
- Angular Version: `1`
- Browser(s): ``Chrome
- Operating System and Version ``Windows 7, amd64, 6.1

**Comment by marleitao** [comment]
Hi,

As getText() is providing text, may be an issue in Jasmine 'toEqual' method and not in Protractor.

Try to print getText to console and compare both manually and try to use 'toBe' instead of 'toEqual' just for troubleshooting. Probably getText is getting spaces or \n and you may need to trim that before comparing.

**Comment by NickTomlin** [comment]
Agreed that this probably isn't an issue with protractor. Our example [does the exact same thing](https://github.com/angular/protractor/blob/master/example/example_spec.js#L7-L9) successfully in chrome. 

Because of this, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by VineethMadathil88** [comment]
Hi @marleitao , Yes this issue in jasmine,
I tried toBe,toContain and @NickTomlin example does the exact same thing

**Comment by VineethMadathil88** [comment]
This is the stack overflow link:
![error111](https://cloud.githubusercontent.com/assets/23114718/24857989/25010192-1d9f-11e7-90f0-28a4994cb5ff.PNG)
http://stackoverflow.com/questions/43275191/expected-text-and-toequal-text-are-same-but-text-case-is-failing-in-protractor?answertab=active#tab-top
