### ISSUE TITLE
Force protractor to stay in background, or atleast somewhere else. 

### ISSUE THREAD

**Issue by keatinge** [angular/protractor#4216]
I've been trying to solve this for a while, I've looked into running tests on a docker container but wasn't able to get that setup because I'm on Windows 7. 

All I want to do is run my tests and not have a giant chrome window pop up right in front of my ide as soon as I launch the test. Is there anyway I can get it to be running in the background, like behind my ide. I just want to do anything so it's not directly in my face as soon as I launch it. Even getting it to move to my other monitor would be good enough. I understand it has to stay open, but does it really have to pop up in front of everything else as soon as it opens? How can I set this up so it doesn't open on top of everything else? 

For anyone else with a similar issue a decent hack is to add the following code, but it's still pops up in the center of my main monitor for 1-2 seconds:

```javascript
  browser.driver.manage().window().setPosition(-1920, 0);
  browser.driver.manage().window().setSize(1100, 1080);
```

**Comment by mgiambalvo** [comment]
Hi there!

Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

That said, you could try running selenium in a VM. Though, if you don't have Hyper-V, I don't know how well the VM would run. You could either use webdriver-manager to start and run selenium in the vm, or just install Selenium Grid.

Thanks and good luck!
