### ISSUE TITLE
How to enable compatibility mode in IE using Protractor

### ISSUE THREAD

**Issue by raghavbheem** [angular/protractor#4243]
Hi there,

I want to know how to invoke IE browser 8 in compatibility view ?

Problem Description: We have a application that can only be open in IE compatibility view, I want to automate few scenarios in that application using protractor. 

I am able to invoke IE by changing the conf.js capabilities to the following:

'browserName' : 'internet explorer',
		version : '8',
		platform : 'ANY'

I want to know if there is way that everytime my IE will open in Compatibility View.

Bug report
---

- Node Version:  'v6.10.1'
- Protractor Version: '4.0.13'
- Angular Version: NA
- Browser(s): `IE 8'
- Operating System and Version `Win 7 64 Bit machine`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by NickTomlin** [comment]
Hi there!

Because it is specific to configuring IEDriver and not Protractor core, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask) or a IEDriver specific venue.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
