### ISSUE TITLE
System var in excecute script doesn't work

### ISSUE THREAD

**Issue by djom20** [angular/protractor#4277]
Hi there!

I'm trying to export a var from protractor to my local env with browser.executeScript(). Suppose I have a COUNTER_USERS=0 in my console. Now when I run my tests in protractor I set COUNTER_USERS=1 with the next code:

`browser.executeScript('export COUNTER_USERS=1')`

But when I try to print this var in the console I got COUNTER_USERS=0 and should be shown an one.

**Comment by NickTomlin** [comment]
Hi there!

I'm not quite sure what you are expecting; If `export` is supposed to set an environmental variable (e.g. something on `process.env` or your shell's `ENV`) it is not going to do so because `executeScript` is run by the current browser and not your shell. I'm surprised that that does not result in a syntax error. 

Regardless, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
