### ISSUE TITLE
Fails to find element when running more than one spec file

### ISSUE THREAD

**Issue by qroosje** [angular/protractor#4295]
Hi there!

Bug report
Fails to find element when running more than one spec file

- Node Version: `7.4.0`
- Protractor Version: `5.1.0`
- Angular Version: `1`
- Browser(s): `chrome`
- Operating System and Version `windows 10 Home 64-bit`
- conf.js
- A relevant example test: description of scenario.
I run the the protractor conf.js. In the conf.js I have the file ´spec/testA_spec.js´ which is the one being ran. In this file I have created another object which s ran for logging in and creating a task which is what the application does, after these object are done the ´it´are ran and this goes without problem. When in the conf.js file i add more spec file to run [ spec/testA_spec.js,  spec/testB_spec.js]. This time the first spec(doesn`t matter the order testA or testB) run with no problem as normally but when running the second spec or any there after protractor doesn't seem to be able to find an element in the object. the object that is called is ´createNewTask´. this is the same object used in all the spec file(testX) but whenever I run more than one spec for some reason protractor cant find one particular  element(all other element on that page works as usual) even though the same object worked perfectly fine in the first spec file(testA or the spec that ran first). All spec files(testX) individually run with no problem(all element are found no problem). 

I don't know what might be the cause of this?

- Output from running the test: `Failed no element found using locator: By(css selector, *[id="signatureCanvas"])
- Steps to reproduce the bug: `run more than one spec file.` 
- The URL you are running your tests against (if relevant):localhost

**Comment by NickTomlin** [comment]
Hi there!

It's difficult to understand what exactly is going without actual code, but there is going to need to be more debugging to understand this issue. My guess is that there is something within your specs that are modifying the page being tested.

Because it is likely an issue with your environment/application and not Protractor, and will require additional debugging and troubleshooting, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

If you still believe this is an issue with Protractor itself, please include a small example repository that we can clone and run to reproduce the issue. You can use [nicktomlin/protractor-mvce](https://github.com/NickTomlin/protractor-mcve) as a basis if you'd like.

Thanks!
