### ISSUE TITLE
File will upload successfully but with 0 size bytes

### ISSUE THREAD

**Issue by Hokrani** [angular/protractor#4369]
I'm able to upload file using below code 

`  

      var fileToUpload = 'tt.jpg';

        var absolutePath = path.resolve(__dirname, fileToUpload);

        var FileDetector = require('selenium-webdriver/remote/index.js').FileDetector;
        browser.setFileDetector(new FileDetector());

        element(by.css('input[type="file"]')).sendKeys(absolutePath);`

But file will upload with zero byte size even though file size is actually 1 KB
![image](https://user-images.githubusercontent.com/29490752/27971034-d43d0380-636e-11e7-9d85-c329e12ee0d7.png)

My development added below code for uploading the file 
![image](https://user-images.githubusercontent.com/29490752/27971161-3770eef8-636f-11e7-9b11-eb862916b82d.png)

Let me know where i am doing wrong.

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README:


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
