### ISSUE TITLE
Protractor Timeouts for long running http tasks

### ISSUE THREAD

**Issue by MuraliMolluru** [angular/protractor#4370]
I am facing timeouts when long running http calls during protractor E2E tests and finally getting timeout as
  - Failed: Timed out waiting for asynchronous Angular tasks to finish after 300 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular. 
      The following tasks were pending:
       - $http: http://xxx.com....
Changing timeout is not solution for my case as we are using event-stream mechanism so that long running http request never get closed and keep open in the background to receive events from the server.
I am using protractor 5.x and AngularJS 1.6x.
It was mentioned in the documentation that using $interval service would solve this timeout issues https://github.com/angular/protractor/blob/master/docs/timeouts.md#angularjs
But this is not working solution.
I had put this question is stackoverflow but couldnot get answers, so i am raising issue here.
Please help as this is major issue most of the people are facing.

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README:


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
