### ISSUE TITLE
Angular4 + Protractor. CanActive route with browser.get() 

### ISSUE THREAD

**Issue by JuliaAlaeva** [angular/protractor#4375]
Bug report
---

- Node Version: `8.0.0`
- Protractor Version: `5.1.2`
- Angular Version: `4.0.0`
- Browser(s): `Version 59.0.3071.115 (Official Build) unknown (64-bit)`
- Operating System and Version `4.4.0-62-generic / GNU/Linux`
- Your protractor configuration file

```
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 40000,
    print: function() {}
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  }
};

```
- A relevant example test

My test:

```js
import { SliderPage } from './app-slider.po';
import { browser, by, element, promise, ElementFinder, ElementArrayFinder } from 'protractor';

describe('angular-app App', () => {
  let page: SliderPage;

  beforeEach((done) => {
    page = new SliderPage();
    page.navigateTo();
  });

  it('should select first image (if it exist)', async () => {
    console.log(element(by.css('.slider')).getText());
    // page.getImages().count().then((count) => {
    //   console.log(count);
    //   done();
    // if (count > 1) {
    //   page.getFirstImage().click().then(() => {
    //     expect(page.getFirstImage().getAttribute('class')).toMatch('selected');
    //   })
    // }
    // });
  });
}
```

My app-slider.po:

```js
import { browser, by, element, promise, ElementFinder, ElementArrayFinder } from 'protractor';

export class SliderPage {
  navigateTo() {
    return browser.get('/slider');
  }

  getImages() {
    return element(by.css('.slider')).all(by.css('li'));
  }

  getFirstImage(): ElementFinder {
    return this.getImages().first();
  }

  getArrowNext(): ElementFinder {
    return element(by.css('arrow-next'));
  }

  getArrowPrev(): ElementFinder {
    return element(by.css('arrow-prev'));
  }
}
```

- Output from running the test
```

Jasmine started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
A Jasmine spec timed out. Resetting the WebDriver Control Flow.

  angular-app App
    ✗ should select first image (if it exist)
      - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
          at ontimeout (timers.js:488:11)
          at tryOnTimeout (timers.js:323:5)
      - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
          at ontimeout (timers.js:488:11)
          at tryOnTimeout (timers.js:323:5)
      - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
          at ontimeout (timers.js:488:11)
          at tryOnTimeout (timers.js:323:5)

**************************************************
*                    Failures                    *
**************************************************

1) angular-app App should select first image (if it exist)
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

Executed 1 of 1 spec (1 FAILED) in 2 mins.
[11:17:17] I/launcher - 0 instance(s) of WebDriver still running
[11:17:17] I/launcher - chrome #01 failed 1 test(s)
[11:17:17] I/launcher - overall: 1 failed spec(s)
[11:17:17] E/launcher - Process exited with error code 1

```

- Steps to reproduce the bug

1. My routes in app.module.ts:
```
Routes = [
  { path: 'login', component: AuthPageComponent, canActivate: [LoginGuard] },
  { path: 'slider', component: SliderPageComponent, canActivate: [SliderGuard] },
  { path: '', redirectTo: 'slider', pathMatch: 'full' }
];
```
2. I run command `ng e2e`
3. Browser don't open and then I get issues
4. If I change routes:
```
Routes = [
  { path: 'login', component: AuthPageComponent},
  { path: 'slider', component: SliderPageComponent},
  { path: '', redirectTo: 'slider', pathMatch: 'full' }
];
```
Browser open and all okay.

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by wswebcreation** [comment]
Hi @JuliaAlaeva 

You closed it again, isn't it an issue?

**Comment by JuliaAlaeva** [comment]
Problem exist.

**Comment by wswebcreation** [comment]
Hi @JuliaAlaeva 

I don't think it has something to do with it, but you are logging a promise without resolving it (with for example this `console.log(await element(by.css('.slider')).getText());`, just in case ;-)

I'm not familiar with Angular + `canActivate`, but just a _check-check-double-check_, you've implemented the _router_ and the `SliderGuard` the correct way? You are not redirected to a page that isn't a Angular page, or your`SliderGuard` isn't working properly? 
Did some searching on the internet and saw some question / problems with it, for example [here](https://github.com/angular/angular-cli/issues/3954). That page also refers to the [router](https://angular.io/guide/router)-docs.

Based on your info I would suggest to look into your `SliderGuard` because Protractor works without it and breaks when the `SliderGuard` is activated.

**Comment by JuliaAlaeva** [comment]
I can to solve this problem some way? 
My canActivate return "true" and don't protect this page, if my user is logging. But I can't do this with protractor, because I implement login with Facebook.

**Comment by wswebcreation** [comment]
Based on this info I would suggest you to ask this question StackOverflow or Gitter because it has a bigger public. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I'm gonna close it for now.

Thanks!

**Comment by raha1923** [comment]
i have this problem too, so i will happy if you found a solution, tell me about that @JuliaAlaeva .

thank you in advance.

**Comment by raha1923** [comment]
this is my problem in this case, are the protractor able to detect components wrapped by wrappers, in the router-outlet at all?

https://stackoverflow.com/questions/48606150/e2e-protractor-test-cant-detect-angular-component-in-multi-layer-angular-router
