### ISSUE TITLE
get index from row element in protractor

### ISSUE THREAD

**Issue by lararogu** [angular/protractor#4376]
I search for a row in a table using protractor.I want a specific row with a specific ID in one of the columns. With a filter list I am able to get read that id but now I want to know to which row index corresponds that id.

 element.all(by.repeater('item in list)')).count().then(function (count) {
            var list = element.all(By.binding('item.ID'));

            var ID = list.filter(function (elem) {
                return elem.getText().then(function (text) {
                    return text === myID;
                });
            }
         expect(ID.getText()).toBe(myID)); 

The thing is that I want to read the value from another column but from the same element,so for that I would need the index.

Any ideas?

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README:


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
