### ISSUE TITLE
Cannot access HTML elements on iOS device [Timeout]

### ISSUE THREAD

**Issue by SpedsT** [angular/protractor#4377]
Note: I'm just starting to work with end-to-end testing so please forgive my noobness. 

## The problem

I am trying to execute end-to-end test using Protractor with Jasmine and Appium on a iOS device on a simple dummy application created with Ionic v1. All what I am trying to make the test do is just click a button located with: `element(by.css('a[icon-on=ion-ios-chatboxes]'))`. 

What I am getting is a timeout but I wasn't able to track down the problem to the root.

> Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

The interesting part is that on an Android device works without any problem. 

## Environment

* Appium version: v1.6.5
* OS: macOS Sierra 10.12.3
* Node.js version : v7.8.0
* Mobile platform/version under test: iOS 10.3.1
* Appium CLI or Appium.app|exe: Appium CLI
* Protractor Version: 5.1.2

## Link to Appium, Protractor and webDriver logs

https://gist.github.com/SpedsT/e16e4ee6093fde873c18467e96392296

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README:Ohh yeah, made my day


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


I also saw that you posted it on SO, so I'll close the issue here.

Thanks!
