### ISSUE TITLE
CircleCI is broken due to drag and drop issue

### ISSUE THREAD

**Issue by heathkit** [angular/protractor#4385]
Our CircleCI build [is failing](https://circleci.com/gh/angular/protractor/705). The test that's failing is "using an ActionSequence should drag and drop" from basicConf.js. I'm guessing this is due to a change in selenium webdriver around the actions API. It would be good to get this fixed so we can get a passing CI run again. If it's a big unfeasible problem, marking the test pending and referencing this issue would also be fine, as long as we investigate what's happening.

**Comment by wswebcreation** [comment]
Will dive into it the coming days and create a PR for it

**Comment by wswebcreation** [comment]
Hi @heathkit ,

I dove into this and I think it's related to https://github.com/angular/protractor/issues/583. What I see in the testapp of Protractor is that the html 5 slider is working, but it will only go to value 5. It doesn't mater if you try to slide it to 1000px to the right, it will still stick on 5.

We now have a few options:

1. change expected value 10 to 5. We know the drag and drop work, only not with HTML5 sliders due to a Chromedriver issue (maybe we can also close issue 583). Also refer to https://github.com/angular/protractor/issues/583 in a comment in the test why we adjusted it to 5.
2. accept that is wont work and skip this test

I'm more in favour of 1 because the dag and drop does work (set some sleeps into it to see if it's working and it's working), only not completely due to https://github.com/angular/protractor/issues/583. 

Like to hear what you think

**Comment by BassemDev** [comment]
@heathkit do you face a problem with getCurrentUrl in circleCi with chrome, i can't get the new url after login to the home page it's always sending the old url which mean the /signIn page ?
I don't know the reason but with firefox on circleCi and locally (on my mac) everything works fine.
could you maybe share an example where you use getCurrentUrl on circleCi after signIn. meanWhile this is an example of my code:

```
import { browser, Config, element, by } from 'protractor';
import { assert } from 'chai';

describe('test sample', function() {

    function urlChanged(url) {
            return function () {
                return browser.getCurrentUrl().then(function(actualUrl) {
                    return url != actualUrl;
                });
            };
    };

    beforeEach(function() {
        browser.ignoreSynchronization = true;
    });

    it('should login', function() {
        browser.get('http://localhost:8080/#/signin');
        const email = element(by.name('email'));
        const password = element(by.name('password'));
        const button = element(by.css('[type="submit"]'));
        email.sendKeys('qa-test@fashion.cloud');
        password.sendKeys('fc123456789');
        button.click();
        browser.wait(urlChanged('http://localhost:8080/#/signin'), 30000);
        browser.getCurrentUrl().then((url) => {
            console.log('url is', url);
        });
    });
});
```

**Comment by wswebcreation** [comment]
@BassemDev 

Tnx for the info, but it's better to mention it in your own issue. This issue is mainly for the drag and drop of a HTML5 slider with chrome, not an issue with the `getCurrentUrl()`

**Comment by BassemDev** [comment]
@wswebcreation , i am not trying to mention it here but this is just a simple question for @heathkit to see if he also face the same issues or not with that method since this issues is also related to CircleCi behaviour with chrome. (i also update and explain more in my issues)

**Comment by cnishina** [comment]
"Fixed" with `xit`. Should revisit https://github.com/SeleniumHQ/selenium/issues/3693 in the future to fix our action_spec.js. See https://github.com/angular/protractor/commit/768fd393d1084a8da0ec6eeaa57508bf17519a3f for the "fix"

**Comment by wswebcreation** [comment]
Created a new issue for removing the `xit` and closed this one as asked by @cnishina
