### ISSUE TITLE
Way to ignore certain suites in command line args

### ISSUE THREAD

**Issue by parky128** [angular/protractor#4388]
Hello,

When specifying suites to run from the command line, is it possible to provide suite names to ignore?

I'm sure I saw somewhere, perhaps in another issue here that you could use a `!` prefix on a suite name when setting the `--suites` value, but I cant find where I did see this.

Is this possible?

Thanks

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
