### ISSUE TITLE
Drag and drop not working in firefox

### ISSUE THREAD

**Issue by hansiemithun** [angular/protractor#4393]
I have below code which is working fine in local machine, chrome environment considering drag and drop:

`browser.actions().dragAndDrop(elem1, elem2).mouseUp().perform();`

But the same code throwing error in firefox browser:

```
[e2e] [firefox #11-1] [31m    Failed: UnknownError: Cannot release a button when no button is pressed.'UnknownError: Cannot release a button when no button is pressed.' when calling method: [wdIMouse::up]
[e2e] [firefox #11-1]     Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
[e2e] [firefox #11-1]     System info: host: '6b46e0e227dc', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.13.1.el7.x86_64', java.version: '1.8.0_03-Ubuntu'
[e2e] [firefox #11-1]     Driver info: driver.version: unknown[0m [e2e] [firefox #11-1]   Stack:
```

Any assistance to fix will be much appreciated to fix it?

**Comment by wswebcreation** [comment]
Hio @hansiemithun ,

Strange that it works on chrome, according to the docs your syntax is not correct, see [here](http://www.protractortest.org/#/api?view=webdriver.WebDriver.prototype.actions).

Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
