### ISSUE TITLE
browser.pause in beta using protractor cucumber framework

### ISSUE THREAD

**Issue by sriparnam** [angular/protractor#4394]
Hi there!

I have used protractor cucumber framework. In step definition file I have a browser.pause() which seems to fail at command line execution. Please find zip of protractor config and cucumber feature & step definition file attached.

This is the error that comes up:

2 scenarios (2 passed)
8 steps (8 passed)
0m00.016s
[19:23:49] I/protractor -
[19:23:49] I/protractor - Encountered browser.pause(). Attaching debugger...
[19:23:49] I/protractor -
[19:23:49] I/protractor - ------- WebDriver Debugger -------
# [19:23:49] I/protractor - Starting WebDriver debugger in a child process. Pause is still beta, please report issues at github.com/angular/protractor
[19:23:49] I/protractor -
[19:23:49] I/protractor - press c to continue to the next webdriver command
[19:23:49] I/protractor - press ^D to detach debugger and resume code execution
[19:23:49] I/protractor -
[19:23:50] I/launcher - 0 instance(s) of WebDriver still running
[19:23:50] I/launcher - chrome #01 passed

[featuretest.zip](https://github.com/angular/protractor/files/1160126/featuretest.zip)

**Comment by wswebcreation** [comment]
Hi there!

When I look at your code I think you are missing 2 things:

1. In your step file you don't have a callback / return a promise. That is why the tests succeed before your are doing anything, see [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/step_definitions.md) for the step implementation
2. If you want to use the `browser.pause();` you should place it within a step, not outside the step.

Because your issue involves usage and debugging it is better to ask your question on StackOverflow or Gitter in the future. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I'm going to close the issue for now.

Thanks!

**Comment by sriparnam** [comment]
Thank you for the advise. great help !!
