### ISSUE TITLE
Protractor : Unexpected error launching Internet Explorer. Pro tected Mode settings are not the same for all zones

### ISSUE THREAD

**Issue by ManojMN** [angular/protractor#4404]
Hi All,

I am facing issue while launching protractor code.

Below are the code that i am using:

**conf.js with below code**

```js
// An example configuration file. 
exports.config = {
    // The address of a running selenium server. 
    seleniumAddress: 'http://localhost:4444/wd/hub',

    // Capabilities to be passed to the webdriver instance. 
    capabilities: {
       // 'browserName': 'chrome'
        'browserName': 'internet explorer'
    },

    // Spec patterns are relative to the current working directly when 
    // protractor is called. 
    specs: ['example_spec.js'],

    // Options to be passed to Jasmine-node. 
      allScriptsTimeout: 500000,
    jasmineNodeOpts: {
        onComplete: null,
        isVerbose: true,
        showColors: true,
        includeStackTrace: true,
        defaultTimeoutInterval: 1000000
    }
};
```

**sample_class.js file with below code:**
```
describe('angularjs homepage title check', function () {
    it('should have a title', function () {
        console.log('Step 1');
        browser.get('http://google.com');
        expect(browser.getTitle()).toEqual('My Todolist Page');
    });
});
```

And there are the command i used to launch 
1. Installed protractor and node js
2.  webdriver-manager update --ie
3. webdriver-manager start

**Please find the error i am getting below**
```bash
13:24:20.675 WARN - Exception: Unexpected error launching Internet Explorer. Pro
tected Mode settings are not the same for all zones. Enable Protected Mode must
be set to the same value (enabled or disabled) for all zones. (WARNING: The serv
er did not provide any stacktrace information)
Command duration or timeout: 41 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'US1INF020D70194', ip: '10.16.198.27', os.name: 'Windows 7',
os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: InternetExplorerDriver
```

I cant change my IE settings because it is disabled in my machine.  Please recommend anything we can do in code.

**Comment by wswebcreation** [comment]
Hi there!

First of all you need to set those settings in IE, otherwise you can't automate it.
Secondly, since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
