### ISSUE TITLE
cant trigger click/tap event 

### ISSUE THREAD

**Issue by ebin123456** [angular/protractor#4406]
i just want to trigger button click event for following code
**<button id="test" [disabled]="clickControl" (tap)="gotoWallet()" data-test-id="my-wallet">**

i tried following code 
**element(by.xpath('//button[@data-test-id="my-wallet"]')).click()**

getting timeout  exception 

posted question in SO https://stackoverflow.com/questions/45275552/how-trigger-tap-event-for-ionic2-application-to-automate

is this bug of protractor ?

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow what you already did.

From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
