### ISSUE TITLE
browser.wait timeout -- how to catch the exception and continue?

### ISSUE THREAD

**Issue by Sean-Brown** [angular/protractor#4409]
[Related question on Stack Overflow](https://stackoverflow.com/questions/45355734/protractor-wait-timeout-catch-and-continue)

Essentially I have code that calls browser.wait() which may potentially timeout. This is OK but I cannot seem to catch the exception: if browser.wait() times out then it fails the test. The code in question is waiting for a data table to have rows and the table may not have rows, so if the code times out then I want to have logic to create a row in the table, but I cannot seem to catch the timeout exception.

**Comment by wswebcreation** [comment]
Hi @Sean-Brown 

Since you are referring to an issue / question on SO and this is more a coding issue then an issue with Protractor I'm going to close this issue , see also  the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.) 

I'll try to answer it on SO

**Comment by Sean-Brown** [comment]
Sure no problem, and thanks for pointing out the `getting help` section
