### ISSUE TITLE
Protractor does not clean Chrome.exe process after test finish with failure.

### ISSUE THREAD

**Issue by gaurabhi1986** [angular/protractor#4415]
Hi !
I am facing issue with **protractor@4.0.14**, I am using **chrome driver 2.29** version with 
Protractor. Whenever UI tests execution finish with failure **Chrome.exe** processes still running in windows. Every-time I need to manually kill all the **chrome.exe** process otherwise execution time will increase due to slowness.

Can you please suggest me what Can I do to make sure that each and every **chrome.exe** processes will be killed after test execution.

Thanks,
Abhishek

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

We can try to help you there

Thanks!
