### ISSUE TITLE
Api call response value is not getting in the getText() ,test failed by showing the message   - Expected '' to be '101'. 

### ISSUE THREAD

**Issue by darsana** [angular/protractor#4424]
it('should allow searching and Show the count', () => {
  
        const searchButton = element(by.className('list-ro-input'));
        const searchBox = element(by.className('list-RO-search'));
        searchBox.sendKeys('[PIMS]SYSTEM+GAP_FILL_TEST');
        searchButton.click().then(() => {
          browser.driver.wait(function () {
            expect(element(by.id('SequenceMasterCount')).getText()).toEqual(101);
          }, 50000);
        });
      });

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
