### ISSUE TITLE
click() method does not work on Appium iOS/safari 

### ISSUE THREAD

**Issue by samsul-kabir** [angular/protractor#4425]
Hi there,

click() method is not working in Appium iOS/safari. If run test, it does not do anything. Not throwing any error. I put an delay explicitly to check if it perform the click function, but nothing happens.

Any idea why is this happening?

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

By the way, Safari is more strict with the element that holds the click event and the element that receives it. It could have something to do with that. I'm going to close it for now.

Thanks!
