### ISSUE TITLE
browser.ignoreSynchronization and browser.waitForAngularEnabled()

### ISSUE THREAD

**Issue by vinodkpasi** [angular/protractor#4432]
What is the difference between browser.ignoreSynchronization and browser.waitForAngularEnabled()?

**Comment by NickTomlin** [comment]
Hi there!

[`waitForAngularEnabled()` sets ignoreSynchronization under the hood](https://github.com/angular/protractor/blob/183cd803254f7a3ccb3a8650e8ef06b4fff03446/lib/browser.ts#L231). 

Because it is a usage question your issue is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
