### ISSUE TITLE
Create ElementArrayFinder from array of ElementFinders

### ISSUE THREAD

**Issue by quirimmo** [angular/protractor#4444]
Hi, 

I have the following issue. In a method which returns a promise, I have an `ElementArrayFinder`, but when I resolve the promise passing this object, actually in `then` block of the resolution of the promise, I get the an array of `ElementFinder` instead of an `ElementArrayFinder`.
Same as I manually resolve the `ElementArrayFinder`. 

How can I avoid that? How can I return the `ElementArrayFinder` from a promise without explicitly resolving it also? 

Thanks a lot

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
