### ISSUE TITLE
Error highlightDelay protractor 5.1.2 

### ISSUE THREAD

**Issue by adelitofarias** [angular/protractor#4448]
Hello Dearest !!!

Unfortunately with the last update of webdrive-manager, version 12.0.6, protractor 5.1.2, a highlightDelay function presents the error:

**E/BlockingProxy - (node:4706) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: err.toString is not a function**

Has anyone encountered this error?

Bug report
---

- Node Version: 6.9.5
- Protractor Version: 5.1.2
- Angular Version: 1.5.9
- Browser(s): Chrome
- Operating System and Version: Linux 16.04 LTS
- Your protractor configuration file

![image](https://user-images.githubusercontent.com/19351435/29333222-59e220a0-81d9-11e7-9d0a-9971714b12a2.png)

- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by rodrigc** [comment]
@adelitofarias I have encountered a slightly different error, but it is very similar to yours:

https://github.com/angular/protractor/issues/4473

In my case `err` is None, so calling `err.toString()` is the source of the problem.

**Comment by rodrigc** [comment]
@adelitofarias I cannot see your full config file.  The problem seems to be in BlockingProxy, which is available in Protractor 5.1.0 and higher.

In your config, you should try disabling BlockingProxy by putting in your exports section:

```
useBlockingProxy: false
```

also if you have `webDriverLogDir`, remove that setting.

**Comment by draganstanisavljevic** [comment]
I got same error after I updated webdriver manager.

useBlockingProxy: false did not help

I solved issue by removing highlightDelay  from config file

**Comment by rodrigc** [comment]
From this line: https://github.com/angular/protractor/blob/master/lib/config.ts#L536
it looks like `highlightDelay` turns on blocking proxy, even if `useBlockingProxy` is set to false.
So your workaround is correct.

I opened another bug against BlockingProxy: https://github.com/angular/blocking-proxy/issues/38 because it looks like it has problems.  I'm waiting for @heathkit to look at it, since it looks like he is the main person working on BlockingProxy.

**Comment by heathkit** [comment]
`highlightDelay` depends on blocking proxy to work. The issue was a protocol change in selenium standalone from 3.0.x to 3.5.x. Version 1.0.0 of blocking-proxy fixed the problem.

The next release of Protractor should fix this. If you'd like to use highlightDelay before then, you can do the following

```
npm install blocking-proxy@1.0.1
blocking-proxy -p 4445 -s http://localhost:4444/wd/hub --highlightDelay 2000
```

and in another shell

```
protractor --blockingProxyUrl=http://localhost:4445 --highlightDelay
```

Note that you need to turn on `--highlightDelay` in both protractor and blocking-proxy. You also need to pass blocking-proxy the address of your selenium standalone server when you start it.

**Comment by aarr0n** [comment]
@heathkit Really keen to start using `highlightDelay`, is there a date for the next release of Protractor?

**Comment by heathkit** [comment]
We'll do a release next week. Sorry for the delay!

**Comment by qiyigg** [comment]
@aarr0n @heathkit  Sorry, I haven't got a time to do the release this week, I will do it on Monday. Ideally, also include the doc modification for the new debugging process in the new release.
