### ISSUE TITLE
waitForAngularEnabled is not a function

### ISSUE THREAD

**Issue by stevermeister** [angular/protractor#4453]
Bug report
---

- Node Version: `6.9.4`
- Protractor Version: `4.0.11`
- Angular Version: `4`
- Browser(s): `Chrome`

Getting an error `waitForAngularEnabled is not a function` on [browserstack](https://www.browserstack.com/) service, but locally it works fine.

Also created question on SO:
https://stackoverflow.com/questions/45636630/waitforangularenabled-is-not-a-function

**Comment by wswebcreation** [comment]
Hi @stevermeister 

The reason why it's not working on your browserstack service is that Protractor 4 doesn't support `waitForAngularEnabled()`. That method is not implemented in Protractor 4. It's implemented on Protractor 5.

Have you installed Protractor global on your local machine and perhaps have version 5.x.x?

**Comment by stevermeister** [comment]
@wswebcreation thank you very much for you quick response!
and sorry for stupid question.

I have version 4 global, but I think further I'll figure it out myself

**Comment by wswebcreation** [comment]
Hi @stevermeister 

No question is stupid, I could also be me that could ask it ;-). 

When you try to figure it out, please check all the globals and dependencies of the globals on your local machine. I stopped using global installs on my machine because I had a lot of problems with the globals and dependencies I thought I never installed but did had on my machine.

I'm going to close this issue for now but it's still open for further discussion.
