### ISSUE TITLE
Protractor 5.1.2 + Jasmine 2 - Header passing issue for UI automation

### ISSUE THREAD

**Issue by nitinnitik** [angular/protractor#4458]
I have a requirement to add headers to every request on UI action. so be it opening home page, click on buttons or links I need to add few headers. I need to do this in protractor so that I can automate the functionality. Can you please give me some example on how I can do this?

I am using Jasmine + protractor..

i have raised it on stackoverflow but no response from anyone. 
https://stackoverflow.com/questions/45540512/adding-headers-on-ui-action-protractor-jasmine

I am using fiddler tool at the moment to append the headers at the moment but I want to automate this so that I don't need to start fiddler every time before i run automation.

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by nitinnitik** [comment]
Hi, I have already raised in stackoverflow  and have shared link above. I have not received any response. I have not used template as I have not written any test case as of now as the above is pre requisite to start my automation. 
Please let me know if you need any specific information i will provide.  I am stuck with this issue since a while now - any help on this will be of great help to me.

**Comment by wswebcreation** [comment]
@nitinnitik 

I understand your problem, but this issue list is only for issues/bugs with Protractor, not for debugging or other questions with Protractor and or third party tools. That's why I closed it.

**Comment by nitinnitik** [comment]
okay. but you think anyone can help me? no response on other links
