### ISSUE TITLE
Protractor doesn't run in private mode on IE 11

### ISSUE THREAD

**Issue by IgorProtsenko** [angular/protractor#4478]
Hi,
I'm trying to run IE 11 in private mode, and when I set all the keys and requirements are met, IE just stops booting.

It ends like this:

[19:51:12] I/launcher - Running 1 instances of WebDriver
[19:51:12] I/local - Starting selenium standalone server...
[19:51:15] I/local - Selenium standalone server started at http://192.168.0.102:53355/wd/hub

and then stuck, browser instance doesn't appear at all.
I have in my registry the key TabProcGrowth REG_DWORD with the value 0 (actually, I tried all the options with system reboot after each) in the required path ../Internet Explorer/Main/

Conf:

node -v 6.11.2
protractor 5.1.1
IE 11.0.9600.1876
Windows 7

    capabilities: {
        browserName: 'internet explorer',
        "ie.forceCreateProcessApi": true,
        "ie.browserCommandLineSwitches": "-private",
        "ie.ensureCleanSession": "true",
    },

    localSeleniumStandaloneOpts : {
        jvmArgs : ["-Dwebdriver.ie.driver=node_modules/IEDriverServer.exe"]
    },
    seleniumServerJar: '../node_modules/selenium-standalone-jar/bin/selenium-server-standalone-3.0.1.jar',

As soon as forceCreateProcessApi key is removed IE starts, but obviously not in private mode.

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by Havunen** [comment]
I'm having the exact same issue and tried the same settings but no luck! Probably this is bug in IE driver? I tried its manually possible to launch IE in private mode by adding "-private" parameter. But that does not work with selenium
