### ISSUE TITLE
With shardTestFiles browser windows are not being closed after tests are finished

### ISSUE THREAD

**Issue by natalya-semenova** [angular/protractor#4480]
With `shardTestFiles: true`  browser windows are not being closed after tests are finished. Launcher says 'X instance(s) of WebDriver still running' and test run never completes. 
---
- Node Version: `v8.4.0`
- Protractor Version: `5.1.2`
- Angular Version: `1.6.5`
- Browser(s): `Chrome`
- Operating System and Version `Linux (Fedora release 26) x86_64`
- Please find the protractor configuration file, relevant example test, output from running the test, steps to reproduce here: https://github.com/natalya-semenova/issues

**Comment by wswebcreation** [comment]
Hi @natalya-semenova 

I see you are using CucumberJS 3 and protractor-cucumber-framework 4, both the latest versions. What happens if you downgrade to CucumberJS 2 and protractor-cucumber-framework 3.

I currently don't use CucumberJS 3 and protractor-cucumber-framework 4 in my own project, we work with CucumberJS 2 and protractor-cucumber-framework 3 and we don't see the issue.

Based on what I see on the current issues on this Git there are no issues with other frameworks. Have you tried with asked the protractor-cucumber-framework? I know there is a different issue there that is about the `restartBrowserBetweenTests:true `, see also [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/100), but maybe it's related.

**Comment by natalya-semenova** [comment]
Hi @wswebcreation 

In general, we don't use `restartBrowserBetweenTests`, but I've played with this option - nothing changes in the described behavior.  

There is no issue when we use cucumber.js 2x version - all browser windows are being closed. 
Based on the fact that Protractor's Runner is responsible for starting the execution  of  a test run, setup,  managing config, etc the issue was raised here, please correct me if i'm wrong.
It feels related to how Protractor handles creating tasks (TaskScheduler) and closing browsers.

**Comment by wswebcreation** [comment]
@natalya-semenova 

Tnx for your response. You are right by saying that _Protractor handles creating tasks (TaskScheduler) and closing browsers_, but if you have this

**New situation:** _Not working_
- CucumberJS: 3.x
- protractor-cucumber-framework: 4.x
- Protractor: 5.1.2


**Old situation:** _Working_
- CucumberJS: 2.x
- protractor-cucumber-framework: 3.x
- Protractor: 5.1.2

And Protractor is still the same version, then I would say that Protractor isn't the problem here. I'll also dive into this, but my first thought would be a third party issue instead of an issue in Protractor.

**Comment by natalya-semenova** [comment]
@wswebcreation

I've opened requests, though resent changes in third party can only reveal the issue in Protractor :)

**Comment by wswebcreation** [comment]
@natalya-semenova 

Tnx! I hope to have time tomorrow to make an example repo that will reflect the issues.

**Comment by natalya-semenova** [comment]
Fixed with [protractor-cucumber-framework v4.0.5](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/releases/tag/4.0.5)

**Comment by wswebcreation** [comment]
Thx for the feedback
