### ISSUE TITLE
Closing browser for unhandled exception

### ISSUE THREAD

**Issue by vinodkpasi** [angular/protractor#4489]
For unhandled exception protractor immediately stops the execution but browser remains open 
There is any workarond for this.

**Comment by wswebcreation** [comment]
Hi @vinodkpasi 

Which framework are you using , Jasmine, Mocha or Cucumber. I know protractor-cucumber-framework (which you use when you want to use CucumberJS) has the option ['ignoreUncaughtExceptions: true'](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework#uncaught-exceptions) which allows cucumber to handle the exception and record it appropriately. I don't know how this works with the other frameworks. 

Since your question is better suited for StackOverflow or Gitter I would advice you to [ask your question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
