### ISSUE TITLE
MS Edge: Error while waiting for Protractor to sync with the page 

### ISSUE THREAD

**Issue by rreitmann** [angular/protractor#4493]
Hi,

we are using Protractor to continuously test our app in Chrome, Firefox, IE 11 and MS Edge on Saucelabs.  While the tests run fine in the first three browsers they fail with the following error in Edge:
`Error: Error while waiting for Protractor to sync with the page: "Unable to get property '$$testability' of undefined or null reference"`

We already provide `rootElement` since `ng-app`  is on the html element in our [index.html
](https://github.com/dzhw/metadatamanagement/blob/04de65dba8124e615ad6ed8432e05db809765451/src/main/webapp/index.html) but this does not seem to help. Do you have any idea?

Bug report
---
- Protractor Version: 5.1.2
- Angular Version: 1.6.6
- Browser: MS Edge
- Operating System and Version: Windows 10
- [Protractor Conf](https://github.com/dzhw/metadatamanagement/blob/04de65dba8124e615ad6ed8432e05db809765451/src/test/protractor/protractor.conf.js)
- [Output from test](https://travis-ci.org/dzhw/metadatamanagement/builds/277001551#L2256)
- [Saucelabs Output](https://saucelabs.com/beta/builds/dd0a76e4cc49456d86e0f95a2e06c486)
- [System under test](https://metadatamanagement-dev.cfapps.io/)

**Comment by wswebcreation** [comment]
Hi @rreitmann 

What happens if you remove the element? Protractor should detect it automatically when you are using AngularJS

**Comment by rreitmann** [comment]
Hi @wswebcreation,

I have run the tests without `rootElement` but it did not help (same error in Edge):
- [Travis Log](https://travis-ci.org/dzhw/metadatamanagement/builds/277172856#L2251)
- [Protractor Conf](https://github.com/dzhw/metadatamanagement/blob/cd7218ca02732701dcd9736a279f4e8e8afd0b7e/src/test/protractor/protractor.conf.js)
- [Saucelabs Output](https://saucelabs.com/beta/builds/beb94e9e6abe4570b8833f8976691522)

**Comment by wswebcreation** [comment]
Hi @rreitmann 

I've checkout your project, did an `npm install`, and ran the test on Edge for only the `home.spec.js` and it works fine, see also the [report](https://saucelabs.com/beta/tests/35d1f33eb0434e6d916b332935704cf7/commands#43)

It could be that a different specs is failing, can you pinpoint that one? For now I would say it's working fine. 
For the customer I work for we have an Angular (4) project and Edge is working fine. I can't share a report because of the security.

**Comment by rreitmann** [comment]
Hi @wswebcreation,

I have also reduced our protractor tests by using only `home.spec.js` (see [`protractor.conf.js`](https://github.com/dzhw/metadatamanagement/blob/1e84a7dac66a75c9f05e5937c227c89b21c5929c/src/test/protractor/protractor.conf.js)) and have run the tests multiple times (sometimes only Edge, sometimes Chrome, Firefox, IE 11 and Edge concurrently). My observations are:
- Edge is always much slower than the other browsers (takes 2-6 times the time see [Protractor Output](https://travis-ci.org/dzhw/metadatamanagement/builds/278235876#L6753))
- If it runs solely, Edge fails rarely (but it does sometimes) 
- Edge fails often if all 4 browser tests run concurrently (Saucelabs and Protractor Output follow...)

Do you have any idea what could cause this?

**Comment by wswebcreation** [comment]
Hi @rreitmann 

What can help speed up (don't expect large numbers) is to disable the following in your capabilities

```js
        recordScreenshots: false,
        recordVideo: false,
```

> Edge is always much slower than the other browsers (takes 2-6 times the time see Protractor Output)

That could be the webdriver implementation, nothing Protractor can do about.
You can also check your script again to do some optimizations there. Each webdriver call you don't need to make will speed up your execution time. 

> If it runs solely, Edge fails rarely (but it does sometimes)
> Edge fails often if all 4 browser tests run concurrently (Saucelabs and Protractor Output follow...)

I haven't experienced your flakeyness for my customer. The only thing I've experienced was that sometimes I have webdriver errors because the VM could not be started. That's why I use [protractor-flake](https://github.com/NickTomlin/protractor-flake) to rerun the the specs that failed again.

**Comment by rreitmann** [comment]
Hi,

our tests run stable now. I found out that the error was not occurring while protractor was waiting to sync with the page (as the error message told) instead it was occurring when protractor was waiting for the visibility of elements we want to click on:
```javascript
function waitFor(htmlElementId) {
  var deferred = protractor.promise.defer();
  var expectedCondition = protractor.ExpectedConditions;
  var el = element(by.id(htmlElementId));
  browser.wait(expectedCondition.visibilityOf(el), 60000).then(function() {
    deferred.fulfill(el);
  });
  return deferred.promise;
}
```
For some reason Edge needs a huge timeout (60 s  in this case). Since this is not protractors responsibility you can close this issue.
