### ISSUE TITLE
Run tests without open browser app

### ISSUE THREAD

**Issue by cristopher-rodrigues** [angular/protractor#4496]
Its possible run protractor tests without open browser app?
I want test a chat app with multiples browsers (users).

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by cristopher-rodrigues** [comment]
Sorry @wswebcreation  my bad.
