### ISSUE TITLE
How can i test "angular" application  using "protractor"?

### ISSUE THREAD

**Issue by Vasundhara-vasu** [angular/protractor#4503]
Hi All,

I have knowledge on how to test "angularJS" application using "protractor tool" using "eclipse" . I am unable to test "angular" application with the same "angularJS" set up in "eclipe".

So can any one suggest me how to test "angular" applicaiton using "Protractor" in "Eclipse"

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by Vasundhara-vasu** [comment]
@wswebcreation ,

Thanks for your reply. 

I need a solution to do"end to end testing" of "angular" application using "protractor" .

**Comment by wswebcreation** [comment]
Please the docs on this git or use Google for some good tutorials. All question concerning usage can be asked on SO or gitter

**Comment by Vasundhara-vasu** [comment]
Yes i did already , i searched in google , i found links for "angularJs application end to end testing using protractor" , i couldn't find any link which helps me to test "angular application end to end testing using protractor" ..
