### ISSUE TITLE
Protractor cucumber Typescript - Unable to create new service: internetexplorerdriverservice

### ISSUE THREAD

**Issue by amsoma** [angular/protractor#4518]
Hi,
 I'm getting the following error message when I try to launch via IE
"Unable to create new service: internetexplorerdriverservice"

Please find the details below:
(Protractor+cucumber+Typescript)
- Node Version: `6.11.3'
- Protractor Version: `5.1.2`
- Browser(s): `IE 11`
- Operating System and Version `Windows 7`
- Your protractor configuration file

Anyone faced such issues?

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
