### ISSUE TITLE
Support for browser ESR releases

### ISSUE THREAD

**Issue by benjaminapetersen** [angular/protractor#4525]
Greetings!

I've hit a snag where our CI env runs Firefox ESR 52.4 (extended support release).  This is not one of the latest 2 versions of the browser (defined [here](https://github.com/angular/protractor/blob/master/docs/faq.md#which-browsers-are-supported), but is important for large projects:

https://www.mozilla.org/en-US/firefox/organizations/

> Who is it for?

>  Firefox ESR is intended for groups who deploy and maintain the desktop environment in large 
> organizations such as universities and other schools, county or city governments and businesses.

It may be worth it for protractor to support these releases as well, at least the most recent one.

**Comment by benjaminapetersen** [comment]
Just left a comment on a [close issue here](https://github.com/angular/protractor/issues/3044#issuecomment-334168753), perhaps the problem is less with supporting ESR and more about other browsers needing an analogous `chromeOptions` under `capabilities`.

**Comment by NickTomlin** [comment]
I don't think there's anything we can do here unfortunately as it is a driver/configuration issue. If there's an option that we aren't passing to FF feel free to open up a pull request that allows us to pass it through. Otherwise, i'd suggest looking on Stack Overflow or a gecko related forum.

Good luck!

**Comment by benjaminapetersen** [comment]
ok thanks!
