### ISSUE TITLE
Protractor ignores connection to DB via ssh

### ISSUE THREAD

**Issue by vitebchanka** [angular/protractor#4562]
Hello.
I have the next tricky task: I need to test a chat and then make a query to DB and check billing.

We are using mysql over ssh connection.
I found the next library to work with:
https://www.npmjs.com/package/mysql-ssh
I tried it and it works.
But when I am trying to set it in my spec I see nothing in console.log and the specs always runs successfully even if I change sql query to non-valid:
![image](https://user-images.githubusercontent.com/12962582/32089588-8235518c-baf3-11e7-8464-38627d62a880.png)
I do not have ideas how to push it working.
I am using latest version of protractor.

Thanks.

**Comment by viktorpergjoka** [comment]
Maybe add an catch and check if the promise got rejected, so you could get more information.

.catch(err => {
    console.log(err)
})

**Comment by viktorpergjoka** [comment]
Maybe also check for missing returns in your pomise chain

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
