### ISSUE TITLE
Protractor does not wait for nested http request

### ISSUE THREAD

**Issue by bunnu** [angular/protractor#4582]
Bug report
---

- Node Version: `6.10.2`
- Protractor Version: `5.1.2`
- Angular Version: `4.4.6`
- Browser(s): `Chrome 62.0.3202.89`
- Operating System and Version ` Windows 10.0.16299 `
- Your protractor configuration file
default generated by ng new:
```javascript
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  }
};

```
- A relevant example test
app.e2e-spec.ts
```javascript
import { AppPage } from './app.po';
import { element, by, browser } from 'protractor';

describe('myapp App', () => {
  let page: AppPage;

  beforeEach(() => {
    page = new AppPage();
    page.navigateTo();
  });

  it('should display Call 2 finished.', ()=>{
    let anchor = element(by.id('start'));
    anchor.click();
    let status = element(by.id('status'));
    expect(status.getText()).toBe('Call 2 finished.');
  })
});

```
app.component.ts
```javascript
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/delay';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  status = ''

  constructor(private http: HttpClient) {
  }

  private doNestedHttpCall() {

    this.status = 'Starting call1.';
    this.http.get("https://httpbin.org/delay/5").subscribe(() => {
      this.status = 'Call 1 finished. Starting call2';
      this.http.get("https://httpbin.org/delay/5").subscribe(() => {
        this.status = 'Call 2 finished.';
      })
    })

    // Observable.of("1").delay(5000).subscribe(() => {
    //   this.status = 'Call 1 finished. Starting call2';
    //   Observable.of(2).delay(5000).subscribe(() => {
    //     this.status = 'Call 2 finished.';
    //   });
    // })
  }
}
```
app.component.html
```html
<a id="start" href="javascript:void(0);" (click)="doNestedHttpCall()">Click here for nested http call</a><br>
<span id="status">{{status}}</span>
```
- Output from running the test
```
[10:48:16] I/update - chromedriver: file exists c:\Entwicklung\angular\myapp\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.33.zip
[10:48:16] I/update - chromedriver: unzipping chromedriver_2.33.zip
[10:48:16] I/update - chromedriver: chromedriver_2.33.exe up to date
[10:48:16] I/launcher - Running 1 instances of WebDriver
[10:48:16] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:12877/devtools/browser/72508994-d670-4e49-a1d0-0633d961543d
Jasmine started

  myapp App
    × should display Call 2 finished.
      - Expected 'Call 1 finished. Starting call2' to be 'Call 2 finished.'.
          at UserContext.<anonymous> (c:\Entwicklung\angular\myapp\e2e\app.e2e-spec.ts:16:30)
          at new ManagedPromise (c:\Entwicklung\angular\myapp\node_modules\selenium-webdriver\lib\promise.js:1067:7)
          at ControlFlow.promise (c:\Entwicklung\angular\myapp\node_modules\selenium-webdriver\lib\promise.js:2396:12)
          at TaskQueue.execute_ (c:\Entwicklung\angular\myapp\node_modules\selenium-webdriver\lib\promise.js:2970:14)
          at TaskQueue.executeNext_ (c:\Entwicklung\angular\myapp\node_modules\selenium-webdriver\lib\promise.js:2953:27)
          at asyncRun (c:\Entwicklung\angular\myapp\node_modules\selenium-webdriver\lib\promise.js:2860:25)
          at c:\Entwicklung\angular\myapp\node_modules\selenium-webdriver\lib\promise.js:676:7
          at process._tickCallback (internal/process/next_tick.js:109:7)

**************************************************
*                    Failures                    *
**************************************************

1) myapp App should display Call 2 finished.
  - Expected 'Call 1 finished. Starting call2' to be 'Call 2 finished.'.

Executed 1 of 1 spec (1 FAILED) in 7 secs.
[10:48:26] I/launcher - 0 instance(s) of WebDriver still running
[10:48:26] I/launcher - chrome #01 failed 1 test(s)
[10:48:26] I/launcher - overall: 1 failed spec(s)
[10:48:26] E/launcher - Process exited with error code 1
```

- Steps to reproduce the bug

1. create a new angular application with ng new
1. replace app.component.ts, app.component.html and app.e2e-spec.ts with examples given above.
1. run protractor  (ng e2e)

Protractor should wait until the nested http request is finished. Currently Protractor checks the expectations direct after the first http request is finished. If you use two nested Observables with delay (as shown in the comment section in the code above), Protractor waits until the nested Observable is finished.

**Comment by Haseeb90** [comment]
Is using Async/Await an option in your case? Rather than having nested calls you can use Async/Await and get the job done in a nice, neat and clean manner. Of course, that would mean that you have to disable SELENIUM_PROMISE_MANAGER in your conf... See this link.
https://github.com/SeleniumHQ/selenium/issues/2969

Not 100% sure about Observables but I don't think protractor is waiting for the Observables to finish.. It might just be waiting for 5sec and that timeout just pauses and sets the value.

If your project isn't too big I would suggest moving to Async/Await. We're currently in the middle of switching over and trust me it's a lot easer to handle such cases as yours.

**Comment by bunnu** [comment]
Thanks for your suggestions @Haseeb90. Right now async/await isn't a option for me. In my understanding Observables in Angular are running in Angular Zone. So Protractor should be able to wait. You can increase the time in the observable.delay example, protractor still will wait.

**Comment by lyml** [comment]
Due to having the same problem with our protractor tests I have debugged the issue and I found the underlying cause to be a bug in angular. I believe that the reason is that Angulars ngZone considers itself stable when the microtask queue is drained and Angulars Testability.whenStable considers itself stable when both the macrotask queue and the microtask queue is completed.

To consolidate this Testability.whenStable listens to the ngZone.onStable event which fires when there are no microtasks left and then checks if there are pending macrotasks.

However when the last macrotask in the queue is completed there might still be more macrotasks added afterwards (presumably by an event task, though I haven't been able to confirm that). The issue can be fixed by waiting for a 0 second macrotask (e.g. setTimeout) to make sure that no more macrotasks are added.

I will clean up my solution a bit and submit it as merge request into angular this weekend (2017-12-10).

**Comment by bunnu** [comment]
Hi lyml, thanks a lot for your feedback and your investigation.

**Comment by lyml** [comment]
I have added a custom build of angular core 4.4.6 with the patch which is currently going through the angular pull request process. You can use that custom build while waiting for the fix to be adopted by angular.

See:

https://github.com/lyml/chained-http/tree/with-patched-angular

For a working example. The package.json contains a reference to my custom build.

**Comment by SchnWalter** [comment]
I don't think that protractor should deal with the example you give here. Your method should be updated to use the RxJS `mergeMap()` operator, the example feels borderline broken.

If this behavior doesn't manifest in other situations, like when triggering ChangeDetection, then this story should be closed.

I have a similar issue (with a login page) where the API request triggers a router navigation on completion and for some reason when I check if the URL has changed, `await browser.waitForAngular()` doesn't do the job, and as a hack I'm using a `await browser.findElement()` to check the page title instead of reading the current URL after waiting for Angular, but this feels hackish and I'll look into it later this week.
