### ISSUE TITLE
Get Suite Name in conf.js

### ISSUE THREAD

**Issue by Pratish487** [angular/protractor#4592]
Hi there!

When we execute command [protractor conf.js --suite=user_regression] from command line interface, I want to get the suite value 'user_regression' in conf.js file. 

Is there any way we can get the value?
Or 
Is there any way I can pass environment and suite with single parameter...

As per our requirements, I have to pass only 1 param for build in Jenkins. If I can get the suite name, I can hard code the environment based on suite mentioned in CLI ...

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
