### ISSUE TITLE
element not found in headless chrome browser

### ISSUE THREAD

**Issue by jainAdijain** [angular/protractor#4652]
Hi, 
I am using chrome as browser to run my specs, all are executing very fine.
But when I change the browser to **--headless** by mentioning as follows in the protractor.conf.js

```
'chromeOptions': {
            args: ["--headless", "--disable-gpu"]

}
```

and ran the specs, then it displays an error on some specs as -  ` Failed: No element found using locator: By(css selector, *[id="more"])`

Why is the same spec passing when the browser is without headless? 

I have also posted this on SO - https://stackoverflow.com/questions/48126468/no-element-found-using-locator-bycss-selector-id-more

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter because it involves usage and debugging.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I'm going the close it for now.

Thanks!
