### ISSUE TITLE
Could not find Angular on page https://www.facebook.com/ : retries looking for angular exceeded

### ISSUE THREAD

**Issue by lakhiwala** [angular/protractor#4654]
My todo-spec.js is
describe('angularjs homepage todo list',function(){
    it('should add a todo', function(){
        browser.get('https://www.facebook.com/')
        element(by.id('email')).sendKeys('xxxxxxxxxxxxxxxxxxx')
        element(by.id('u_0_a')).click()
        var errorMessage=element.all(by.className('u_0_a')).get(0).getText()
        expect(errorMessage).toEqual("The password that you've entered is incorrect. Forgotten password?")
    })
})

conf.js is
exports.config={
    //seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['todo-spec.js'],
    capabilities: {
        'browserName': 'chrome'
    },
    onPrepare: ()=>{
        browser.manage().window().maximize();
    }
}
When I run conf.js i get following error:
Failed: Angular could not be found on the page https://www.facebook.com/.If this is not an Angular application, you may need to turn off waiting for Angular.

I have tried browser.ingnoreSynchronization=true;
It does not work.

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
