### ISSUE TITLE
Unable to set capabilities at run-time

### ISSUE THREAD

**Issue by vinodkpasi** [angular/protractor#4831]
I am trying to set capabilities at run time inside **onPrepare** function of **protractor configuration file** but it is not setting the value?

        browser.getProcessedConfig().then(function (conf) {
                         conf["capabilities"]["chromeOptions"]["prefs"]["download"]["default_directory"] = "C:/Automation/Drivers";
            
                    });

**Comment by CrispusDH** [comment]
For what reason do you need it to do it in Run Time?

**Comment by yongcy** [comment]
Yes, You can't change it during run-time, this is as protractor designed.  Because protractor will launch an browser instance before any case beginning, And when code run into **onPrepare** function, the browser instance had launched with the capabilities.  Those changes of capabilities won't take effect on already launched browser instance.

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
