### ISSUE TITLE
accessing params value in config file

### ISSUE THREAD

**Issue by bharukaRupesh** [angular/protractor#4929]
Hi,

I want to access value of parameters value passed through command line as below,

**config.js file**

```
params: {
        baseURL:'https://vl-pun-pm-aut01.bmc.com:8443/',
        browserParam:"firefox"
    }, 
    
    capabilities: {
        browserName:params.browserParam,
        marionette : true,
        acceptInsecureCerts : true,
    }
```
**Command:** protractor config.js --parameters.browserParam="chrome"

I am trying to access ```browserParam``` of params ```inside capabilities``` but getting error.

Is there a way we can access it?

**Comment by IgorSasovets** [comment]
@bharukaRupesh , I'd recommend you to ask such questions in the [gitter](https://gitter.im/angular/protractor) room or on the stack overflow because it's not an issue with protractor itself. Regarding your question, you can pass env variables from command line as following `BROWSER=chrome protractor config.js` and then in protractor conf access it using `process.env.BROWSER`.

**Comment by bharukaRupesh** [comment]
Thanks @IgorSasovets 

Basically, I was not aware of [gitter](https://gitter.im/angular/protractor) that's why I was putting my questions here at [git]()

**My apology!**

**Comment by IgorSasovets** [comment]
@bharukaRupesh , thanks)
