### ISSUE TITLE
Protractor test case execution in Eclipse - SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by wattle9** [angular/protractor#4963]
Hi all,

I am using Mac book installed with Eclipse Photon.
Node version - V10.10.0
Protractor version - 5.4.1

When trying to execute basic Protractor test case, I get below error.

Any suggestion to fix this will be highly appreciated.

/Users/abc/eclipse-workspace/projecttest/projecttest/node_modules/protractor/built/logger.js:79
    info(...msgs) {
         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/abc/eclipse-workspace/projecttest/projecttest/node_modules/protractor/built/configParser.js:6:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by GitSage** [comment]
The function in question is:

```
    /**
     * Log INFO
     * @param ...msgs multiple arguments to be logged.
     */
    info(...msgs) {
        this.log_(LogLevel.INFO, msgs);
     }
```


Seems like you've got a really old version of node. That's a [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax), which [has been supported since Node 5](https://node.green/). 

Check your version of Node. Protractor requires Node `6.9.x`. If your global version is up-to-date it's possible that Eclipse is using its own version of Node, in which case you can presumably update it in Node's settings.

In the future you should post questions like this to StackOverflow. This issue board is for bugs in Protractor.

**Comment by wattle9** [comment]
I fixed this issue in below manner.
installed this Snapshot, http://oss.opensagres.fr/angularjs-eclipse/1.3.0-SNAPSHOT/
Run Configurations-> Protractor..Changed Node JS install to be Native Node JS.
