### ISSUE TITLE
security vulnerability 

### ISSUE THREAD

**Issue by maxisam** [angular/protractor#5173]
I got a notification from github saying cryptiles has a security vulnerability issue.

https://github.com/maxisam/ngx-clipboard/network/alert/yarn.lock/cryptiles/open

And ask me to upgrade it to 4.1.2

dependency tree is like 

protractor -> webdriver-manager ->  request "^2.78.0" -> hawk "~6.0.2" -> cryptiles "3.x.x"

**Comment by GitSage** [comment]
Your link gives a 404.

I think all you need to do though is remove your `webdriver-manager` and reinstall it. To make a long story short, hawk is no longer a dependency since `webdriver-manager v.12.1.0` updated its `request` dependency in July 2018.

The Protractor team could make this easier on users by updating protractor's `package.json` from `"webdriver-manager": "^12.0.6"` to `"webdriver-manager": "^12.1.0"`. Then, if I'm not mistaken, users could correct this issue by simply running `npm install` .

**Comment by maxisam** [comment]
Yeah, that is what I am trying to do here. I want to bring this matter to protractor team's attention, so they can update their package.json instead of everyone update their package.json

**Comment by cnishina** [comment]
Just went through and did a webdriver-manager audit and did a release to 13.0.0. I also did an audit on Protractor. We have some vulnerabilities but those exist in the testapp (for our own testing) and the website (but it has to be that way because of dgeni). This is done. Closing this issue.
