### ISSUE TITLE
CI Build is failing with no functional changes

### ISSUE THREAD

**Issue by Amy-Lynn** [angular/protractor#5176]
PR that's just updating the docs, no code changes: https://github.com/angular/protractor/pull/5174

Getting the following errors in CircleCI: 

```
[10:24:55] I/direct - Using ChromeDriver directly...
[10:24:55] E/launcher - session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-141-generic x86_64)
[10:24:55] E/launcher - SessionNotCreatedError: session not created: Chrome version must be between 71 and 75
```

My PR is also failing for the same reasons

**Comment by cnishina** [comment]
You will need to set the chromedriver version to 2.44. I had to set it in our config as well since they are on Chrome 69. https://github.com/angular/protractor/blob/master/.circleci/config.yml#L35

So when downloading chromedriver, you'll need something like `webdriver-manager update --versions.chrome 2.44`. I got 2.44 based on http://chromedriver.chromium.org/downloads

I am also looking into downloading a Chromium based on the ChromeDriver so things just work. Closing this issue.
