### ISSUE TITLE
WebDriverError: No active session with ID

### ISSUE THREAD

**Issue by anilreddii** [angular/protractor#5215]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: `v10.14.2`
- Protractor Version: `5.4.2`
- Angular Version: ``
- Browser(s): `chrome`
- Operating System and Version `windows 10`
- Your protractor configuration file
- A relevant example test
- Output from running the test
WebDriverError: No active session with ID 4f54805f9d7fbf34dba27065eba93f71 
Failed: No active session with ID 4f54805f9d7fbf34dba27065eba93f71

This error only happens when i run a suite on TFS 
locally everything is working fine

**Comment by cnishina** [comment]
There is not enough information to reproduce this. This also looks like a support question since Protractor itself works but TFS set it appears to be the issue. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor) or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
