### ISSUE TITLE
issue is for angular 4.4.6 version not able click any thing in webpage for one aplication

### ISSUE THREAD

**Issue by VishnuSomisety92** [angular/protractor#5251]
Please let me know for angular 4 + version protractor is supporting or not?

beacuse i am working on one application i cannot click anything in a webpage for multiple xpath and css

**Comment by cnishina** [comment]
Protractor supports Angular and AngularJS. There hasn't been a change here. I would avoid using xpath because it causes your tests to be brittle.

This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
