### ISSUE TITLE
element locater by.css throws error if the selector has ":" while by.id works fine

### ISSUE THREAD

**Issue by VamsiDevalla** [angular/protractor#5306]
Bug report
---
I am using element(by.id()) most of the time but tried using $('#_myID_') and found that the later syntax throw invalid syntax error if the ID contains **:** .

- Node Version: `10.16.0`
- Protractor Version: `5.3.1`
- Angular Version: `5.2.2`
- Browser(s): `chrome`
- Operating System and Version `mac os`
- Your protractor configuration file
- A relevant example test
$('#test-05:0C:07:mN')
    .getText().then((data) => {
        expect(data.split("\n")[0]).equals("test");
    });
- Output from running the test
 InvalidSelectorError: invalid selector: An invalid or illegal selector was specified
- Steps to reproduce the bug
Give an ID containing "**:**" to an element and try to locate it using **element(by.css('#_yourID_') or $('#_yourID_')**.
if you use **element(by.id('_yourID_')** it works fine.
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by cnishina** [comment]
This is because it does a look up for a WebElement with selenium-webdriver's method. So this should be $('[id="yourId"]'). 

It is the difference between By.css:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L151

and By.id:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L162

**Comment by VamsiDevalla** [comment]
Thank you
