### ISSUE TITLE
How to handle element not found exception

### ISSUE THREAD

**Issue by mohit-excelindia** [angular/protractor#631]
Hi @juliemr @wlingke

Is there a way in Protractor to handle element not found exception, similar to what we can do in Java version of Selenium webdriver?

Thanks,
Mohit

**Comment by ahmedusa** [comment]
Hi @Droogans 
I could find the custom Exception error handler code in the astrolabe. could you please add it over here in the comment.

**Comment by Droogans** [comment]
https://github.com/stuplum/astrolabe/blob/963eb5001d7d3ce019a6ed66cec62ba2bb0d316b/lib/astrolabe/base.js#L45

It simply hooks up to the [exceptions npm module](https://www.npmjs.com/package/exceptions), which contains more information. Or, you can take a look [at the example that uses `this.exception` on Astrolabe's readme](https://github.com/stuplum/astrolabe#usage).

However, keep in mind that the tutorial referenced above is very stale. I would not recommend making too many custom exceptions. Sometimes it's useful for invalid situations in your business logic, but overall, `throw new Error()` works just as well, without the extra dependency.

At some point I might redo it, since vanilla ES6 in node 6+ makes Astrolabe obsolete (it's just a fancy way to make very uniform looking es6 classes, with some URL convenience functions that are easy to reproduce). If I were to rewrite it today, it would be using at least protractor 4.0, with typescript featured prominently. That might make more sense once typescript releases 2.0.
