### ISSUE TITLE
Support redirecting using window.location

### ISSUE THREAD

**Issue by sgronblo** [angular/protractor#762]
Have a non-SPA Angular application that basically is a collection of multiple small Angular apps. If I redirect to another page using `window.location` Protractor I get the _Error while waiting for Protractor to sync with the page_ message.
To get around this I currently have to put in something like `browser.sleep(3000);` but would be nice if I didn't have to slow down the test with this sleep and be worried about test breakage in case the redirect for some reason took longer than 3 seconds in this case.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this since we have some usable (albeit a little messy) workarounds like turning off synchronization before redirecting (which is what I currently do to handle flows in an application that move through non-angular pages) and we haven't seen any action on this issue in a year and a half.

Please feel free to re-open if there's more work to do here.
