### ISSUE TITLE
Post url using protractor

### ISSUE THREAD

**Issue by Hardcode37** [angular/protractor#82]
Does protractor allow post as well as get. My app requires a post to my api however I can not find a post that allows me to specify the url and params.

I can do this 

ptor.get('http://localhost:22222/pathtoapi?params=1');

but I can not do 

var params = 1;
ptor.post('http://localhost:22222/', params,);

is this something that maybe added in the future or is it already possible via another method.

**Comment by joffrey-bion** [comment]
I'm facing the same issue here. My use case is that my webapp is normally accessed via an external portal that calls us with a POST request. This external portal is only used from the production and similar ones are used on UAT environments. In development, we directly access the webapp through a test page making POST requests emulating the portal.

I can't use the portal because it would not target the right platform, neither can't I go to the test page from protractor because of security reasons. I simply want to navigate to my webapp via a POST request.
So far, I started my tests with `browser.get()`, passing all params in the URL, but that is not consistent with what actually happens in real life, so I'd like to perform an actual browser POST. Isn't this at all possible?
