### ISSUE TITLE
Split a step definition file into many scenarios to run in parallel

### ISSUE THREAD

**Issue by asmi85** [angular/protractor#864]
Hello everyone, 

I am using Protractor and cucumberJS (https://github.com/cucumber/cucumber-js).

Can someone please help me how can i split the scenarios in the step definition file to run them in parallel. 

Thanks a  lot

**Comment by edgarechm** [comment]
Executing **same tests** in different browsers at the same time, is no problem. The interesting thing is to make each **instance run a different set of features**.

I tried the following but I get **_"undefined warnings messages"_** as if my spec.js files don't exist. They may be warnings, but enough to break my test, since specs **are not found**.

Here's my config file:

```
var featsLocation = 'features/';
var stepsLocation = 'steps/';

exports.config = {
		rootElement: 'html',
		chromeDriver: './srv/build/applications/chromedriver/chromedriver_win32/chromedriver.exe',
		seleniumServerJar: './node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone.jar',
		params:{
			authURL:'',	
			login:{
				email:'',
				passw:''
			}
		},
		resultJsonOutputFile:'',
		getPageTimeout: 60000,
		allScriptsTimeout: 60000,
		maxSessions: 2,
		framework: 'custom',
		frameworkPath: require.resolve('protractor-cucumber-framework'),
		multiCapabilities:[
		     {	
		    	 browserName: 'chrome',
		    	 chromeOptions:{
		    		 args:["--headless"]
		    	 },
		    	 name: 'CAPABILITY_1',
		    	 logName: 'LOGNAME1_USERNAME1_A',
		    	 shardTestFiles: false,
		    	 maxInstances: 1,
		    	 count: 1,
		    	 specs: [   featsLocation+'authenticateCSM.feature'
		    	            , featsLocation+'locationSearch.feature'
		    	        ]
		     },{                  
		    	 browserName: 'chrome',
		    	 chromeOptions:{
		    		 args:["--headless"]
		    	 },
		    	 name: 'CAPABILITY_2',
		    	 logName: 'LOGNAME1_USERNAME2_B',
		    	 shardTestFiles: false,
		    	 maxInstances: 1,
		    	 count: 1,
		    	 specs: [   featsLocation+'authenticateCSM.feature'
		    	            , featsLocation+'shipmentErrors.feature'
		    	        ]
		     }],

		onPrepare: function(){
			global.EC = protractor.ExpectedConditions;
		},		
		baseUrl: '',
		cucumberOpts: {
			tags: '',
			require: [
			            './support/*.js'
			          , stepsLocation+'shipmentErrors/shipmentErrors.spec.js'
			          , stepsLocation+'locationSearch/locationSearch.spec.js'
			         ],
			monochrome: true,
			strict: true,
			plugin: "json"
		},
};
```
URL and other parameters are passed using package.json.
When executed, I get a warning message telling me that the *.spec.js files are not defined, **BUT THEY ARE AND PLACED IN THIS LOCATION** (`steps/shipmentErrors/shipmentErrors.spec.js and steps/locationSearch/locationSearch.spec.js`):

> [LOGNAME1_USERNAME1_A] Warnings:
[LOGNAME1_USERNAME1_A]
[LOGNAME1_USERNAME1_A] 1) Scenario: CSM FinalMile: Get authenticated to test Werner CSM Finalmile (SMOKE) - features\authenticateCSM.feature:11
[LOGNAME1_USERNAME1_A]    Step: Given CSM FinalMile: Navigate to the Werner SSO initial page - features\authenticateCSM.feature:12
[LOGNAME1_USERNAME1_A]    Message:
[LOGNAME1_USERNAME1_A]      Undefined. Implement with the following snippet:
[LOGNAME1_USERNAME1_A] 
[LOGNAME1_USERNAME1_A]        Given('CSM FinalMile: Navigate to the Werner SSO initial page', function (callback) {
[LOGNAME1_USERNAME1_A]          // Write code here that turns the phrase above into concrete actions
[LOGNAME1_USERNAME1_A]          callback(null, 'pending');
[LOGNAME1_USERNAME1_A]        });
 

I may be having problems with the syntax of the config file... any clues how I should build it?
