### ISSUE TITLE
Any JS logger we can use with  protractor

### ISSUE THREAD

**Issue by mohit-excelindia** [angular/protractor#998]
HI @juliemr 
Can I use any javascript logger API to create log files just like Log4j for java?

Thanks,
Mohit

**Comment by GuyMograbi** [comment]
actually the question is pretty good. you cannot actually use any logger in protractor due to its async nature. 

if I do 
```
...
expect(element(by.css('.title')).getText()).toBe('my title');
console.log('hello world'); 
...
```

the `console.log` statement will actually run before the assertion. 
you can still use any logger library but only if you write all logs in `then` handlers. 

 this is a nice gist on how to wrap log4js so the log prints will be aligned to protractor's queue. 

https://gist.github.com/guy-mograbi-at-gigaspaces/7f28eacd4d49fbcb551f
